inaturalist/iNaturalistReactNative

tests/unit/components/Projects/Projects.test.js
The `expect` lines never actually completed before the test was terminated.  Switched to approach used in MyObservations.test.js
New to this stuff - so happy for other thoughts!
=> Fixes Projects.test.js false positive problem

ios/Gemfile.lock, ios/Podfile.lock, package-lock.json, src/components/LoginSignUp/AuthenticationService.js, src/components/ObsDetails/hooks/useObservation.js, src/components/UserProfile/UserProfile.js, src/models/Comment.js, src/models/index.js, src/providers/hooks/useObservations.js, tests/factories/LocalComment.js, tests/unit/components/Messages/Messages.test.js, tests/unit/components/ObsEdit/ObsEdit.test.js, tests/unit/components/PhotoLibrary/PhotoGallery.test.js
Fixes a few failures and warnings in our tests, and closes Realm when a hook is done with it which prevents jest from hanging forever.
=> Test fixes

.github/workflows/test.yml
As of 085eda25bffd12c5d84e89054e98665cd22af985 we should not have any flow errors in main, so it should be safe to run eslint and flow for CI.
=> Try to run eslint and flow as a part of CI

src/components/Explore/DropdownPicker.js, src/components/Explore/TaxonLocationSearch.js, src/sharedHooks/useRemoteSearchResults.js
Fixes crash that was happening due to /v2/search being updated to return type-specific records.
Also allows for only one dropdown to be displayed at a time on Explore.
=> Fix search results for Explore Dropdowns, Projects, Search

.vscode/settings.json, package-lock.json, src/components/Observations/ObsList.js, src/components/Observations/UploadProgressBar.js, src/components/Observations/UploadPrompt.js, src/components/Observations/hooks/useCurrentUser.js, src/components/Observations/hooks/useObservations.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, src/providers/uploadHelpers/uploadObservation.js, src/styles/observations/uploadProgressBar.js, src/styles/sharedComponents/bottomSheet.js, tests/unit/components/Observations/ObsList.test.js
=> Upload progress bar

src/components/LoginSignUp/Login.js, src/styles/login/login.js
This PR resolves issue #122 , by adding close button to the login screen.
=> Add close button to the login screen

src/components/ObsEdit/ObsEdit.js, src/styles/obsEdit/obsEdit.js
This PR resolves issue #134. 
Applied Platform specific style to show the title header on Android
.
=> Show title on Obs Edit

flow-typed/npm/react-native-safe-area-context_vx.x.x.js, src/components/Camera/FadeInOutView.js
Dipping my toes just a little bit into this React Native project...
=> Add flow types for `react-native-safe-area-context`; upgrade file to `@flow strict-local`.

ios/Podfile.lock, package-lock.json, package.json, src/components/Explore/Explore.js, src/components/Observations/ObsList.js, src/components/Observations/UserCard.js, src/components/SharedComponents/BottomSheet.js, src/components/SharedComponents/ObservationViews/LoginPrompt.js, src/components/SharedComponents/ObservationViews/ObservationViews.js, src/components/SharedComponents/ObservationViews/UploadProgressBar.js, src/components/SharedComponents/ObservationViews/UploadPrompt.js, src/components/SharedComponents/ObservationViews/hooks/useUploadObservations.js, src/components/SharedComponents/ObservationViews/hooks/useUploadStatus.js, src/components/UserProfile/UserProfile.js, src/components/UserProfile/hooks/useUser.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, src/sharedHooks/useCurrentUser.js, src/styles/sharedComponents/bottomSheet.js, tests/integration/MyObservations.test.js, tests/unit/components/Explore/Explore.test.js, tests/unit/components/LoginSignUp/AuthenticationService.test.js, tests/unit/components/Observations/ObsList.test.js, tests/unit/components/Projects/Projects.test.js, tests/unit/components/UserProfile/UserProfile.test.js
This makes the bottom sheet a regular sheet, not a modal. It moves the bottom sheets into `ObservationViews` where the actual `FlatList` lives. It snaps the bottom sheet away when a user scrolls down and snaps it back up when a user scrolls to the top of the screen.
Need to get one more test passing.
Closes #177.
=> UI updates to bottom sheet

src/components/Explore/FiltersIcon.js, src/components/LoginSignUp/Login.js, src/components/ObsDetails/DataTab.js, src/components/ObsDetails/ObsDetails.js, src/components/ObsEdit/AddID.js, src/components/ObsEdit/AddIDHeader.js, src/components/ObsEdit/ObsEdit.js, src/components/PhotoLibrary/GroupPhotoImage.js, src/components/PhotoLibrary/PhotoGalleryImage.js, src/components/SharedComponents/Buttons/CameraOptionsButton.js, src/components/SharedComponents/Buttons/EvidenceButton.js, src/components/SharedComponents/Footer.js, src/components/SharedComponents/ObservationViews/ObsCardDetails.js, src/components/SharedComponents/ObservationViews/Toolbar.js, src/components/SharedComponents/ObservationViews/UserCard.js
This PR resolves #156 .
- It replaces all the icons from material community Icon set to material Icon.
=> Use only material icon set 

src/components/PhotoImporter/PhotoGallery.js, src/components/PhotoImporter/PhotoGalleryImage.js, tests/factories/DevicePhoto.js, tests/integration/PhotoGallery.test.js, tests/jest.setup.js, tests/unit/components/PhotoImporter/PhotoGallery.test.js
Added a test to make sure that the checkmark is shown when a photo is selected, which closes #221.
Also started using the FlatList `extraData` prop to rerender the list.
=> Test: checkmark is shown when photos are selected

package-lock.json, package.json, src/components/ObsEdit/Notes.js, src/components/ObsEdit/ObsEdit.js, src/components/ObsEdit/OtherDataSection.js, tests/unit/components/ObsEdit/ObsEdit.test.js
=> Move notes input field above keyboard on focus

src/components/Camera/StandardCamera.js, src/components/SharedComponents/PhotoCarousel.js
=> Hide flash on devices with no flash capability

package-lock.json
=> 290: Fix crash on Android when navigating to New Observation screen

src/components/ObsEdit/IdentificationSection.js, src/components/ObsEdit/ObsEdit.js, src/components/ObsEdit/SaveDialog.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, src/navigation/mainStackNavigation.js, src/providers/ObsEditProvider.js
Closes #284
- One save dialog for a single observation with changes
- One save dialog for multiple observations, when navigating back to Group Photos
=> Add save dialog to back button in ObsEdit

src/api/observations.js, src/components/ObsDetails/Attribution.js, src/components/ObsDetails/DataTab.js, src/components/ObsDetails/ObsDetails.js, src/components/Observations/ObservationViews.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, src/realmModels/Application.js, src/realmModels/Observation.js, src/realmModels/User.js, src/realmModels/index.js, tests/factories/RemoteObservation.js, tests/unit/components/ObsDetails/ObsDetails.test.js
=> Fix copyright in data tab of ObsDetail; improve data fetching

src/components/Observations/UploadProgressBar.js, src/providers/ObsEditProvider.js, src/realmModels/Observation.js, src/sharedHelpers/dateAndTime.js, src/sharedHelpers/parseExif.js, src/sharedHooks/useUploadObservations.js, tests/unit/helpers/photoExif.test.js
=> Ensure observed_on_string is actually a string for upload

src/components/ObsEdit/AddID.js
=> Allow keyboard click propagation - #322

src/components/Observations/ObsListHeader.js, src/components/Observations/ObservationViews.js, tests/unit/components/Projects/ProjectObservations.test.js
Fixes issue #298 and #339 
Ended up translating the entire list rather than just the header.
=> Fix unclickable observations bug (#298)

ios/Podfile.lock, package-lock.json, package.json, src/providers/ObsEditProvider.js, src/sharedHooks/useUploadObservations.js, tests/jest.setup.js
Adds functionality to keep a user's device awake while a user is uploading observations.
=> Keep phone awake during uploads

src/providers/ObsEditProvider.js
=> Cleanup unsaved changes state after use

src/components/MediaViewer/MediaViewerModal.js
=> Trigger system back button from Modal in Android

src/providers/ObsEditProvider.js
=> Bug fix for importing photos to obs without evidence

react-native-logs.config.js, src/components/About.js, src/components/App.js, src/components/LoginSignUp/AuthenticationService.js, src/components/LoginSignUp/Login.js, src/components/LoginSignUp/Logout.js, src/components/Observations/ObsListHeader.js, src/components/styledComponents.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, src/providers/contexts.js, src/realmModels/Observation.js, src/realmModels/User.js, src/realmModels/index.js, src/sharedHooks/useCurrentUser.js, tailwind.config.js, tests/jest.setup.js, tests/unit/components/LoginSignUp/AuthenticationService.test.js, tests/unit/components/ObsDetails/ObsDetails.test.js
Closes #373
This seems to address the issue, at the expense of not actually deleting the Realm file on signout, which I think is fine assuming we delete all the data. There are a number of other changes here to logging and the about screen. The logging might be paranoid so I can remove it if it seems excessive. I'd definitely appreciate another set of eyes on this.
=> Fix sign out after force quit in Android

package-lock.json, package.json, src/components/Messages/Messages.js, src/components/SharedComponents/Tabs.js, src/navigation/mainStackNavigation.js, tests/jest.post-setup.js, tests/unit/components/Tabs.test.js
=> Create reusable tab components

src/components/About.js, src/components/Identify/GridItem.js, src/components/LoginSignUp/Login.js, src/components/LoginSignUp/Logout.js, src/components/ObsEdit/DeleteObservationDialog.js, src/components/ObsEdit/IdentificationSection.js, src/components/ObsEdit/LocationPicker.js, src/components/ObsEdit/ObsEdit.js, src/components/ObsEdit/SaveDialog.js, src/components/PhotoImporter/GroupPhotosFooter.js, src/components/PhotoImporter/PhotoGallery.js, src/components/SharedComponents/Buttons/Button.js, src/components/SharedComponents/DeletePhotoDialog.js, src/components/UiLibrary.js, src/components/UserProfile/UserProfile.js, tailwind.config.js
=> Update Button component with new styling

src/components/ObsDetails/ObsDetails.js, src/components/SharedComponents/Tabs.js
=> 380 Make obs detail page use reusable tabs component

src/components/Projects/ProjectTabs.js
=> 379 Make projects page use tab component

src/components/Observations/ObservationViews.js
=> Fix flatlist height in observations view

src/components/ObsDetails/ActivityItem.js, src/components/ObsDetails/ActivityTab.js, src/components/ObsDetails/ObsDetails.js, src/components/SharedComponents/InlineUser.js, src/components/SharedComponents/UserIcon.js, src/components/UiLibrary.js, tests/unit/components/ObsDetails/ActivityTab.test.js, tests/unit/components/ObsDetails/ObsDetails.test.js, tests/unit/components/SharedComponents/InlineUser.test.js
#398 
Base component for inline user. Simple user icon for fallback. Not totally complete because text is not up to spec
=> Create base inline user component

.eslintrc.js, README.md, package-lock.json, package.json, src/components/SharedComponents/InlineUser.js, src/components/SharedComponents/Tabs.js, src/components/SharedComponents/UserIcon.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl
=> 416 eslint a11y

ios/Podfile.lock, src/components/Observations/GridItem.js, src/components/Observations/ObsCardStats.js, src/components/SharedComponents/ActivityCount.js, src/components/UiLibrary.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, tests/unit/components/Observations/ObsCard.test.js, tests/unit/components/Observations/ObsList.test.js
=> Activity Count component

src/components/DisplayTaxonName.js, src/components/Observations/ObsCardDetails.js, src/sharedHelpers/taxon.js, tests/unit/components/DisplayTaxonName.test.js, tests/unit/components/Observations/ObsCard.test.js, tests/unit/components/Observations/ObsCardDetails.test.js, tests/unit/components/Projects/ProjectObservations.test.js
#435 
list view common name first
list view sci name first
grid view sci name first
grid view common name first
=> 435 - Create taxon name component

ios/Podfile.lock, package-lock.json, package.json, src/components/DisplayTaxonName.js, src/components/Observations/GridItem.js, src/components/Observations/ObsCardDetails.js, src/components/Observations/ObsGridItem.js, src/components/Observations/ObsStatus.js, src/components/Observations/ObservationViews.js, src/components/Projects/ProjectObservations.js, src/components/styledComponents.js, tests/unit/components/DisplayTaxonName.test.js, tests/unit/components/Projects/ProjectObservations.test.js
#436 
Did not add spacing or margins to the list yet. Just built to the issue spec. I do think 172x172 is little small
=> 436 obs grid item

src/components/Observations/UserCard.js, src/i18n/initI18next.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/l10n/es.ftl, src/i18n/l10n/es.ftl.json, src/i18n/strings.ftl, tests/integration/MyObservations.test.js
=> 423 translation interpolations

src/components/Camera/StandardCamera.js, src/components/SharedComponents/BottomSheet.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, src/styles/sharedComponents/bottomSheet.js, tests/unit/components/Camera/StandardCamera.test.js
#471 
https://user-images.githubusercontent.com/13311268/222974139-6b21fca7-63f0-4c71-92fa-a503febbf82c.mov
=> 471 create camera cancel bottom sheet

src/components/PhotoImporter/GroupPhotos.js, src/components/SharedComponents/FloatingActionBar.js, src/navigation/ContextHeader.js, src/navigation/mainStackNavigation.js, src/navigation/navigationOptions.js, src/navigation/rootDrawerNavigation.js
#481 
ex w/ subtitle:
passing subtitle:
=> Create custom header

src/components/SharedComponents/PhotoCarousel.js
=> Use trash-outline icon

src/navigation/BottomTabNavigator/CustomTabBar.js, src/navigation/BottomTabNavigator/NavButton.js, src/navigation/BottomTabNavigator/index.js
=> Center tab bar icons

src/components/Observations/ObsPreviewImage/index.js, src/components/PhotoImporter/GroupPhotoImage.js
=> Use ObsPreviewImage for photo gallery and use PhotoCount component

src/components/MyObservations/MyObservations.js, src/components/MyObservations/Toolbar.js, src/navigation/ContextHeader.js
=> add safe area to headers

src/components/Camera/StandardCamera.js
=> Rotate camera checkmark in landscape

package-lock.json, package.json, src/components/MyObservations/Toolbar.js, src/providers/ObsEditProvider.js, src/realmModels/Observation.js, src/sharedHooks/useUploadObservations.js
#534
I figured using an event emitter was probably the easiest path forward here.
https://user-images.githubusercontent.com/13311268/225186226-35db86ba-b097-41cf-b481-239ed00fb2ae.mov
=> Sync upload button w/ progress

src/providers/ObsEditProvider.js
Replace nullish coalescing assignment
=> Attempt to fix e2e ios test

src/components/SharedComponents/PhotoCount.js, tests/unit/components/SharedComponents/PhotoCount/PhotoCount.test.js
#539 
https://user-images.githubusercontent.com/13311268/226402073-00c41908-eed3-4ff6-a445-a12682a6870c.mov
=> Implement forced state update to rerender svg content

ios/Podfile.lock, package-lock.json, package.json, src/components/MyObservations/MyObservations.js, src/components/MyObservations/MyObservationsContainer.js, src/sharedHooks/useInfiniteScroll.js, src/sharedHooks/useLocalObservations.js, tests/integration/MyObservations.test.js, tests/jest.setup.js, tests/unit/components/MyObservations/MyObservations.test.js
#535 
It seems to be snappier switching between grid/list view.
Only real issue I've had was on querying for more observations. I believe that is now working but something to check when testing this pr.
=> Use flash list obs page

src/components/ObsEdit/DeleteObservationDialog.js, src/sharedHooks/useLocalObservations.js
#545 
I'm guessing what happened was that the response from the server was cached and thus was searching for an ID in realm that didn't exist.
I wasn't able to repro the issue after this, but please lmk if you can.
=> Fix observation deletion crash

src/components/Camera/DiscardChangesSheet.js, src/components/Camera/StandardCamera.js, src/components/MyObservations/LoginSheet.js, src/components/MyObservations/MyObservations.js, src/components/SharedComponents/BottomSheet.js, src/components/SharedComponents/Buttons/CloseButton.js, tests/unit/components/Camera/StandardCamera.test.js
=> Refactor DiscardChangesSheet and show only when leaving screen

Gemfile.lock, README.md, src/components/MyObservations/Header.js, src/components/MyObservations/ObsStatus.js, src/components/MyObservations/Toolbar.js, src/components/SharedComponents/Buttons/Button.js, src/components/SharedComponents/Buttons/INatIconButton.js, src/components/SharedComponents/UploadStatus/UploadStatus.js, src/components/SharedComponents/index.js, src/components/UiLibrary.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, src/sharedHooks/useUploadObservations.js, tailwind.config.js, tests/unit/components/SharedComponents/Buttons/INatIconButton.test.js, tests/unit/components/SharedComponents/Buttons/__snapshots__/Button.test.js.snap, tests/unit/components/SharedComponents/Buttons/__snapshots__/INatIconButton.test.js.snap, tests/unit/components/SharedComponents/UploadStatus/__snapshots__/UploadStatus.test.js.snap
* use `shrink` tailwind class instead of hard-coded max widths to control overflow in a few situations
* fixed some spacing issues with the Toolbar during upload
* center text in buttons by default
* export KebabMenu from SharedComponents (how was it working without this?)
* added some extra colors for debugging purposes
* added `INatIconButton` to have something like `IconButton` that allows us to set an accessible interactive area
=> Several minor UI fixes

src/components/App.js, src/components/Camera/StandardCamera.js, src/navigation/BottomTabNavigator/index.js, src/sharedHooks/useUnlockScreen.js, tests/jest.setup.js
=> 590 lock screen orientation

src/components/ObsEdit/EvidenceSection.js, src/providers/ObsEditProvider.js, src/realmModels/Observation.js, src/sharedHooks/useLocationFetching.js, tests/integration/ObsEditWithoutProvider.test.js
=> Only use date/location from exif when importing photo

src/components/MyObservations/LoginSheet.js, src/components/MyObservations/Toolbar.js
=> Tappable toolbar text & use shared component for LoginSheet

src/components/ObsEdit/Header.js, src/components/PhotoImporter/GroupPhotos.js, src/components/PhotoImporter/GroupPhotosContainer.js, src/components/PhotoImporter/PhotoGallery.js, src/navigation/BottomTabNavigator/index.js, src/providers/ObsEditProvider.js
=> Show correct group photos state

src/components/ObsEdit/BottomButtons.js
=> Loading/disabled state for ObsEdit buttons

src/components/ObsEdit/DatePicker.js, src/components/ObsEdit/IdentificationSection.js, src/components/ObsEdit/OtherDataSection.js, src/providers/ObsEditProvider.js
=> Set observation properties with a single function

src/components/SharedComponents/Sheets/TextInputSheet.js
=> Add autofocus prop to TextInputSheet

src/components/ObsEdit/OtherDataSection.js, src/components/ObsEdit/Sheets/GeoprivacySheet.js, src/components/ObsEdit/Sheets/WildStatusSheet.js, src/components/SharedComponents/Sheets/RadioButtonSheet.js
Closes #617 
...unless the goal is to also make the text description underneath the radio label tappable. for now, this makes the label and the button tappable.
=> Update radio buttons to make text pressable

src/components/MyObservations/Header.js, src/components/MyObservations/MyObservations.js, src/components/MyObservations/MyObservationsContainer.js, src/components/MyObservations/ToolbarContainer.js
=> Layout preference in async storage

src/components/Camera/StandardCamera.js, src/components/SharedComponents/Buttons/CloseButton.js, src/components/SharedComponents/Buttons/INatIconButton.js, tests/unit/components/SharedComponents/Buttons/__snapshots__/INatIconButton.test.js.snap
=> Tappable areas bigger in camera on phones

src/components/MyObservations/MyObservations.js, src/sharedHooks/useDeviceOrientation.js
=> Display correct columns and grid item sizes when rotating tablet

src/components/MyObservations/MyObservations.js, tests/integration/MyObservations.test.js, tests/unit/components/MyObservations/MyObservations.test.js
While continuing to allow it for tablets. Closes #661
=> Ensure MyObs grid doesn't change column count on phone rotation

src/components/SharedComponents/Sheets/TextInputSheet.js
=> Allow editing observation description

src/components/ObsEdit/EvidenceList.js, src/providers/ObsEditProvider.js
=> Add skeleton loading wheel to EvidenceList

package-lock.json, package.json
=> Update bottom sheet package

src/components/MyObservations/ObsUploadStatus.js, src/components/MyObservations/ToolbarContainer.js, src/providers/ObsEditProvider.js
=> Update toolbar text with single observation upload

src/components/MyObservations/Header.js
=> fix: MyObs log in button width issue on iPad

src/components/Camera/ARCamera/ARCamera.js, src/components/Camera/ARCamera/ARCameraButtons.js, src/components/Camera/ARCamera/FrameProcessorCamera.js, src/components/Camera/Buttons/CameraFlip.js, src/components/Camera/Buttons/Close.js, src/components/Camera/Buttons/Flash.js, src/components/Camera/Buttons/Zoom.js, src/components/Camera/CameraContainer.js, src/components/Camera/CameraView.js, src/components/Camera/StandardCamera/CameraOptionsButtons.js, src/components/Camera/StandardCamera/StandardCamera.js, src/components/Camera/TabletButtons.js, src/components/SharedComponents/Buttons/TransparentCircleButton.js
=> Add zoom button to camera

src/components/AddObsModal.js
=> Update styling for AddObsModel

src/components/Camera/ARCamera/ARCamera.js
=> Add error message alerts

src/components/ObsDetails/ActivityItem.js, src/components/ObsDetails/Sheets/AgreeWithIDSheet.js
=> Fix agree with ID bottom sheet visibility

src/components/SharedComponents/IconicTaxonChooser.js, src/components/SharedComponents/index.js, src/components/UiLibrary.js, tests/unit/components/SharedComponents/IconicTaxonChooser.test.js
=> IconicTaxonChooser component

src/components/AddID/AddID.js, src/components/AddID/AddIDContainer.js, src/components/AddID/TaxonSearch.js, src/components/ObsDetails/ObsDetailsContainer.js, src/components/ObsEdit/IdentificationSection.js, src/components/SharedComponents/SearchBar.js, src/components/SharedComponents/TaxonResult.js, src/navigation/BottomTabNavigator/index.js, tests/unit/components/AddID/AddID.test.js, tests/unit/components/SharedComponents/SearchBar.test.js
=> Update activity list with suggested IDs

src/components/AddObsModal.js, src/components/Camera/Buttons/CameraFlip.js, src/components/Camera/Buttons/Close.js, src/components/Camera/Buttons/Flash.js, src/components/Camera/Buttons/GreenCheckmark.js, src/components/Explore/Header.js, src/components/LocationPicker/LocationPicker.js, src/components/ObsDetails/DetailsTab/DQAVoteButtons.js, src/components/ObsEdit/IdentificationSection.js, src/components/SharedComponents/Buttons/CloseButton.js, src/components/SharedComponents/Buttons/INatIconButton.js, src/components/SharedComponents/Buttons/TransparentCircleButton.js, src/components/SharedComponents/IconicTaxonChooser.js, src/components/SharedComponents/KebabMenu.js, src/components/SharedComponents/TaxonResult.js, src/components/UiLibrary.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, src/navigation/CustomDrawerContent.js, tests/unit/components/AddID/AddID.test.js, tests/unit/components/SharedComponents/Buttons/INatIconButton.test.js, tests/unit/components/SharedComponents/Buttons/__snapshots__/INatIconButton.test.js.snap
Closes #745:
- Make INatIconButton throw when no accessibilityLabel and fix related errors
Next step here should be to replace usage of IconButton with INatIconButton and add accessibilityLabels accordingly
=> Require accessibilityLabel in INatIconButton

src/components/Camera/Buttons/TakePhoto.js
=> Increase camera shutter size

ios/iNaturalistReactNative.xcodeproj/project.pbxproj, src/components/PhotoImporter/GroupPhotoImage.js, src/components/PhotoImporter/GroupPhotos.js, src/components/PhotoImporter/GroupPhotosContainer.js, src/components/PhotoImporter/PhotoGallery.js, src/components/SharedComponents/Buttons/INatIconButton.js, src/components/UiLibrary.js, src/navigation/ContextHeader.js, src/navigation/StackNavigators/AddObsStackNavigator.js, src/navigation/navigationOptions.js, src/providers/INatPaperProvider.js, tailwind.config.js
Closes #480
This PR includes several smaller UI changes, including dynamic sizing and number of columns for the photo's list.
Made a separate [issue](https://github.com/inaturalist/iNaturalistReactNative/issues/781) for what happens when pressed on the plus button.
=> Group photos UI

.flowconfig, src/components/Camera/ARCamera/ARCamera.js, src/components/Camera/StandardCamera/StandardCamera.js, src/components/Camera/helpers/index.ts
=> 691 error handling

src/components/SharedComponents/SearchBar.js, src/navigation/StackNavigators/AddObsStackNavigator.js, src/navigation/StackNavigators/ObservationsStackNavigator.js
=> Fix double back button

src/components/MyObservations/MyObservations.js, src/components/ObsDetails/Header.js, src/components/ObsDetails/ObsDetails.js, src/components/SharedComponents/StickyView.js, src/components/SharedComponents/index.js
=> ObsDetail tab bar sticks to top of screen

src/components/Camera/ARCamera/ARCamera.js, src/components/Camera/ARCamera/ARCameraButtons.js, src/components/Camera/Buttons/Zoom.js, src/components/Camera/CameraContainer.js, src/components/Camera/StandardCamera/CameraOptionsButtons.js, src/components/Camera/StandardCamera/StandardCamera.js, src/components/Camera/TabletButtons.js, src/components/SharedComponents/Typography/INatText.js, tests/unit/components/SharedComponents/Buttons/__snapshots__/Button.test.js.snap, tests/unit/components/SharedComponents/Tabs/__snapshots__/Tabs.test.js.snap, tests/unit/components/SharedComponents/Typography/__snapshots__/Heading1.test.js.snap, tests/unit/components/SharedComponents/Typography/__snapshots__/Heading2.test.js.snap, tests/unit/components/SharedComponents/Typography/__snapshots__/Heading3.test.js.snap, tests/unit/components/SharedComponents/Typography/__snapshots__/Heading4.test.js.snap, tests/unit/components/SharedComponents/Typography/__snapshots__/Heading5.test.js.snap
=> 772 zoom button

fastlane/Fastfile
=> Update Fastlane file to check for extraneous assets

src/components/MediaViewer/MediaViewer.js, src/components/ObsEdit/Header.js, src/components/SharedComponents/Buttons/BackButton.js, src/navigation/StackNavigators/AddObsStackNavigator.js, src/navigation/StackNavigators/ObservationsStackNavigator.js, src/navigation/StackNavigators/SharedStackScreens.js, src/navigation/navigationOptions.js
- make group for screens in multiple navigators
- closes #808
=> Fix back button position

src/components/SharedComponents/IconicTaxonChooser.js, src/components/SharedComponents/IconicTaxonIcon.js, src/components/SharedComponents/ObservationsFlashList/ObsImage.js, src/components/SharedComponents/ObservationsFlashList/ObsImagePreview.js, src/components/SharedComponents/ObservationsFlashList/ObsListItem.js, src/components/SharedComponents/PhotoCount.js, src/components/SharedComponents/TaxonResult.js, src/components/UiLibrary.js, src/components/styledComponents.js, tests/factories/LocalObservation.js, tests/factories/LocalObservationPhoto.js, tests/factories/LocalPhoto.js, tests/jest.setup.js, tests/unit/components/MyObservations/MyObservations.test.js, tests/unit/components/SharedComponents/ObservationsFlashList/ObsGridItem.test.js, tests/unit/components/SharedComponents/ObservationsFlashList/__snapshots__/ObsGridItem.test.js.snap, tests/unit/components/SharedComponents/TaxonResult.test.js, tests/unit/components/SharedComponents/__snapshots__/TaxonResult.test.js.snap
* Fixed layout changes for ObsGriditem
* Added noevidence icon when no photos
* Added a few tests
* Minor cleanup
Closes #805
=> ObsGridItem layout fixes

src/components/ObsEdit/IdentificationSection.js, src/components/SharedComponents/Buttons/Button.js
=> Ignore dark mode on add identification button

src/components/LocationPicker/LocationPicker.js, src/components/SharedComponents/Map.js, tests/unit/components/LocationPicker/LocationPicker.test.js
=> Remove minZoomLevel for LocationPicker

src/components/ObsDetails/ObsDetailsContainer.js, src/components/ObsEdit/Header.js, src/components/ObsEdit/IdentificationSection.js, src/components/SharedComponents/SearchBar.js, src/components/SharedComponents/TaxonResult.js, src/components/Suggestions/SuggestionsContainer.js, src/components/Suggestions/SuggestionsList.js, src/components/Suggestions/TaxonSearch.js, src/providers/ObsEditProvider.js, tests/factories/RemoteTaxon.js, tests/integration/Suggestions.test.js, tests/jest.setup.js, tests/realm.setup.js
Nav was a small fix, testing it was not, so just want to make sure nothing broke.
=> Suggestions nav fix

src/components/MyObservations/MyObservations.js, src/components/SharedComponents/ObservationsFlashList/ObsItem.js, src/components/SharedComponents/ObservationsFlashList/ObservationsFlashList.js
=> Show login sheet when user logged out & tries to upload

src/components/Camera/CameraContainer.js, src/components/Camera/StandardCamera/PhotoCarousel.js, src/components/Camera/StandardCamera/PhotoPreview.js
=> Swap landscape/portrait photo preview position on tablet

src/components/Camera/ARCamera/ARCamera.js, src/components/Camera/CameraContainer.js, src/providers/ObsEditProvider.js, src/realmModels/Taxon.js, src/sharedHooks/index.js, src/sharedHooks/useTaxon.js, tests/unit/components/Camera/ARCamera.test.js, tests/unit/components/Camera/CameraContainer.test.js, tests/unit/sharedHooks/useTaxon.test.js
Creates a hook called useTaxon to check for an existing taxon in realm. If taxon doesn't exist, it's downloaded remotely and stored in realm. If taxon does exist, a taxon photo is shown in the AR camera. Closes #804
=> Show taxon photo in AR camera

src/components/Explore/ObservationsView.js, src/components/ObsDetails/DetailsTab/DetailsMap.js, src/components/ObsDetails/DetailsTab/DetailsMapContainer.js, src/components/ObsDetails/DetailsTab/DetailsTab.js, src/components/SharedComponents/Map.js, src/components/SharedComponents/index.js, tests/unit/components/ObsDetails/DetailsTab.test.js, tests/unit/components/SharedComponents/Map.test.js
=> Show taxon tiles on ObsDetails map & map modal

src/components/Camera/StandardCamera/PhotoCarousel.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, tests/unit/components/Camera/__snapshots__/PhotoCarousel.test.js.snap
=> Photos cant be deleted from camera preview

src/components/ObsDetails/Header.js, tests/unit/components/ObsDetails/ObsDetails.test.js
=> Fix displayed date on ObsDetails

src/components/ObsDetails/Header.js, src/components/ObsDetails/HeaderKebabMenu.js, src/components/ObsDetails/ObsDetails.js, src/components/ObsDetails/ObsDetailsContainer.js, src/components/ObsDetails/PhotoDisplay.js, src/components/ObsDetails/PhotoDisplayContainer.js, src/components/SharedComponents/KebabMenu.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, tests/unit/components/ObsDetails/HeaderKebabMenu.test.js
Closes #884 by adding a kebab menu, share item, and native share dialog to ObsDetails when a user is viewing another user's ObsDetails screen
=> Kebab menu with share option on other users' observations

package-lock.json, package.json, src/components/ObsEdit/BottomButtons.js, src/components/ObsEdit/EvidenceSection.js, src/components/ObsEdit/EvidenceSectionContainer.js, src/providers/ObsEditProvider.js, src/sharedHelpers/fetchUserLocation.e2e-mock, src/sharedHelpers/fetchUserLocation.js, src/sharedHooks/useCurrentObservationLocation.js, tests/integration/ObsEdit.test.js, tests/integration/ObsEditOffline.test.js, tests/integration/Suggestions.test.js, tests/jest.setup.js
Fixes #930. Also adds an ObsEditOffline test for adding a new obs offline... which doesn't actually catch this bug, but may catch others. This bug may have been due to a race condition that doesn't happen in the test env for some reason.
=> Fix broken offline coord fetch by only reverse geocoding in one place

src/components/ObsEdit/Sheets/DeleteObservationSheet.js
Correctly identify if observation was synced when deleting it. Closes #861
=> Fix bug preventing deletion of most recent observation

src/components/MyObservations/MyObservationsContainer.js, tests/integration/Explore.test.js, tests/integration/MyObservations.test.js, tests/jest.setup.js
=> Bugfix: handle blank LocalPreferences.last_sync_time on first sync

src/components/ObsEdit/BottomButtons.js, tests/unit/components/ObsEdit/BottomButtons.test.js
=> Logged out state for ObsEdit buttons

package-lock.json, package.json, src/components/SharedComponents/Checkbox.js, src/components/SharedComponents/index.js, src/components/UiLibrary.js, tests/unit/components/SharedComponents/Checkbox.test.js, tests/unit/components/SharedComponents/__snapshots__/Checkbox.test.js.snap
Using a new library, bouncy checkbox, because it is more customizable than either of the other solutions we're using in different parts of the app. This will be used in the ExploreFilters screen.
We should also replace other checkboxes throughout the app (Settings, FlagItemModel) with this shared component in a separate PR.
=> Checkbox shared component

ios/Podfile.lock, package-lock.json, package.json, src/components/ObsDetails/FlagItemModal.js, src/components/Settings/Relationship.js, src/components/Settings/SettingsAccount.js, src/components/Settings/SettingsContentDisplay.js, src/components/Settings/SettingsNotifications.js, src/components/SharedComponents/Checkbox.js, src/components/UiLibrary.js, tests/unit/components/ObsDetails/Flags.test.js, tests/unit/components/SharedComponents/Checkbox.test.js, tests/unit/components/SharedComponents/__snapshots__/Checkbox.test.js.snap
- Replace react native community checkbox with bouncy checkbox
- Fix tests; make sure checkbox is still working when checked/onPress props are passed in from external components
=> Update checkboxes & fix tests

src/components/TaxonDetails/About.js, src/components/TaxonDetails/TaxonDetails.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl
=> #874 / #870 - taxon UI changes

src/components/ObsDetails/CommunityTaxon.js, src/components/ObsDetails/ObsDetails.js, tests/unit/components/ObsDetails/CommunityTaxon.test.js
=> Fix styling, CommunityTaxon in ObsDetail

src/components/ObsDetails/DetailsTab/DetailsTab.js, src/components/ObsEdit/BottomButtons.js, src/realmModels/Observation.js, src/realmModels/ObservationSound.js
These changes are meant to fix issues #939 and #973.
=> Get observation photos and sounds from correct fields in Explore; fix for issue #939

src/api/taxa.js, src/components/ObsDetails/ObsDetailsContainer.js, src/components/ObsEdit/EvidenceSectionContainer.js, src/components/Suggestions/SuggestionsContainer.js, src/components/Suggestions/hooks/useOfflineSuggestions.js, src/components/Suggestions/hooks/useTaxonSelected.js, src/realmModels/Observation.js, tests/factories/ModelPrediction.js, tests/factories/RemoteIdentification.js, tests/factories/RemoteObservation.js, tests/helpers/render.js, tests/helpers/user.js, tests/integration/SuggestionsWithSyncedObs.test.js, tests/integration/navigation/MediaViewer.test.js, tests/integration/navigation/ObsEdit.test.js, tests/integration/navigation/Suggestions.test.js, tests/jest.setup.js
=> Restore tests removed in recent suggeston fixes

ios/Podfile.lock, src/components/SharedComponents/ObservationsFlashList/ObsStatus.js, tests/unit/components/SharedComponents/ObservationsFlashList/ObsStatus.test.js
=> Only show current ids in IdentificationCount

ios/Podfile.lock, src/components/Developer/Log.js
=> Support copy paste in developer log

flow-typed/npm/@realm/react_vx.x.x.js, src/api/taxa.js, src/components/ObsDetails/ActivityTab/ActivityItem.js, src/components/ObsDetails/ActivityTab/ActivityTab.js, src/components/ObsDetails/ObsDetails.js, src/components/ObsDetails/ObsDetailsContainer.js, src/components/TaxonDetails/TaxonDetails.js, src/realmModels/Taxon.js, tests/unit/components/ObsDetails/ActivityItem.test.js
=> Agree button: match web functionality 

flow-typed/npm/@realm/react_vx.x.x.js, src/components/MyObservations/MyObservationsContainer.js, src/components/ObsDetails/ObsDetailsContainer.js, src/components/ObsEdit/Sheets/DeleteObservationSheet.js, src/sharedHelpers/logging.js, src/sharedHooks/useLocalObservations.js, tests/factories/LocalObservation.js, tests/factories/RemoteObservation.js, tests/integration/ObsDetails.test.js
=> Crash when uploading after deleting unsynced observation

src/components/SharedComponents/SearchBar.js
=> Fix: cut-off descender text in SearchBar

src/components/Explore/ObservationsView.js, src/components/MyObservations/MyObservations.js, src/components/MyObservations/MyObservationsContainer.js, src/components/SharedComponents/ObservationsFlashList/ObservationsFlashList.js, tests/unit/components/Explore/ObservationsView.test.js
=> Render loading wheel until data is available for FlashList

src/components/SharedComponents/InlineUser/InlineUser.js, tests/unit/components/SharedComponents/InlineUser/InlineUser.test.js, tests/unit/components/SharedComponents/InlineUser/__snapshots__/InlineUser.test.js.snap
=> Show person icon as fallback when user is offline

src/components/ObsEdit/IdentificationSection.js, src/components/SharedComponents/Buttons/Button.js, tests/unit/components/SharedComponents/Buttons/__snapshots__/Button.dark.test.js.snap
=> Pause button dark mode until post-MVP

ios/Podfile.lock, ios/iNaturalistReactNative.xcodeproj/project.pbxproj, src/navigation/BottomTabNavigator/CustomTabBar.js, tests/unit/components/BottomTabNavigator/__snapshots__/CustomTabBar.test.js.snap
=> Use safe area insets to style tab bar padding

src/components/ObsDetails/ObsDetailsHeader.js
=> Fix DisplayTaxon styling for long, multiname taxon

src/components/PhotoImporter/GroupPhotoImage.js, src/components/SharedComponents/ObservationsFlashList/ObsImagePreview.js, src/components/SharedComponents/PhotoCount.js, tests/unit/components/PhotoImporter/GroupPhotosContainer.test.js
=> Render correct photo count when combining multiple photos

ios/Podfile.lock, ios/iNaturalistReactNative.xcodeproj/project.pbxproj, src/components/SharedComponents/DisplayTaxonName.js, src/components/SharedComponents/ObservationsFlashList/ObsGridItem.js, src/components/SharedComponents/Typography/INatText.js, tests/unit/components/SharedComponents/ObservationsFlashList/__snapshots__/ObsGridItem.test.js.snap, tests/unit/components/SharedComponents/__snapshots__/TaxonResult.test.js.snap
=> Limit display taxon name on ObsGridItem

package-lock.json, package.json, src/api/announcements.js, src/components/LoginSignUp/AuthenticationService.js, src/components/MyObservations/Announcements.js, src/components/MyObservations/MyObservations.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, tests/integration/MyObservations.test.js, tests/integration/SuggestionsWithSyncedObs.test.js, tests/integration/navigation/ObsEdit.test.js, tests/unit/components/MyObservations/Announcements.test.js
Closes #891 
This introduces a component to show announcements fetched from the server.
The component is partly copied over from Seek with some refactors to use the iNatRN react-query setup for the api calls to fetch and dismiss announcements.
=> Announcements

src/components/ObsDetails/FaveButton.js, src/components/ObsDetails/HeaderKebabMenu.js, src/components/ObsDetails/ObsDetails.js, src/components/ObsDetails/ObsDetailsHeader.js, src/components/ObsDetails/ObsMediaCarousel.js, src/components/ObsDetails/ObsMediaDisplay.js, src/components/ObsDetails/ObsMediaDisplayContainer.js
Partly addresses #766.
Introduces all the high level layout changes for tablets without the masonry layout of photos/sounds.
=> ObsDetail tablet layout

src/components/Suggestions/SuggestionsContainer.js, src/components/Suggestions/hooks/useOnlineSuggestions.js
Closes #1039
- cancels query for online suggestions after 2 seconds, to account for spotty network conditions
=> Timeout for online suggestions

src/components/Camera/StandardCamera/PhotoCarousel.js, src/components/Explore/ExploreFlashList.js, src/components/LocationPicker/LoadingIndicator.js, src/components/Messages/MessageList.js, src/components/MyObservations/InfiniteScrollLoadingWheel.js, src/components/Notifications/NotificationsList.js, src/components/ObsDetails/ActivityTab/ActivityHeader.js, src/components/ObsDetails/DetailsTab/DQAVoteButtons.js, src/components/ObsDetails/ObsDetails.js, src/components/ObsEdit/EvidenceList.js, src/components/ObsEdit/EvidenceSection.js, src/components/PhotoImporter/PhotoGallery.js, src/components/Projects/Projects.js, src/components/Search/Search.js, src/components/Settings/Settings.js, src/components/SharedComponents/ActivityIndicator.js, src/components/SharedComponents/Buttons/Button.js, src/components/SharedComponents/ObservationsFlashList/ObservationsFlashList.js, src/components/SharedComponents/OverviewCounts.js, src/components/SharedComponents/index.js, src/components/styledComponents.js
Closes #1035 by using custom iNaturalist activity indicator across the app
=> Standardize activity indicator

src/components/Explore/Explore.js, src/components/SharedComponents/Sheets/BottomSheet.js, src/components/SharedComponents/Sheets/RadioButtonSheet.js, src/components/SharedComponents/Sheets/TextInputSheet.js, src/components/SharedComponents/Sheets/TextSheet.js, src/components/SharedComponents/Sheets/WarningSheet.js
=> Handle close & backdrop dismissal, Explore bottom sheet

src/components/SharedComponents/ObservationsFlashList/ObsStatus.js, src/components/SharedComponents/UploadStatus/UploadStatus.js, tests/unit/components/SharedComponents/ObservationsFlashList/__snapshots__/ObsGridItem.test.js.snap, tests/unit/components/SharedComponents/UploadStatus/__snapshots__/UploadStatus.test.js.snap
=> Show ObsStatus in correct position after animating, ObsGridItem

src/components/ObsEdit/IdentificationSection.js, src/components/ObsEdit/MultipleObservationsArrows.js, src/components/ObsEdit/ObsEdit.js, src/components/SharedComponents/IconicTaxonChooser.js, src/components/SharedComponents/ObservationsFlashList/ObsStatus.js, src/components/Suggestions/SuggestionsContainer.js, tests/unit/components/ObsEdit/IdentificationSection.test.js
=> Reset IconicTaxonChooser when navigating multiple observations

src/components/ObsDetails/ObsDetailsContainer.js, tests/unit/components/ObsDetails/ObsDetails.test.js
closes #1036
- agree button agrees with taxon tapped, not the community taxon
- added a test for this
=> Fix agree button taxon id

src/components/Camera/CameraView.js, src/components/Camera/FocusSquare.js, tailwind.config.js
=> Show Focus square on cameras that do not focus; plus style changes

src/components/LocationPicker/LocationPickerContainer.js
=> Use private Latitude and private Longitude to initialize location picker if observation is obscured

src/components/LoginSignUp/AuthenticationService.js, src/components/MyObservations/MyObservationsContainer.js, src/components/MyObservations/hooks/useDeleteObservations.js, src/components/ObsDetails/FaveButton.js, src/components/ObsDetails/ObsDetailsContainer.js, src/components/ObsDetails/ObsDetailsHeader.js, src/components/ObsDetails/ObsDetailsOverview.js, src/components/ObsDetails/ObsMedia.js, src/components/ObsDetails/ObsMediaDisplay.js, src/components/ObsDetails/ObsMediaDisplayContainer.js, src/components/ObsDetails/helpers/checkCamelAndSnakeCase.js, src/components/SharedComponents/ObsStatus.js, src/components/SharedComponents/ObservationLocation.js, src/components/SharedComponents/ObservationsFlashList/ObsGridItem.js, src/components/SharedComponents/ObservationsFlashList/ObsListItem.js, src/components/SharedComponents/ObservationsFlashList/ObsStatus.js, src/components/SharedComponents/ObservationsFlashList/ObsUploadStatus.js, src/components/SharedComponents/index.js, src/components/UiLibrary.js, src/realmModels/Observation.js, src/realmModels/Taxon.js, tests/helpers/user.js, tests/unit/components/SharedComponents/ObservationsFlashList/ObsStatus.test.js
=> Load ObsDetails skeleton before observation data is ready

ios/iNaturalistReactNative.xcodeproj/project.pbxproj, src/components/Explore/Explore.js, src/components/Explore/ObserversView.js, src/components/Explore/TaxonGridItem.js, src/components/SharedComponents/UserListItem.js, src/components/SharedComponents/index.js, tests/unit/components/Explore/TaxonGridItem.test.js, tests/unit/components/SharedComponents/UserListItem.test.js
Closes #1054 
- Adds UserProfile navigation to UserListItem
- Adds TaxonDetails navigation to TaxonGridItem
=> Add navigation links to explore views

src/components/ObsDetails/ActivityTab/ActivityHeader.js, src/components/ObsDetails/ActivityTab/ActivityHeaderContainer.js, src/components/ObsDetails/ActivityTab/ActivityHeaderKebabMenu.js, src/components/ObsDetails/Sheets/WithdrawIDSheet.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, tests/factories/RemoteIdentification.js, tests/integration/ObsDetails/ActivityTab/ActivityHeaderContainer.test.js
Additionally,
* Adds tests for ID withdraw and restore
* Renames withdrawOrRestoreIdentification function for clarity
* Adds some accessibility labels for testing and accessibility
Closes #1129
=> Bugfix: withdrawing ID was deleting the ID body

src/components/Explore/Explore.js, src/components/Explore/ExploreContainer.js, src/components/Explore/Header/Header.js, src/components/Explore/MapView.js, src/components/Explore/MapViewContainer.js, src/components/Explore/ObservationsView.js, src/components/SharedComponents/Map.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, src/providers/ExploreContext.tsx, tests/unit/components/Explore/MapView.test.js
=> Redo search in map, Explore

src/components/Explore/Modals/FilterModal.js, src/components/ObsDetails/DetailsTab/DetailsTab.js, src/components/SharedComponents/Checkbox.js, src/components/SharedComponents/DateTimePicker.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, src/providers/ExploreContext.tsx, tests/unit/components/SharedComponents/Checkbox.test.js, tests/unit/components/SharedComponents/__snapshots__/Checkbox.test.js.snap
Adds a date range option to the "Date Uploaded" explore filter.
Fixes a bug with Checkmarks.
Fixes a bug with DateTimePicker.
Closes #1137
Closes #1148
Closes #1153
=> Explore filters, one more date range, two bugfixes

src/components/Suggestions/ObsPhotoSelectionList.js, src/components/Suggestions/Suggestions.js, src/components/Suggestions/SuggestionsContainer.js, src/realmModels/ObservationPhoto.js, tests/integration/navigation/MediaViewer.test.js
=> Navigate to Media viewer from suggestions

src/components/Explore/Explore.js, src/components/Explore/ObservationsViewBar.js
=> Observations view bar and explore icon button style changes

src/api/observations.js, src/components/MyObservations/MyObservationsContainer.js, src/components/MyObservations/ToolbarContainer.js, src/components/PhotoImporter/PhotoGallery.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, tests/performance/MyObservations.perf-test.js, tests/unit/components/MyObservations/MyObservations.test.js, tests/unit/components/MyObservations/ToolbarContainer.test.js
This shows a UI state while observations are syncing but not uploading. Closes #1055
Also partially addresses #1040
Also uses an animation instead of activity indicator on import from gallery screen.
=> Changes to Sync button

.eslintrc.js, .flowconfig, ios/Podfile.lock, package-lock.json, package.json, src/components/SharedComponents/index.js, src/components/Support/Support.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, src/navigation/BottomTabNavigator/index.js, src/navigation/CustomDrawerContent.js
Have taken the specs from the design files directly.
=> Add Support screen

src/components/Explore/Modals/FilterModal.js
As specified in a comment in the design files.
=> Show reviewed-by section only when logged in

src/components/SharedComponents/IconicTaxonIcon.js, src/components/SharedComponents/ObservationsFlashList/ObsGridItem.js, src/components/SharedComponents/ObservationsFlashList/ObsImage.js, src/components/SharedComponents/ObservationsFlashList/ObsImagePreview.js, src/components/SharedComponents/ObservationsFlashList/ObsListItem.js, src/components/SharedComponents/ObservationsFlashList/ObsUploadStatus.js, src/components/SharedComponents/PhotoCount.js, src/components/SharedComponents/TaxonResult.js, src/components/SharedComponents/UploadStatus/UploadStatus.js, src/components/UiLibrary.js, tailwind.config.js, tests/unit/components/SharedComponents/ObservationsFlashList/__snapshots__/ObsGridItem.test.js.snap, tests/unit/components/SharedComponents/UploadStatus/__snapshots__/UploadStatus.test.js.snap, tests/unit/components/SharedComponents/__snapshots__/TaxonResult.test.js.snap
Some style fixes for grid view after discussion w/ Abhas, and some updates to upload status layout.
=> Obs grid view updates

ios/Podfile.lock, package-lock.json
Just an update of the vision-plugin.
Exposes the `cropRatio` param but that works only on Android at the moment. So we could use it to take a smaller center crop than the full width/height.
=> Update vision plugin

src/components/ObsDetails/ObsDetails.js, src/components/ObsDetails/ObsDetailsContainer.js, src/components/ObsDetails/ObsDetailsOverview.js
=> Update community taxon when new id suggested

.detoxrc.js, .github/workflows/e2e_android.yml, .github/workflows/e2e_ios.yml, package-lock.json, package.json
=> Detox update

src/components/Explore/Header/HeaderCount.js, src/components/Explore/hooks/useInfiniteExploreScroll.js
=> Explore header count update fixes

src/components/Explore/ExploreContainer.js
Had a tiny change here but the issue is punted to the next iteration.
=> Remove a superfluous delete call

src/components/PhotoSharing.js, src/navigation/StackNavigators/SharedStackScreens.js, src/sharedHooks/useShare.js
=> Add alerts and loading screen to photo sharing functionality

src/components/Explore/TaxonGridItem.js, src/components/TaxonDetails/TaxonDetailsTitle.js
=> Only show species checkmark for species or lower

src/components/ObsEdit/Header.js, src/components/ObsEdit/Sheets/DeleteObservationSheet.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, tests/unit/components/ObsEdit/DeleteObservationSheet.test.js
=> Allow single observation deletion when editing multiple

src/components/MyObservations/MyObservationsContainer.js, src/components/MyObservations/hooks/useDeleteObservations.js
=> Reset toolbar success state after five seconds

package-lock.json, package.json, src/components/PhotoImporter/GroupPhotosContainer.js, src/components/PhotoSharing.js, src/stores/useStore.js
=> Use text in iOS share dialog to add observation description

src/components/ObsDetails/ActivityTab/ActivityHeaderContainer.js, src/components/ObsDetails/DQAContainer.js, src/components/ObsDetails/DataQualityAssessment.js, src/components/ObsDetails/DetailsTab/DQAVoteButtons.js, src/components/ObsDetails/DetailsTab/DetailsTab.js, src/components/ObsDetails/FaveButton.js, src/components/ObsDetails/ObsDetails.js, src/components/ObsDetails/ObsDetailsContainer.js, src/realmModels/Observation.js, src/realmModels/index.js, src/sharedHooks/index.js, src/sharedHooks/useIsConnected.ts, src/sharedHooks/useRemoteObservation.js, src/sharedHooks/useRemoteObservation.ts, tests/factories/LocalObservation.js, tests/factories/RemoteVote.js, tests/integration/DataQualityAssesment/DataQualityAssessment.test.js, tests/unit/components/BottomTabNavigator/CustomTabBar.test.js, tests/unit/components/ObsDetails/DQAVoteButtons.test.js, tests/unit/components/ObsDetails/DataQualityAssessment.test.js, tests/unit/components/ObsDetails/FaveButton.test.js, tests/unit/components/ObsDetails/ObsDetails.test.js
=> Community Taxon improvement DQA

src/navigation/BottomTabNavigator/CustomTabBarContainer.js
=> Fix Notifications navigation

src/components/Explore/Explore.js, src/components/Explore/ExploreContainer.js, src/components/Explore/Header/Header.js, src/components/Explore/RootExploreContainer.js, src/components/Explore/helpers/mapParamsToAPI.js, src/components/Explore/hooks/useMapLocation.js, src/components/MyObservations/MyObservationsEmpty.js, src/components/MyObservations/Toolbar.js, src/components/ObsEdit/EvidenceSection.js, src/components/SharedComponents/Buttons/BackButton.js, src/components/SharedComponents/ObservationsFlashList/ObsItem.js, src/components/SharedComponents/OverviewCounts.js, src/components/SharedComponents/SpeciesSeenCheckmark.js, src/components/TaxonDetails/TaxonDetails.js, src/components/UserProfile/UserProfile.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, src/navigation/BottomTabNavigator/CustomTabBarContainer.js, src/navigation/StackNavigators/ObservationsStackNavigator.js, src/providers/ExploreContext.tsx, tests/integration/navigation/Explore.test.js, tests/unit/components/BottomTabNavigator/__snapshots__/CustomTabBar.test.js.snap
=> Explore filters and navigation entry points

.github/workflows/e2e_android.yml
=> Disable Android e2e tests

src/components/Explore/Modals/FilterModal.js
=> Refactor overall padding to not apply for IconicTaxonChooser

src/components/FullPageWebView/FullPageWebView.js
=> Use Mortal to reload fresh webview page

ios/Podfile.lock, src/components/Camera/ARCamera/ARCamera.js, src/components/Camera/ARCamera/ARCameraButtons.js, src/components/Camera/Buttons/TakePhoto.js, src/components/Camera/StandardCamera/CameraNavButtons.js, src/components/Camera/StandardCamera/CameraOptionsButtons.js, src/components/Camera/StandardCamera/StandardCamera.js, src/components/Camera/TabletButtons.js, tests/integration/navigation/ARCamera.test.js
=> Disable TakePhoto button while model loads

nativewind-env.d.ts, src/components/Suggestions/Suggestions.js, src/components/Suggestions/SuggestionsContainer.js, src/components/Suggestions/SuggestionsEmpty.tsx, src/components/Suggestions/hooks/useOfflineSuggestions.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, tailwind.config.js, tests/unit/components/Suggestions/Suggestions.test.js
=> Allow user to navigate to ObsEdit when no suggestions found

ios/iNaturalistReactNative/Info.plist, src/components/Help/Help.js
=> Allow iOS users to open Gmail

src/components/Explore/SearchScreens/ExploreLocationSearch.js, src/components/Explore/hooks/useParams.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl
=> Explore location search buttons

src/components/Suggestions/hooks/useOnlineSuggestions.js, src/sharedHooks/useIsConnected.ts
=> Check for Internet connectivity in useOnlineSuggestions

src/components/Explore/SpeciesView.js, src/components/Explore/TaxonGridItem.tsx, tests/unit/components/Explore/TaxonGridItem.test.js
=> Add observation count to TaxonGridItem

src/components/MyObservations/Header.js, src/components/MyObservations/MyObservations.js, src/components/MyObservations/MyObservationsEmpty.js, src/components/SharedComponents/Buttons/AddObsButton.js, src/components/SharedComponents/Buttons/GradientButton.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, tests/integration/navigation/ARCamera.test.js, tests/integration/navigation/Explore.test.js, tests/integration/navigation/SoundRecorder.test.js, tests/integration/navigation/StandardCamera.test.js
=> 1363 casual home screen

src/components/ObsDetails/ObsDetailsContainer.js, src/stores/createLayoutSlice.js, src/stores/useStore.js, tests/unit/components/ObsDetails/ObsDetails.test.js
=> 1044 persist obs tab

ios/Podfile.lock, package-lock.json, src/components/Explore/Explore.js, src/components/Explore/Header/Header.js, src/components/Explore/MapView.js, src/components/Explore/Modals/FilterModal.tsx, src/components/Explore/RootExploreContainer.js, src/components/Explore/hooks/useMapLocation.js, src/components/Explore/hooks/useParams.js, src/providers/ExploreContext.tsx, tests/unit/components/Explore/Modals/FilterModal.test.js
=> Reset taxon/place when resetting explore filters

src/components/MyObservations/MyObservationsContainer.js, src/components/Settings/Settings.js
=> Offline warning for upload

src/components/ObsDetails/SoundContainer.js, src/components/SharedComponents/Map.js
=> 1070 sound progress

src/components/About.js
=> Relative width for wordmark on About

src/components/SharedComponents/Map.js
* Changed grid tile opacity
* Made grid tiles orange, points are still green
* Use hybrid instead of satellite base map
Closes #1196
=> Minor map style updates

src/components/MediaViewer/MainMediaDisplay.js, src/components/MediaViewer/MediaSelector.js, src/components/MediaViewer/MediaViewer.js, src/components/MediaViewer/MediaViewerModal.js, src/components/ObsDetails/ObsMedia.js, src/components/ObsDetails/ObsMediaDisplayContainer.js, src/components/ObsEdit/EvidenceList.js, src/components/ObsEdit/EvidenceSection.js, src/components/ObsEdit/EvidenceSectionContainer.js, src/components/SoundRecorder/SoundRecorder.js, src/realmModels/Observation.js, src/realmModels/ObservationSound.js, src/realmModels/Sound.js, src/realmModels/index.js, src/sharedHelpers/uploadObservation.js, src/stores/createObservationFlowSlice.js, tests/factories/LocalObservationSound.js, tests/factories/LocalSound.js, tests/unit/components/ObsEdit/EvidenceList.test.js, tests/unit/helpers/uploadObservation.test.js, tests/unit/models/Observation.test.js
Adds the Sound model so the app's schema matches the web schema and locally ObservationPhotos / Photos matches ObservationSounds / Sounds. There should not be any user-facing change, but hopefully it should make things easier to maintain.
=> Sound model

src/components/Camera/AICamera/AICamera.js
=> Move taxon result to safe area, AI camera

src/components/Developer/UiLibrary/Misc.js, src/components/Explore/Modals/FilterModal.tsx, src/components/ProjectDetails/ProjectDetails.js, src/components/Projects/helpers/displayProjectType.ts, src/components/SharedComponents/ProjectListItem.tsx
=> 1434 explore filter project UI

package-lock.json, package.json, src/components/Camera/CameraView.tsx, src/components/Camera/FocusSquare.tsx, src/components/Camera/hooks/useFocusTap.ts
I added some of the recent updates to the Camera views into Seek and adapted some of the TypeScript code from those changes.
I am presenting the updates here as well.
Let me know what you think of it @albullington.
=> Focus types

src/components/MediaViewer/MainMediaDisplay.js, src/components/MediaViewer/MediaSelector.js, src/components/ObsDetails/MasonryLayout.js, src/components/SharedComponents/Map/Map.js, src/components/SharedComponents/ObservationsFlashList/ObsGridItem.js, src/realmModels/Photo.js, tests/unit/components/SharedComponents/ObservationsFlashList/__snapshots__/ObsGridItem.test.js.snap
=> Display saved photos after app updates

src/components/Explore/Explore.js, src/components/Explore/ExploreContainer.js, src/components/Explore/ObserversView.js, src/components/Explore/RootExploreContainer.js, src/components/Explore/hooks/useParams.js, src/stores/createExploreSlice.js, tests/integration/navigation/Explore.test.js
closes #1454 
also closes #1467
=> Keep previous explore view when changing filters

src/components/Explore/MapView.js, src/components/Explore/hooks/useMapLocation.js, src/stores/createExploreSlice.js, src/stores/createExploreSlice.ts
=>  Preserve previous explore map state

src/components/Camera/hooks/usePrepareStoreAndNavigate.js, src/stores/createObservationFlowSlice.js
=> Save all camera photos in a single iNat Next album

src/components/Camera/AICamera/AIDebugButton.js, src/components/Camera/Buttons/Flash.js, src/components/Camera/Buttons/Zoom.js, src/components/SharedComponents/Buttons/TransparentCircleButton.tsx
=> Use consistent styling for zoom button

src/components/SoundRecorder/SoundRecorder.js, src/navigation/StackNavigators/NoBottomTabStackNavigator.js
=> Fix back nav on sound recorder

src/components/LoginSignUp/ForgotPassword.js, src/components/LoginSignUp/ForgotPasswordForm.js, src/components/LoginSignUp/LoginForm.js, src/components/LoginSignUp/LoginSignUpInputField.js, src/components/LoginSignUp/SignUp.js, src/components/LoginSignUp/SignUpForm.js
=> #1362 - login/signup screens - hide keyboard

src/components/Suggestions/Suggestions.js, src/components/Suggestions/SuggestionsEmpty.tsx
=> Removes notice about not having suggestions when there is a top suggestion

src/components/SharedComponents/KebabMenu.js, src/components/TaxonDetails/TaxonDetails.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl
=> 1441 dropdown text style change

src/components/Explore/Header/Header.js
=> Replace Explore header taxon display

src/realmModels/ObservationPhoto.js
=> Fix: App update makes saved observations fail to upload

src/components/MyObservations/MyObservationsContainer.js, src/components/MyObservations/hooks/useClearSyncedPhotosForUpload.ts, tests/integration/MyObservations.test.js, tests/integration/Notifications.test.tsx, tests/integration/ObsDetails.test.js, tests/integration/ObsDetails/ActivityTab/ActivityHeaderContainer.test.js, tests/integration/ObsEditOffline.test.js, tests/integration/SuggestionsWithSyncedObs.test.js, tests/integration/navigation/AICamera.test.js, tests/integration/navigation/Explore.test.js, tests/integration/navigation/MediaViewer.test.js, tests/integration/navigation/ObsEdit.test.js, tests/integration/navigation/SoundRecorder.test.js, tests/integration/navigation/StandardCamera.test.js, tests/integration/navigation/Suggestions.test.js
more size updates, re: https://github.com/inaturalist/iNaturalistReactNative/issues/1484
=> Clear synced photoUploads paths

src/components/ObsDetails/ObsDetails.js, src/components/ObsDetails/ObsDetailsHeader.tsx, tests/unit/components/ObsDetails/ObsDetailsHeader.test.js
Closes #1509
Closes #1508
Closes #1486
=> Open local observation in ObsEdit from ObsDetails

src/components/Explore/helpers/mapParamsToAPI.js, src/components/Explore/hooks/useMapLocation.js, src/components/Explore/hooks/useParams.js, src/providers/ExploreContext.tsx
=> Fix crash from changing explore params

src/components/ObsEdit/Header.js, src/components/SharedComponents/ObservationsFlashList/MyObservationsPressable.js
=> Nav back to ObsList from unsynced ObsEdit

src/components/LocationPicker/LocationPicker.js
=> Prevent map from resetting place name on initial render

src/components/Explore/SearchScreens/ExploreUserSearch.js
=> Handle taps while keyboard open

src/components/SharedComponents/TaxonResult.js, tests/unit/components/SharedComponents/__snapshots__/TaxonResult.test.js.snap
=> Grow pressable area in TaxonResult

src/components/Explore/SearchScreens/ExploreTaxonSearch.js, src/components/SharedComponents/SearchBar.js
=> Autofocus search bar by default

src/components/Explore/TaxonGridItem.tsx, tests/unit/components/Explore/TaxonGridItem.test.js
=> Show correct view in Explore when tapping species count

src/components/Camera/AICamera/AICamera.js, src/components/Camera/AICamera/hooks/usePredictions.ts, src/components/Camera/CameraContainer.tsx, src/components/Camera/CameraWithDevice.tsx, tests/integration/navigation/AICamera.test.js, tests/unit/components/Camera/AICamera.test.js
=> 1569 ai camera zoom

src/components/MyObservations/MyObservations.js, src/components/MyObservations/hooks/useDeleteObservations.ts, src/components/MyObservations/hooks/useUploadObservations.ts, src/realmModels/Observation.js, src/sharedHelpers/uploadObservation.js, src/sharedHooks/useLocalObservations.js, src/stores/createUploadObservationsSlice.ts
=> Handle modified but remotely deleted obs in upload process

src/components/MyObservations/hooks/useUploadObservations.ts, src/realmModels/Observation.js
=> Upload least recently created observations first

src/components/ObsDetails/DetailsTab/DetailsTab.js, src/components/ObsDetails/ObsDetails.js, tests/unit/components/ObsDetails/DetailsTab.test.js
=> Hide DQA voting if no current user

src/components/ObsEdit/IdentificationSection.js, src/components/SharedComponents/TaxonResult.js
=> Show default icon on ObsEdit ID section while offline

src/components/Suggestions/SuggestionsEmpty.tsx
=> Hide empty text & button when top suggestion exists

index.js, ios/Podfile.lock, ios/iNaturalistReactNative.xcodeproj/project.pbxproj, src/api/log.ts, src/components/LoginSignUp/AuthenticationService.js, src/sharedHelpers/userData.ts, src/stores/useStore.js, tests/helpers/render.js, tsconfig.json
Would like some feedback on the approach in src/api/log.ts. Is this how we're supposed to handle sometimes-present attributes on objects?
=> Typescrpt path aliases; tried to resolve ts errors in one file

src/components/Explore/Modals/FilterModal.tsx, src/components/Explore/RootExploreContainer.js, src/components/Explore/SearchScreens/ExploreLocationSearch.js, src/components/Explore/hooks/useMapLocation.js, src/components/Explore/hooks/useParams.js, src/providers/ExploreContext.tsx, tests/unit/providers/ExploreContext.test.js
* Set location filter to Nearby on Explore after granting location permission
* Removes lat/lng filter when redoing search in map area
Closes #1226
=> Explore nearby and map area

ios/Podfile.lock, src/components/Camera/hooks/usePrepareStoreAndNavigate.js
=> Save photos to gallery in sequence to avoid duplicate albums

ios/Podfile.lock, src/components/Developer/UiLibrary.js, src/components/Developer/UiLibrary/ToolbarDemo.tsx, src/components/Developer/UiLibraryItem.js, src/components/MyObservations/Toolbar.js, src/components/SharedComponents/Buttons/INatIconButton.js, tests/unit/components/BottomTabNavigator/__snapshots__/CustomTabBar.test.js.snap, tests/unit/components/SharedComponents/Buttons/__snapshots__/INatIconButton.test.js.snap, tests/unit/components/SharedComponents/__snapshots__/TaxonResult.test.js.snap
=> Tappable toolbar status

src/components/Camera/CameraWithDevice.tsx, src/components/SharedComponents/Mortal.js, src/navigation/StackNavigators/NoBottomTabStackNavigator.js, src/providers/ExploreContext.tsx, src/sharedHelpers/fetchUserLocation.ts, src/sharedHelpers/uploadObservation.js, src/sharedHooks/useCurrentObservationLocation.js, src/sharedHooks/useUserLocation.ts
Definitely fixes a problem where sharing a photo without coordinates resulted in a GPS fetch on ObsEdit. Might improve the situation with stale coordinates (#1688)... but I doubt it. Adds more logging at least.
=> Location fixes

src/components/ObsEdit/EvidenceSection.js, src/components/SharedComponents/ActivityCount/ActivityCount.js, src/components/SharedComponents/InlineUser/InlineUser.js, src/components/SharedComponents/Tabs/Tabs.tsx, src/components/SharedComponents/Typography/Body1.tsx, src/components/SharedComponents/Typography/Body3.tsx, src/components/SharedComponents/Typography/Body4.tsx, src/components/SharedComponents/Typography/Heading1.tsx, src/components/SharedComponents/Typography/Heading2.tsx, src/components/SharedComponents/Typography/Heading3.tsx, src/components/SharedComponents/Typography/Heading4.tsx, src/components/SharedComponents/Typography/Heading5.tsx, src/components/SharedComponents/Typography/P.tsx, src/components/SharedComponents/Typography/UnderlinedLink.tsx
=> 1636 icon alignment

src/components/LoginSignUp/Error.tsx, src/components/LoginSignUp/LicensePhotosForm.js, src/components/LoginSignUp/LoginForm.js, src/components/LoginSignUp/SignUpConfirmation.js, src/components/LoginSignUp/SignUpForm.js, src/components/SharedComponents/Checkbox.tsx, src/components/SharedComponents/Typography/Body2.tsx, src/components/SharedComponents/Typography/List2.tsx, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/l10n/en.ftl.json.orig, src/i18n/l10n/en.ftl.orig, src/i18n/strings.ftl, tests/unit/components/SharedComponents/__snapshots__/Checkbox.test.js.snap
Closes #1626
Some UI changes. Authenticates user now immediately after registration.
=> Changes to email confirmation screen.

src/components/Explore/Explore.js, src/components/SharedComponents/OfflineNotice.tsx, tests/unit/components/SharedComponents/OfflineNotice.test.js
=> 1520 explore offline notice

src/components/ObsEdit/Header.js, src/components/PhotoImporter/GroupPhotos.js, src/components/PhotoImporter/GroupPhotosContainer.js, src/components/Suggestions/SuggestionsEmpty.tsx, src/components/Suggestions/hooks/useNavigateWithTaxonSelected.js
=> Nav user back to Suggestions from ObsEdit

src/components/ObsDetails/ObsDetailsContainer.js, src/components/ObsEdit/IdentificationSection.js, src/components/PhotoImporter/GroupPhotosContainer.js
=> Push suggestions screen when navigating

src/components/MyObservations/hooks/useSyncObservations.ts
Addresses the first couple issues in the comments of #1631:
- Checks whether the user is online (as well as logged in) when starting automatic and manual sync process, so this process won't stall indefinitely if a user has no connectivity
- Allows a user to delete a Realm observation that has not been synced to web, regardless of whether user is online
=> Allow user to delete unsynced observations when offline

src/components/Donate/Donate.tsx, src/navigation/StackNavigators/TabStackNavigator.js
=> Change Donate link, TS

src/components/Notifications/NotificationsList.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl
=> 1502 logged out notifications

src/components/Camera/hooks/usePrepareStoreAndNavigate.js, src/components/Suggestions/Suggestion.js, src/components/Suggestions/Suggestions.js, src/components/Suggestions/SuggestionsContainer.tsx, src/components/Suggestions/SuggestionsFooter.tsx, src/components/Suggestions/SuggestionsHeader.tsx, src/components/Suggestions/hooks/useNavigateWithTaxonSelected.js, src/components/Suggestions/hooks/useOfflineSuggestions.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, src/navigation/StackNavigators/SharedStackScreens.js, src/realmModels/ObservationPhoto.js, tests/integration/SuggestionsWithSyncedObs.test.js, tests/integration/SuggestionsWithUnsyncedObs.test.js, tests/integration/navigation/AICamera.test.js, tests/unit/components/Suggestions/Suggestions.test.js
=> Web parity for displaying top suggestion

ios/iNaturalistReactNative.xcodeproj/xcshareddata/xcschemes/iNaturalistReactNative.xcscheme, src/components/Suggestions/Suggestions.js, src/components/Suggestions/SuggestionsContainer.tsx, src/components/Suggestions/SuggestionsEmpty.tsx, src/components/Suggestions/SuggestionsFooter.tsx, src/components/Suggestions/SuggestionsHeader.tsx, src/components/Suggestions/helpers/sortSuggestions.ts, src/components/Suggestions/hooks/useOnlineSuggestions.ts
=> Fixes for suggestions screen

src/components/SharedComponents/IconicTaxonIcon.js, src/components/SharedComponents/ObservationsFlashList/ObsImage.js, src/components/SharedComponents/ObservationsFlashList/ObsImagePreview.js, src/components/SharedComponents/TaxonResult.js, tests/unit/components/SharedComponents/ObservationsFlashList/__snapshots__/ObsGridItem.test.js.snap, tests/unit/components/SharedComponents/__snapshots__/TaxonResult.test.js.snap
=> Default to iconic taxon image in TaxonResult

src/components/Camera/AICamera/AICamera.js, src/components/Camera/CameraView.tsx, src/components/Camera/CameraWithDevice.tsx, src/components/Camera/StandardCamera/StandardCamera.js, src/components/Camera/hooks/useRotation.js, src/components/Camera/hooks/useRotation.ts, src/components/Camera/hooks/useTakePhoto.ts, src/components/Explore/MapView.tsx, src/components/Explore/hooks/useCurrentMapRegion.ts, src/components/Explore/hooks/useMapLocation.ts, src/components/LocationPicker/LocationPicker.js, src/components/LocationPicker/LocationPickerContainer.js, src/components/MediaViewer/CustomImageZoom.js, src/components/MediaViewer/MainMediaDisplay.js, src/components/MediaViewer/MediaViewer.js, src/components/SharedComponents/Map/CurrentLocationButton.tsx, src/components/SharedComponents/Map/DetailsMap.js, src/components/SharedComponents/Map/LocationIndicator.tsx, src/components/SharedComponents/Map/Map.tsx, src/components/SharedComponents/Map/ObsUrlTile.tsx, src/components/SharedComponents/Map/ObscuredLocationIndicator.tsx, src/components/SharedComponents/Map/SwitchMapTypeButton.tsx, src/components/SharedComponents/Map/helpers/mapHelpers.ts, src/components/SharedComponents/VeryBadIpadRotator.js, src/components/TaxonDetails/TaxonMapPreview.js, src/providers/ExploreContext.tsx, src/sharedHelpers/visionCameraPatches.js, src/sharedHooks/useDeviceOrientation.ts, tests/unit/components/Explore/MapView.test.js, tests/unit/components/MyObservations/MyObservations.test.js
=> 1684 explore map null

src/components/TaxonDetails/Taxonomy.js, src/components/TaxonDetails/TaxonomyCommonName.tsx, src/components/TaxonDetails/TaxonomyScientificName.tsx, src/components/TaxonDetails/TaxonomyTaxon.tsx, tests/unit/components/TaxonDetails/Taxonomy.test.js
=> Push TaxonDetails onto nav stack in Taxonomy section

patches/react-native-paper+5.12.3.patch, src/components/Explore/Modals/ExploreFiltersModal.js, src/components/Explore/Modals/ExploreLocationSearchModal.tsx, src/components/Explore/Modals/ExploreProjectSearchModal.tsx, src/components/Explore/Modals/ExploreTaxonSearchModal.tsx, src/components/Explore/Modals/ExploreUserSearchModal.tsx, src/components/Explore/Modals/FilterModal.tsx, src/components/MediaViewer/MediaViewerModal.js, src/components/MyObservations/MyObservationsEmpty.js, src/components/Settings/Settings.js, src/components/SharedComponents/Modal.tsx, src/components/SharedComponents/PermissionGateContainer.js, src/components/SharedComponents/RadioButtonRow.js, src/components/SharedComponents/RadioButtonRow.tsx, src/components/SharedComponents/Sheets/BottomSheetStandardBackdrop.tsx, src/components/SharedComponents/Sheets/RadioButtonSheet.js, src/components/SharedComponents/Sheets/RadioButtonSheet.tsx, src/providers/ExploreContext.tsx
=> 1746 radio bottom sheet

ios/Podfile.lock, src/components/TaxonDetails/TaxonDetails.js, tests/integration/navigation/TaxonDetails.test.js, tests/unit/components/TaxonDetails/TaxonDetails.test.js
=> Show select taxon button on ancestor/child TaxonDetails

src/components/Camera/Buttons/GreenCheckmark.js, src/components/MediaViewer/MainMediaDisplay.js, src/components/MediaViewer/MediaViewer.js, src/components/MyObservations/MyObservationsEmpty.js, src/components/MyObservations/Toolbar.js, src/components/ObsDetails/PhotoContainer.js, src/components/ObsEdit/EvidenceList.js, src/components/ObsEdit/Sheets/AddEvidenceSheet.js, src/components/SharedComponents/Buttons/AddObsButton.js, src/components/SharedComponents/Buttons/GradientButton.js, src/components/SharedComponents/Sheets/WarningSheet.tsx, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, src/realmModels/ObservationPhoto.js, src/realmModels/ObservationSound.js, src/realmModels/Photo.js, src/realmModels/Sound.js, src/sharedHelpers/logging.js, src/stores/createObservationFlowSlice.js, tests/integration/PhotoDeletion.test.js, tests/integration/navigation/AICamera.test.js, tests/integration/navigation/SoundRecorder.test.js, tests/integration/navigation/StandardCamera.test.js, tests/jest.setup.js, tests/unit/components/BottomTabNavigator/__snapshots__/CustomTabBar.test.js.snap, tests/unit/components/SharedComponents/ObservationsFlashList/__snapshots__/ObsGridItem.test.js.snap
=> Restore photo deletion

src/components/PhotoImporter/PhotoGallery.js, tests/integration/navigation/PhotoGallery.test.js, tests/jest.setup.js, tests/mocks/react-native-image-picker.js
=> Land user on Suggestions when one photo imported

src/components/Projects/ProjectsContainer.tsx
=> Set current tab depending on wether user is logged in or not

src/components/Camera/AICamera/AICameraButtons.js
=> Flip disabled state for tablets in AICamera

ios/Podfile.lock, package-lock.json, package.json, src/components/MyObservations/MyObservationsEmpty.js, src/components/MyObservations/MyObservationsHeader.js, src/components/SharedComponents/Buttons/AddObsButton.js, src/components/SharedComponents/Buttons/GradientButton.tsx
=> 1811 ai button home align

src/components/Camera/AICamera/AICamera.js, src/components/Camera/AICamera/AICameraButtons.js, src/components/Camera/AICamera/AICameraButtons.tsx, src/components/Camera/AICamera/hooks/usePredictions.ts, src/components/Camera/Buttons/CameraFlip.tsx, src/components/Camera/Buttons/Close.tsx, src/components/Camera/Buttons/Flash.tsx, src/components/Camera/Buttons/GreenCheckmark.tsx, src/components/Camera/Buttons/Zoom.tsx, src/components/Camera/CameraWithDevice.tsx, src/components/Camera/StandardCamera/CameraOptionsButtons.js, src/components/Camera/TabletButtons.tsx, src/components/SharedComponents/Buttons/CloseButton.tsx, src/components/SharedComponents/Buttons/TransparentCircleButton.tsx, src/components/SharedComponents/MediaNavButtons.js
=> 1820 multiple navigations camera

src/components/TaxonDetails/TaxonDetails.js, tests/unit/components/TaxonDetails/TaxonDetails.test.js
=> Fixes for displaying select taxon button

src/components/Camera/hooks/usePrepareStoreAndNavigate.js, src/components/Suggestions/Suggestions.js, src/components/Suggestions/SuggestionsContainer.tsx, src/components/Suggestions/SuggestionsFooter.tsx, src/components/Suggestions/hooks/useNavigateWithTaxonSelected.js, tests/integration/PhotoDeletion.test.js, tests/unit/components/Suggestions/Suggestions.test.js
=> Fix: don't show taxon on ObsEdit after skipping ID

src/components/Camera/hooks/usePrepareStoreAndNavigate.js, tests/integration/navigation/AICamera.test.js, tests/jest.setup.js
=> Create new obs when backing out to AICamera

src/components/SharedComponents/UploadStatus/UploadStatus.js, tests/unit/components/SharedComponents/UploadStatus/__snapshots__/UploadStatus.test.js.snap
=> Increase width of upload circle to 2.5

src/components/Suggestions/Suggestions.js, src/components/Suggestions/SuggestionsContainer.tsx, src/components/Suggestions/SuggestionsFooter.tsx, src/components/Suggestions/SuggestionsHeader.tsx, src/components/Suggestions/helpers/sortSuggestions.ts, src/components/Suggestions/hooks/useOnlineSuggestions.ts, tests/integration/SuggestionsWithUnsyncedObs.test.js, tests/unit/components/Suggestions/Suggestions.test.js
=> Fix location toggle on Suggestions

src/sharedHooks/useWatchPosition.ts
This wasn't quite working as intended. Also sets isFetchingLocation correctly when it starts to fetch location.
=> Bugfix: stop watching location when screen blurs

src/components/SharedComponents/Buttons/AddObsButton.js, tests/integration/navigation/AddObsButton.test.js
=> Reset stack when user navigates from AddObsModal

src/components/Suggestions/hooks/useOfflineSuggestions.js
=> Show iconic taxon icons from offline suggestions

src/components/SharedComponents/Sheets/BottomSheet.js, src/components/SharedComponents/Sheets/TextInputSheet.js
=> Persist keyboard taps in bottom sheet

src/components/ObsDetails/SoundContainer.js
=> Only show offline notice for sounds urls with http

src/components/Explore/TaxonGridItem.tsx, src/components/SharedComponents/DisplayTaxon.js, src/components/SharedComponents/DisplayTaxonName.js, src/components/SharedComponents/ObservationsFlashList/ObsGridItem.js, src/components/SharedComponents/ObservationsFlashList/ObsListItem.js, src/components/SharedComponents/TaxonResult.js, src/components/TaxonDetails/TaxonDetailsTitle.js, src/realmModels/User.js, src/realmModels/index.js
=> Display scientific names only based on user settings

src/components/ObsDetails/ActivityTab/ActivityItem.js, src/components/ObsDetails/ActivityTab/DisagreementText.tsx, src/components/ObsDetails/Sheets/PotentialDisagreementSheet.js, src/components/SharedComponents/DisplayTaxonName.js, src/components/SharedComponents/RadioButtonRow.tsx, src/components/SharedComponents/ScientificName.js, src/components/SharedComponents/Sheets/RadioButtonSheet.tsx, src/components/hooks/useLinking.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, tests/unit/components/DisplayTaxonName.test.js
=> Use DisplayTaxonName component for disagreements

src/components/Explore/SearchScreens/ExploreTaxonSearch.js, src/components/ObsEdit/IdentificationSection.js, src/components/SharedComponents/TaxonResult.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl
=> Add remove button to ObsEdit ID section

src/stores/createObservationFlowSlice.js
Close #1802 - fix - deleting a photo when creating multiple observation - also deletes other observations
=> Deleting photos from new does not delete other new observations

src/components/App.js, src/components/Settings/Settings.js, tests/integration/MyObservationsLocalization.test.js, tests/unit/components/Settings.test.js
=> Settings: hide localization section & show internet errors

e2e/signedIn.e2e.js, src/components/Camera/AICamera/AICameraButtons.tsx, src/components/Camera/AICamera/AIDebugButton.js, src/components/Camera/Buttons/Flash.tsx, src/components/Camera/Buttons/Gallery.tsx, src/components/Camera/Buttons/TakePhoto.tsx, src/components/Camera/TabletButtons.tsx, src/components/PhotoImporter/PhotoGallery.js
=> AI Camera gallery button

src/components/MyObservations/hooks/useSyncObservations.ts, src/components/MyObservations/hooks/useUploadObservations.ts, src/stores/createSyncObservationsSlice.ts, src/stores/createUploadObservationsSlice.ts
=> Keep app awake during bulk uploads

src/components/Camera/hooks/usePrepareStoreAndNavigate.js, src/components/Suggestions/Suggestions.js, src/components/Suggestions/SuggestionsEmpty.tsx, src/components/Suggestions/SuggestionsLoading.tsx, tests/unit/components/Suggestions/Suggestions.test.js
=> Show vision result from AICamera in Suggestions loading screen

src/components/PhotoSharing.js, src/components/hooks/useFreshInstall.js
=> Use new MMKV instance to check for fresh installs

src/navigation/ContextHeader.js
- Make sure back button still shows up when coming from PhotoSharing (and allows user to back out to ObsList)
=> Fix GroupPhotos back button 

src/components/ObsEdit/EvidenceList.js, src/components/SharedComponents/DisplayTaxonName.js, src/components/SharedComponents/TaxonResult.js, src/sharedHelpers/geolocationWrapper.ts, src/sharedHelpers/shouldFetchObservationLocation.ts, src/sharedHooks/useWatchPosition.ts, src/stores/createObservationFlowSlice.js, tests/integration/ObsEditOffline.test.js, tests/integration/ObsEditOnline.test.js, tests/integration/PhotoDeletion.test.js, tests/integration/SuggestionsWithSyncedObs.test.js, tests/integration/SuggestionsWithUnsyncedObs.test.js, tests/jest.setup.js, tests/unit/sharedHooks/useWatchPosition.test.js
=> Don't restart location fetch when view blurred

src/sharedHelpers/shouldFetchObservationLocation.ts
=> Fetch location for Camera photos on ObsEdit

src/components/MyObservations/MyObservationsEmpty.js
=> Center logged out content in home screen

src/components/LoginSignUp/ForgotPasswordForm.js
=> Change forgot password input text

src/components/Settings/Settings.js
=> Make sure realm user gets updated after sci/common name change

src/components/Suggestions/SuggestionsContainer.tsx, src/sharedHooks/useLocationPermission.tsx
=> Fix useLocationPermission to avoid infinite component rerenders

src/components/Suggestions/Suggestions.js, src/components/Suggestions/SuggestionsContainer.tsx, src/components/Suggestions/SuggestionsEmpty.tsx, src/components/Suggestions/SuggestionsHeader.tsx, src/components/Suggestions/SuggestionsOffline.tsx
=> Suggestions from ObsDetail should not crash app while offline

src/components/Explore/SearchScreens/EmptySearchResults.tsx, src/components/Explore/SearchScreens/ExploreLocationSearch.js, src/components/Explore/SearchScreens/ExploreProjectSearch.js, src/components/Explore/SearchScreens/ExploreUserSearch.js, src/components/SharedComponents/TaxaList/TaxaList.tsx, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl
=> Standardize offline notice, empty results, and loading for search screens

src/components/MyObservations/MyObservationsContainer.js, src/components/MyObservations/ToolbarContainer.js, tests/integration/navigation/MyObservations.test.js, tests/unit/components/MyObservations/ToolbarContainer.test.js
=> Upload status fixes

src/components/ObsDetails/HeaderKebabMenu.js, src/components/ObsDetails/ObsDetailsHeader.tsx, src/components/SharedComponents/KebabMenu.js, src/components/SharedComponents/OverlayHeader.tsx, src/components/SharedComponents/index.js, src/components/TaxonDetails/TaxonDetails.js, src/components/TaxonDetails/TaxonDetailsHeader.tsx
=> Standardize taxon/obs details header component

src/components/MyObservations/MyObservationsContainer.js, src/components/MyObservations/hooks/useUploadObservations.ts, src/components/ObsEdit/BottomButtons.js, src/sharedHelpers/uploadObservation.js, src/stores/createUploadObservationsSlice.ts
=> Aborting upload should not prevent future uploads

src/components/FullPageWebView/FullPageWebView.tsx
May address #1985, but requires testing with a working PayPal account.
=> Allow FullPageWebView to open popups

src/components/MyObservations/MyObservationsHeader.js, src/components/MyObservations/Onboarding.js
Also changes the spacing for the "Welcome back" text, as this was present in the design files but not in the app.
=> Change spacing for onboarding text

src/components/SharedComponents/UserText.js
=> Change text color of UserText

src/components/Explore/ExploreContainer.js, src/components/Explore/hooks/useParams.js, src/components/MyObservations/ToolbarContainer.js, src/components/ProjectDetails/ProjectDetails.js, src/components/TaxonDetails/TaxonDetails.js, src/components/UserProfile/UserProfile.js, src/stores/createExploreSlice.ts
=> Ensure ExploreContainer state is preserved when navigating back

src/components/MyObservations/ToolbarContainer.js, src/components/MyObservations/hooks/useSyncObservations.ts, src/stores/createSyncObservationsSlice.ts
=> Stop notifying user about automatic syncing

src/components/FullPageWebView/FullPageWebView.tsx, src/components/Settings/Settings.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, tests/unit/components/FullPageWebView/FullPageWebView.test.js
* Allow the in-app browser to open users/delete from settings
* When account deletion successful, sign the user out
Depends on https://github.com/inaturalist/inaturalist/pull/4206
=> Account deletion improvements

src/realmModels/Taxon.js
=> Show correct iconic taxon icon in Explore Species View

src/components/Suggestions/SuggestionsContainer.tsx, src/sharedHooks/useLocationPermission.tsx
Stabilizes some of the props to prevent some re-renders.
Closes #1878
=> fix: reduce image flickering on Suggestions

src/components/MediaViewer/AttributionButton.tsx, src/components/MediaViewer/MainMediaDisplay.js, tests/unit/components/MediaViewer/MediaViewer.test.js
closes https://github.com/inaturalist/iNaturalistReactNative/issues/1570
=> Remove attribution for new photo in MediaViewer

src/navigation/CustomDrawerContent.tsx
=> Navigate to user's profile from drawer

src/components/Explore/MapView.tsx
=> Use observationBounds for nearby Explore map

src/components/TaxonDetails/TaxonMapPreview.js
=> Hide taxon map preview when taxon has no observations

src/components/LoginSignUp/LoginForm.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl
=> add reveal button for password field in login

src/components/Camera/AICamera/AICamera.js, src/components/Camera/StandardCamera/StandardCamera.js, src/components/Camera/hooks/useZoom.ts
=> 1667 front zoom

src/providers/ExploreContext.tsx, src/sharedHooks/useInfiniteScroll.js
=> 2024 faster explore load

src/components/ObsDetails/DetailsTab/DetailsTab.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, tests/unit/components/ObsDetails/DetailsTab.test.js
=> resolve typos on obs detail

src/components/Explore/Modals/FilterModal.tsx, src/components/SharedComponents/UserListItem.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl
=> 1595 removable explore filters

src/components/ObsDetails/ObsMediaDisplay.js
=> add condition to show count for more than one obs

src/navigation/CustomDrawerContent.tsx
=> make drawer scrollable

src/components/ProjectDetails/ProjectDetailsContainer.js
=> fix: fetch project memebership only when signed in

package-lock.json, package.json, src/components/ObsDetails/ObsMedia.js, src/components/SharedComponents/CarouselDots.tsx, src/components/SharedComponents/index.js, src/components/TaxonDetails/TaxonDetails.js
=> add carousel dots component

src/components/SharedComponents/Map/Map.tsx
=> Add a cameraZoomRange default

src/components/ObsDetails/SoundContainer.js
=> fix: replaying and scrubbing audio repeatedly eventually stops playback

src/components/ObsDetails/FaveButton.js
=> fix: fave status was lost when leaving ObsDetails

src/components/SharedComponents/PermissionGateContainer.tsx
closes #1206 
https://github.com/user-attachments/assets/3e5bddc1-4477-4906-8a0d-2e52e53ac40c
=> fix: pass PermissionGate after granting permission in Settings and returning to app

src/components/ProjectDetails/ProjectDetails.js, src/components/ProjectDetails/ProjectMembers.tsx, src/components/SharedComponents/OverviewCounts.js, src/components/TaxonDetails/Wikipedia.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl, src/navigation/ContextHeader.js, src/navigation/StackNavigators/TabStackNavigator.js
Closes #2114 
- Adds a project members screen with infinite scrolling, accessible from ProjectDetails
=> Feat: Project members screen

src/components/PhotoImporter/GroupPhotos.js, src/components/SharedComponents/FloatingActionBar.js, src/components/SharedComponents/StickyToolbar.js
=> Float action bar relative to sticky toolbar, not bottom of screen

src/components/ObsDetails/DetailsTab/DetailsTab.js
=> add share button in obs detail

index.js, src/components/App.js, src/components/Camera/AICamera/AICamera.js, src/components/Camera/StandardCamera/StandardCamera.js, src/components/Camera/hooks/useDeviceStorageFull.js, src/components/Camera/hooks/usePrepareStoreAndNavigate.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl
=> feat: phone storage full alert

src/components/SharedComponents/PermissionGateContainer.tsx, src/navigation/StackNavigators/NoBottomTabStackNavigator.js
=> fix: do not allow rotation in PermissionGate on Android

src/components/ObsEdit/ObsEdit.js, src/components/ObsEdit/ObsEditHeader.js
=> Allow ObsEdit to scroll to bottom with larger text enabled

src/components/AddObsModal.tsx
=> Tweak styling of AddObsModal for smaller screen sizes

android/app/build.gradle, fastlane/metadata/android/en-US/changelogs/120.txt, ios/iNaturalistReactNative.xcodeproj/project.pbxproj, ios/iNaturalistReactNative/Info.plist, ios/iNaturalistReactNativeTests/Info.plist, src/api/log.ts, src/components/FullPageWebView/FullPageWebView.tsx, src/components/LoginSignUp/AuthenticationService.ts, src/components/MyObservations/helpers/syncRemoteDeletedObservations.ts, src/components/MyObservations/helpers/syncRemoteObservations.ts, src/realmModels/ObservationPhoto.js, src/sharedHelpers/logging.js, src/sharedHelpers/taxon.js, src/sharedHelpers/uploadObservation.js, src/sharedHooks/useAuthenticatedInfiniteQuery.ts, src/sharedHooks/useAuthenticatedMutation.js, src/sharedHooks/useAuthenticatedQuery.js, tests/integration/SuggestionsWithUnsyncedObs.test.js, tests/unit/components/LoginSignUp/AuthenticationService.test.js
* Catch and squelch "Network request failed" errors that happen during logging itself (#1639)
* Log around RNSI access to resolve when/where those errors occur (#1639)
* Log around JWT retrieval to resolve when/where JWT missing errors occur (#2155)
=> refactor: log around repeat errors

src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/l10n/id.ftl, src/i18n/l10n/id.ftl.json, src/i18n/strings.ftl
=> Fix typo in name of Sara Beery

src/components/SharedComponents/Sheets/TextInputSheet.js
=> feat: Max font scaling for text inputs

src/components/Developer/UiLibrary/ObsGridItemDemo.js, src/components/Developer/UiLibrary/ObsListItemDemo.js, src/components/ObservationsFlashList/ObsGridItem.js, src/components/ObservationsFlashList/ObsItem.js, src/components/ObservationsFlashList/ObsListItem.js, src/components/ObservationsFlashList/ObsPressableContainer.tsx, src/components/ObservationsFlashList/ObsUploadStatus.js, src/components/ObservationsFlashList/ObservationsFlashList.js, src/components/SharedComponents/UploadStatus/UploadStatus.tsx, tests/unit/components/SharedComponents/ObservationsFlashList/ObsUploadStatus.test.js, tests/unit/components/SharedComponents/UploadStatus/UploadStatus.test.js, tests/unit/components/SharedComponents/UploadStatus/__snapshots__/UploadStatus.test.js.snap
Pulls store interaction up a few levels in the hierarchy to make demos and tests of upload-related components simpler.
=> refactor: restore ObsGridItem and ObsListItem UI demos

src/components/ObsDetails/DetailsTab/DetailsTab.js, src/components/ProjectDetails/ProjectDetails.js
=> Fixes several minor UI issues in projects details

src/components/ObsDetails/ActivityTab/ActivityHeaderContainer.js
=> fix : flagged comments still appears flagged after being resolved 

fastlane/metadata/android/hu-HU/full_description.txt, fastlane/metadata/android/hu-HU/short_description.txt
Testing: do not merge! Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)
=> Testing: do not merge! Crowdin Translations

src/components/SharedComponents/Sheets/TextInputSheet.js
=> fix: unable to clear note once written

src/components/FullPageWebView/FullPageWebView.tsx
=> Add large font size scaling in webviews

src/components/TaxonDetails/TaxonMedia.js
=> fix: add gradient background over photos on TaxonDetails for iPad

src/components/ObsEdit/BottomButtons.js, src/components/ObsEdit/ObsEditHeader.js, src/stores/createObservationFlowSlice.js, tests/integration/navigation/ObsEdit.test.js
=> Show discard sheet if any observations saved/uploaded in multi-obs flow

ios/InfoPlist.xcstrings, src/components/ObsEdit/ObsEdit.js, tests/integration/navigation/MyObservations.test.js, tests/integration/navigation/ObsEdit.test.js
=> Reset queue before adding new observations to upload queue

src/components/Settings/Settings.js
=> fix: only cover online settings w/ spinner while saving

src/components/SharedComponents/Sheets/TextInputSheet.js
=> Fix resetting character count in feedback form

src/components/ObsDetails/DetailsTab/LocationSection.tsx
=> add expand map button in obs detail

src/components/MyObservations/MyObservationsHeader.js
=> Link profile from MyObs header

src/i18n/i18ncli.js
=> Validate date formats in FTL files

src/components/Explore/Explore.js
=> feat: change color of Explore view switcher

src/components/SharedComponents/PhotoCount.js, tests/unit/components/SharedComponents/PhotoCount/__snapshots__/PhotoCount.test.js.snap
=> fix: photocount text overflows icon

src/components/Help/Help.tsx
=> Exchange help link

src/components/ObsDetails/DetailsTab/ProjectSection.tsx, src/components/UserProfile/UserProfile.js, src/navigation/CustomDrawerContent.tsx, tests/integration/SuggestionsWithUnsyncedObs.test.js, tests/unit/components/ObsDetails/DetailsTab.test.js, tests/unit/components/UserProfile/UserProfile.test.js
=> Make projects visible in drawer, observation details and on user profiles

src/components/MyObservations/MyObservationsContainer.js, src/components/MyObservations/MyObservationsEmpty.js, src/components/ObservationsFlashList/ObservationsFlashList.js, src/sharedHooks/useInfiniteObservationsScroll.js, tests/integration/MyObservations.test.js, tests/unit/components/MyObservations/MyObservations.test.js
=> fix: show onboarding content when signed in user has 0 observations

src/components/Developer/UiLibrary/ObsGridItemDemo.js, src/components/ObservationsFlashList/ObsGridItem.js, src/components/ObservationsFlashList/ObsListItem.js, src/components/ObservationsFlashList/ObsPressable.tsx, src/components/ObservationsFlashList/util.ts, src/components/SharedComponents/PhotoCount.js, tests/unit/components/SharedComponents/PhotoCount/__snapshots__/PhotoCount.test.js.snap
=> fix: center number in photo count

src/components/MediaViewer/MainMediaDisplay.js, src/components/MediaViewer/MediaViewer.js
=> feat: make swipe down close the media viewer

src/sharedHelpers/removeSyncedFilesFromDirectory.ts
=> feat: retain local media files for one month or until 5GB threshold

src/navigation/StackNavigators/SharedStackScreens.js
=> Use standard back button on Suggestions/TaxonSearch

src/components/ObsDetails/PhotoContainer.js
=> UI fix: don't block ObsDetails view with OfflineNotice

src/components/ProjectList/ProjectListItem.tsx
=> Fix alignment for project list items with default briefcase icon

src/api/types.d.ts, src/components/Camera/AICamera/AICamera.js, src/components/Camera/CameraWithDevice.tsx, src/components/SharedComponents/Buttons/INatIconButton.tsx, src/components/SharedComponents/TaxonResult.tsx
=> feat: remove interaction from AI camera suggestion

src/components/SharedComponents/ButtonBar.tsx
I have seen a lot of logs from here in our test runs. Can this be removed?
=> Remove log statement

README.md
=> Add description of sentinel files in README

src/components/SharedComponents/SimpleObservationLocation.js
=> fix: change No Location to Add Location on match screen

src/components/Match/EmptyMapSection.js, src/components/Match/MatchHeader.js, src/components/SharedComponents/Typography/Subheading2.tsx, src/components/SharedComponents/index.js, tests/unit/components/SharedComponents/Typography/Subheading2.test.js, tests/unit/components/SharedComponents/Typography/__snapshots__/Subheading2.test.js.snap
=> Create text style Subheading2 and apply in Match screen

src/components/Developer/UiLibrary.js, src/components/Developer/UiLibrary/LoginSignUpLearnMoreDemo.js, src/components/Developer/UiLibraryItem.js, src/components/LoginSignUp/LearnMore.tsx, src/navigation/StackNavigators/LoginStackNavigator.js
=> feat: add a LearnMore screen for use in signup flow

src/components/TaxonDetails/TaxonDetails.js
=> Hide explore button on TaxonDetails from Match

src/navigation/StackNavigators/TabStackNavigator.js, src/navigation/navigationOptions.js
=> Prevent swiping back on root screens

src/components/Camera/AICamera/AICamera.js, src/components/Camera/Buttons/Gallery.tsx, src/components/Match/Match.js, src/components/Match/MatchContainer.js, src/components/PhotoImporter/PhotoGallery.js, src/components/Suggestions/SuggestionsLoading.tsx, src/stores/createObservationFlowSlice.js, tests/unit/components/Suggestions/Suggestions.test.js
Closes MOB-339
- Also limit gallery selection to one photo when advancing to Match
=> Show match screen after gallery from AICamera in default mode

src/components/Match/AdditionalSuggestions/AdditionalSuggestionsScroll.js, src/components/Match/AdditionalSuggestions/SuggestionsResult.js, src/components/Match/MatchContainer.js, src/components/Match/calculateConfidence.js, src/components/SharedComponents/DisplayTaxonName.js
=> Update confidence scores on Match screen

src/components/Match/AdditionalSuggestions/AdditionalSuggestionsScroll.js, src/components/Match/Match.js, src/components/Match/MatchContainer.js, src/components/Match/PhotosSection.js
Closes MOB-368
- Reorders the other suggestion list, moves the top suggestion into the match header, and updates taxon photos with the new top suggestion
=> feat: select other suggestions in Match screen

tests/integration/ObsDetails.test.js
There was only one integration test dealing with ObsDetails, so this change runs it in the new default mode and whatever we're calling the regular mode (advanced? idk anymore).
Closes MOB-333
=> test: run same integration tests for ObsDetails in both modes

index.js, src/navigation/OfflineNavigationGuard.tsx
=> Fix: alert user and go back from login screen when no connectivity

index.js, ios/Podfile.lock, package-lock.json, package.json, src/components/SharedComponents/CarouselDots.tsx, src/realmModels/Identification.js, src/realmModels/Observation.js, src/realmModels/ObservationPhoto.js, src/realmModels/ObservationSound.js, src/realmModels/Sound.js, src/sharedHelpers/installData.ts, tests/jest.setup.js
* replace react-native-uuid with uuid, which might do a better job making UUIDs more random
Work toward MOB-367
=> fix: make UUIDs more random

src/components/PhotoImporter/PhotoGallery.js
=> Fix: location name on Match screen from gallery

package-lock.json, src/components/Settings/Settings.js
=> Upgrade inatjs package and fix payload for users/update

ios/Podfile.lock, src/components/Match/Match.js, src/components/Match/PhotosSection.js
=> Add spacing to observation and taxon photos in Match screen

src/components/ObsDetailsDefaultMode/LocationSection/LocationSection.tsx
=> UI fixes for obscuration explanation in ObsDetails default mode

src/navigation/BottomTabNavigator/NavButton.js, tests/unit/components/BottomTabNavigator/__snapshots__/CustomTabBar.test.js.snap
=> Reduce size of nav button text

src/sharedHelpers/validateRealmSearch.ts, src/sharedHooks/useTaxonSearch.ts
=> Fix: crash when typing non-alphanumeric chars in offline taxon search

src/components/Notifications/NotificationsTab.tsx
=> Make notification tab headings larger

src/components/Match/AdditionalSuggestions/AdditionalSuggestionsScroll.js, src/components/Match/Match.js
=> Show Learn more button only when online

src/components/Camera/AICamera/FrameProcessorCamera.js, src/components/Camera/AICamera/hooks/usePredictions.ts, src/components/Match/AdditionalSuggestions/AdditionalSuggestionsScroll.js, src/components/Match/Match.js, src/components/Match/MatchContainer.js, src/components/Match/calculateConfidence.js, src/components/SharedComponents/IconicTaxonChooser.tsx, src/sharedHelpers/mlModel.ts
Sets camera values to defaults, exactly like Seek works.
Loading indicator while other suggestions are being fetched.
Fix a bug with lingering state of previous score_image request.
Refactor top suggestion to a state.
part of MOB-430
=> Few match screen updates

src/components/Match/Match.js, src/components/Match/MatchContainer.js, src/components/ObsDetailsDefaultMode/MapSection/MapSection.js
=> Map tiles on match screen

src/components/Settings/Settings.js
=> Also switch back advanced mode to default

src/stores/createLayoutSlice.js
=> Initial app state is in advanced mode (for now)

.github/workflows/e2e_ios.yml, src/components/MyObservations/MyObservationsSimple.tsx, src/components/MyObservations/MyObservationsSimpleHeader.tsx
=> Feat: sync button rotates in default mode

.github/workflows/e2e_ios.yml, src/api/log.ts, src/navigation/CustomDrawerContent.tsx
=> Feat: track default vs. advanced mode in grafana

src/components/TaxonDetails/TaxonDetailsHeader.tsx
=> Change taxon details header to be Heading3

src/components/Match/PhotosSection.js
=> Adapt Match screen layout depending on number of taxon photos to display

package.json, src/components/MyObservations/MyObservationsContainer.js, src/components/MyObservations/MyObservationsEmptySimple.js, src/components/MyObservations/MyObservationsSimple.tsx, src/components/MyObservations/MyObservationsSimpleHeader.tsx, src/components/SharedComponents/InlineUser/HeaderUser.js, src/components/SharedComponents/InlineUser/InlineUser.js, src/components/SharedComponents/InlineUser/InlineUserBase.js, src/components/SharedComponents/index.js
Closes MOB-462
Adds a user icon and name to the screen when a user is logged in but has no observations yet.
=> User info to logged-in my obs empty

src/components/MyObservations/MyObservationsSimple.tsx, src/components/MyObservations/MyObservationsSimpleContainer.tsx, src/components/MyObservations/StatTab.js, src/stores/createMyObsSlice.ts, src/stores/useStore.js
=> Persist number of observations/species in MyObservations tabs

src/components/App.js, src/sharedHooks/useShare.js
=> Fix: sharing into the app

src/components/ObsDetailsDefaultMode/LocationSection/LocationSection.tsx
=> Fix: location not showing on match screen

src/components/ObservationsFlashList/ObservationsFlashList.js
=> Add dotted empty boxes to fill up observation grid

src/components/Notifications/Notifications.tsx, src/components/OnboardingModal/OnboardingModal.tsx, src/components/OnboardingModal/OnboardingModalBase.tsx
Minor UI change to respect notches and such
=> Add top margin to pivot card x button

src/components/Settings/Settings.js, tests/unit/components/Settings/Settings.test.js
=> Changing to Advanced Mode should set the Observation Button setting to "All Observation Options"

e2e/signedIn.e2e.js, src/components/Explore/ObservationsViewBar.js, src/components/MyObservations/MyObservationsSimple.tsx, src/components/ObservationsFlashList/ObsGridItem.js, src/components/ObservationsFlashList/ObservationsFlashList.js, src/sharedHooks/useStoredLayout.js, tests/helpers/render.js, tests/integration/MyObservations.test.js, tests/integration/PhotoDeletion.test.js, tests/integration/PhotoImport.test.js, tests/integration/SuggestionsWithSyncedObs.test.js, tests/integration/SuggestionsWithUnsyncedObs.test.js, tests/integration/navigation/MediaViewer.test.js, tests/integration/navigation/ObsEdit.test.js, tests/integration/navigation/Suggestions.test.js, tests/integration/navigation/TaxonDetails.test.js, tests/unit/components/MyObservations/MyObservations.test.js, tests/unit/components/SharedComponents/ObservationsFlashList/__snapshots__/ObsGridItem.test.js.snap
=> Change default MyObs layout to grid

src/components/ObservationsFlashList/ObservationsFlashList.js
=> Tapping an observation navigates to ObsDetails in default mode

src/components/LoginSignUp/Header.js, src/components/LoginSignUp/Login.tsx, src/components/LoginSignUp/LoginForm.tsx, src/components/LoginSignUp/LoginSignUpInputField.tsx, src/components/LoginSignUp/LoginSignUpWrapper.tsx, src/components/LoginSignUp/SignUp.tsx, src/navigation/StackNavigators/LoginStackNavigator.js
=> Fix: login screen scroll to input field

src/api/types.d.ts, src/components/Match/AdditionalSuggestions/SuggestionsResult.js, src/components/Match/MatchContainer.js, src/components/Match/PhotosSection.js, src/components/SharedComponents/TaxonResult.tsx, src/components/TaxonDetails/TaxonDetails.js, src/realmModels/types.d.ts
Closes MOB-455
Closes MOB-334
Closes MOB-491
=> Photo similarity representative photo result sent to taxon details

__mocks__/vision-camera-plugin-inatvision.ts, src/sharedHelpers/mlModel.ts, src/sharedHooks/useSuggestions/filterSuggestions.js, src/sharedHooks/useSuggestions/useOfflineSuggestions.ts, src/sharedHooks/useSuggestions/useSuggestions.js
Closes MOB-373
Changes to allow for matching usage of common ancestor from offline results. See atomic commit messages for intent details.
=> Offline suggestions should have parity with online

src/components/Match/AdditionalSuggestions/SuggestionsResult.js, src/components/MyObservations/MyObservationsSimple.tsx, src/components/ObsDetails/DataQualityAssessment.js, src/components/ObsDetailsDefaultMode/DataQualityAssessment.js, src/components/ObservationsFlashList/ObsGridItem.js, src/components/ObservationsFlashList/ObsImage.tsx, src/components/ObservationsFlashList/ObsImagePreview.tsx, src/components/ObservationsFlashList/ObsListItem.js, src/components/ObservationsFlashList/ObsPressable.tsx, src/components/ObservationsFlashList/ObsUploadStatus.tsx, src/components/ObservationsFlashList/ObservationsFlashList.js, src/components/PhotoImporter/GroupPhotoImage.js, src/components/SharedComponents/ActivityCount/ActivityCount.tsx, src/components/SharedComponents/ActivityCount/CommentsCount.tsx, src/components/SharedComponents/ActivityCount/IdentificationsCount.tsx, src/components/SharedComponents/DateDisplay.tsx, src/components/SharedComponents/IconicTaxonIcon.tsx, src/components/SharedComponents/ObsStatus.tsx, src/components/SharedComponents/PhotoCount.tsx, src/components/SharedComponents/QualityGradeStatus/QualityGradeStatus.tsx, src/components/SharedComponents/TaxonGridItem.tsx, src/components/SharedComponents/TaxonResult.tsx, src/components/SharedComponents/UploadStatus/UploadStatus.tsx, src/realmModels/types.d.ts, tests/integration/MyObservations.test.js, tests/integration/navigation/MyObservations.test.js, tests/unit/components/SharedComponents/ObservationsFlashList/ObsStatus.test.js, tests/unit/components/SharedComponents/ObservationsFlashList/ObsUploadStatus.test.js
=> Hide observation status for logged out users on simple MyObs

src/components/Developer/UiLibrary/PivotCardsDemo.js, src/components/OnboardingModal/OnboardingModalBase.tsx
=> Fix: pivot cards not closing with X button

src/components/ObsDetailsDefaultMode/ObsDetailsDefaultMode.js
=> Add bottom card UI when not in simple mode

src/components/Match/MatchContainer.js
Came up in a comment here:
https://linear.app/inaturalist/issue/MOB-485/after-a-user-grants-location-permissions-on-the-match-screen-return#comment-37e3a3d6
=> Also scroll to top when location permission is granted

src/components/ObsDetails/ActivityTab/ActivityItem.js, src/components/ObsDetailsDefaultMode/CommunitySection/ActivityItem.js
=> Fix agree button placement in both ObsDetails screens

src/components/MyObservations/MyObservationsSimple.tsx
=> Remove Announcements from default mode

src/components/Match/AdditionalSuggestions/AdditionalSuggestionsScroll.js, src/components/Match/AdditionalSuggestions/SuggestionsResult.js
=> Fix for height of additional suggestions on Match

src/components/ObsDetailsDefaultMode/ObsDetailsDefaultMode.js
=> Hide floating buttons for unsaved observations in ObsDetailsDefaultMode

ios/iNaturalistReactNative.xcodeproj/project.pbxproj, src/components/MediaViewer/CustomImageZoom.tsx, src/components/MediaViewer/MainMediaDisplay.js
Closes Mob-226
- was tempted, but did not handle the case where a photo is zoomed in and a user pans to the edge of the zoomed in photo. we might want a separate issue for that in the future.
=> Reset zoom when tapping a different photo in media viewer

src/components/MyObservations/MyObservationsSimple.tsx, src/components/MyObservations/MyObservationsSimpleContainer.tsx, src/components/ObsDetailsDefaultMode/ObsDetailsDefaultMode.js, src/components/ObsDetailsDefaultMode/ObsDetailsDefaultModeContainer.js
=> Crash fix & offline notice for species tab of MyObs

src/components/AddObsModal/AddObsButton.tsx, src/components/Developer/UiLibrary/Buttons.js, src/components/MyObservations/MyObservationsSimpleHeader.tsx, src/navigation/BottomTabNavigator/CustomTabBar.js, tests/integration/navigation/AddObsButton.test.js
=> Add a plus icon button to add all observation types to default mode header

src/navigation/StackNavigators/NoBottomTabStackNavigator.js, src/navigation/StackNavigators/SharedStackScreens.js, src/navigation/StackNavigators/TabStackNavigator.js
=> Max lines of 1 for all headers

src/components/Camera/hooks/useZoom.ts, tests/unit/components/Camera/StandardCamera.test.js, tests/vision-camera/vision-camera.js
=> Only add zoom options if camera device has the actual physical devices

src/components/PhotoSharing.js
=> Fix: reset store when sharing photos into the app

e2e/aiCamera.e2e.js, e2e/sharedFlows/dismissAnnouncements.js, e2e/sharedFlows/signIn.js, e2e/signIn.e2e.js.js, e2e/signedIn.e2e.js, src/components/LoginSignUp/LoginForm.tsx, src/components/MyObservations/Announcements.js
=> Retain user mode (advanced/default) after login

src/components/ObsDetailsDefaultMode/ObsDetailsDefaultModeContainer.js
=> Simple obs detail is also for logged in users

src/components/Match/PhotosSection.js
=> Fix: Media viewer not showing photos on match screen

src/components/MyObservations/SimpleErrorHeader.tsx
=> Replace banner icon with pencil

src/components/Camera/CameraContainer.tsx, src/components/Camera/hooks/useSavePhotoPermission.tsx
=> Save photo to device when first permission granted

src/components/Settings/Settings.js, src/stores/createLayoutSlice.ts, tests/integration/navigation/PhotoLibrary.test.js, tests/integration/navigation/StandardCamera.test.js
=> Make app default to the suggestions-first mode

src/components/Match/MatchContainer.js, src/components/Suggestions/SuggestionsContainer.tsx, src/components/Suggestions/SuggestionsFooter.tsx, src/sharedHooks/useSuggestions/useOnlineSuggestions.ts
=> Add an offline suggestions loading state

src/components/MyObservations/SimpleUploadBanner.js, src/components/MyObservations/SimpleUploadBannerContainer.js
=> Decide banner styling based on same status as text

src/components/LoginSignUp/LoginForm.tsx, src/components/MyObservations/MyObservationsContainer.js, src/components/MyObservations/MyObservationsSimple.tsx, src/components/MyObservations/MyObservationsSimpleContainer.tsx, src/sharedHooks/useLayoutPrefs.ts, src/stores/createLayoutSlice.ts
=> Update welcome back pivot card trigger conditions

src/components/Match/MatchContainer.js, src/components/Suggestions/SuggestionsContainer.tsx, src/sharedHooks/useSuggestions/useOnlineSuggestions.ts
Should make for a better loading experience while offline
=> Online suggestions also need a skipped state

src/components/LoginSignUp/SignUpConfirmationForm.tsx, src/components/LoginSignUp/SignUpForm.tsx
=> Make sign up forms accessible

src/components/Camera/CameraContainer.tsx, src/components/Camera/hooks/usePrepareStoreAndNavigate.ts, tests/integration/navigation/AICamera.test.js
=> Override show suggestions screen to always get there from AI camera

src/components/PhotoSharing.js
=> Sharing one photo routes to Match

index.js, src/components/StartupService.js
=> Improve native error handling

src/components/SharedComponents/Map/Map.tsx
=> Zoom map in further when tapping current location button

src/components/Camera/AICamera/AICamera.js, src/components/Camera/AICamera/AICameraButtons.tsx, src/components/Camera/AICamera/AIDebugButton.js, src/components/Camera/AICamera/FrameProcessorCamera.js, src/components/Camera/CameraView.tsx, src/components/Camera/FadeInOutView.tsx, src/components/Camera/StandardCamera/StandardCamera.js
On AI camera use a camera format close to screen.height / screen.width aspect ratio.
On standard camera use a camera format close to 4:3 aspect ratio.
=> Change camera format used

src/components/ObsDetails/ActivityTab/ActivityHeaderKebabMenu.js, src/components/ObsDetails/HeaderKebabMenu.js, src/components/ObsDetailsDefaultMode/CommunitySection/ActivityHeaderKebabMenu.js, src/components/ObsDetailsDefaultMode/HeaderKebabMenu.js, src/components/SharedComponents/KebabMenu.tsx
=> Hide subscribe button from kebab menu when logged out

src/components/Match/AdditionalSuggestions/AdditionalSuggestionsScroll.js, src/components/Match/IconicSuggestions/IconicSuggestionsScroll.js, src/components/Match/Match.js, src/components/Match/MatchHeader.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl
Closes MOB-611
All new design items are being added. The new UI is only to be shown when there is no top suggestion but other suggestions are present.
I am seeing some flickering in the additional suggestions list, but that is already present on current main.
=> Add a UI for when there is no top suggestion but other suggestions with low confidence on match screen

src/components/AddObsModal/AddObsButton.js, src/components/SharedComponents/Buttons/GradientButton.tsx, tests/integration/navigation/AddObsButton.test.js
=> Add long press to AICamera gradient button in default/advanced

src/components/Developer/UiLibrary/PivotCardsDemo.js, src/components/MyObservations/MyObservationsSimple.tsx, src/components/OnboardingModal/PivotCards.tsx, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl
=> Change pivot card timing from on second to fifth observation

src/components/MyObservations/MyObservationsSimple.tsx
=> In obs list show metadata (date, location) for a advanced user

src/components/MyObservations/MyObservationsSimple.tsx, src/components/ObservationsFlashList/ObsListItem.js, src/components/ObservationsFlashList/ObsPressable.tsx, src/components/ObservationsFlashList/ObservationsFlashList.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl
=> Add research grade label to default obs list

src/components/Camera/CameraContainer.tsx, src/components/Camera/hooks/usePrepareStoreAndNavigate.ts, tests/integration/SuggestionsWithUnsyncedObs.test.js, tests/integration/navigation/AICamera.test.js, tests/integration/navigation/Suggestions.test.js
=> Navigate based on setting in both cameras

src/components/Suggestions/Suggestion.tsx, src/components/Suggestions/Suggestions.js
=> Always show TaxonResult checkmark in Suggestions

src/components/Camera/Buttons/PhotoLibraryIcon.tsx, src/components/PhotoImporter/PhotoLibrary.js
=> Fix: only limit photo library selection to 1 photo from AICamera

fastlane/metadata/ios/default/description.txt, fastlane/metadata/ios/default/subtitle.txt
Closes MOB-657
Needs translation, but was also manually entered for EN directly in the App Store for version 0.59.12 (155)
=> Update default language app store metadata

src/components/Settings/Settings.js, src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl
Closes MOB-671
Temporary. Context notes in the tracking issue.
=> Change label next to the toggle for advanced mode

src/components/SharedComponents/Buttons/Button.tsx, tests/jest.setup.js
=> Fix: prevent multiple taps on Buttons like Suggest Id

src/components/LoginSignUp/AuthenticationService.ts
Pretty much as the title says we will call iNat /signout endpoint when signing out (or before signing in)
=> call iNat /signout endpoint when signing out (or before signing in)

src/components/Camera/AICamera/AICamera.js, src/components/Camera/CameraContainer.tsx, src/components/Camera/hooks/usePrepareStoreAndNavigate.ts, src/components/Match/MatchContainer.js, src/components/Suggestions/SuggestionsLoading.tsx
Displays the AICamera suggestion in the identification section of ObsEdit. This is relevant only when a user has advanced mode navigation flow set to ObsEdit.
=> Populate ObsEdit with AICamera suggestion in advanced AICamera->ObsEdit flow

src/components/SharedComponents/OverviewCounts.js, src/components/UserProfile/UserProfile.js
Minor UI changes to update user profile to be closer to design specs.
Closes MOB-652.
=> Consistent margin around user profile stats

src/components/Explore/MapView.tsx, src/components/SharedComponents/Map/Map.tsx
As linked in PR review comments.
=> To Mob 720: add some types and null guards

src/i18n/l10n/en.ftl, src/i18n/l10n/en.ftl.json, src/i18n/strings.ftl
Comment here: https://inaturalist.slack.com/archives/C02G5AATVGA/p1746214906692239
=> Add a case for one member to string

src/components/ObsEdit/IdentificationSection.js, tests/integration/navigation/Suggestions.test.js, tests/unit/components/ObsEdit/IdentificationSection.test.js
=> Hide "id with ai button" for no media or sound only

src/components/ObsDetailsDefaultMode/MoreSection/ViewInBrowserButton.tsx, src/components/ObsDetailsDefaultMode/NotesSection/NotesSection.tsx
=> Use TS in two .tsx files that used flow types

src/components/LoginSignUp/ForgotPasswordForm.js
=> MOB-772 - reset password field - change label

src/i18n/initI18next.js
=> MOB-677 - clean up locale name when loading i18next module

src/components/Match/AdditionalSuggestions/SuggestionsResult.tsx
=> MOB-692 - suggestions result crash fix

src/components/Suggestions/hooks/useNavigateWithTaxonSelected.ts
=> Fix crash when adding id to sounds

ios/Podfile.lock, package-lock.json, package.json
=> Update to react-native-vector-icons 10.2.0

src/components/FullPageWebView/FullPageWebViewHeader.tsx, src/navigation/StackNavigators/LoginStackNavigator.js, src/navigation/StackNavigators/NoBottomTabStackNavigator.js, src/navigation/StackNavigators/SharedStackScreens.js, src/navigation/StackNavigators/TabStackNavigator.js, src/navigation/navigationOptions.tsx, src/navigation/rootDrawerNavigator.js
In a branch of updating the app to use RN 0.75 this file was throwing flow errors.
Not necessarily blocking the RN update but since we want to remove flow type checks anyhow, now is as good a time as any.
=> Migrate navigationOptions to TS

src/components/ProjectDetails/ProjectDetailsContainer.js
=> Performance: fetch only needed API fields for Project Details

src/components/Explore/RootExploreContainer.js, src/components/LocationPicker/LocationPickerContainer.js, src/components/Match/MatchContainer.js, src/components/Suggestions/SuggestionsContainer.tsx
According to this answer here not returning the addListener result is unwanted.
https://github.com/inaturalist/iNaturalistReactNative/pull/2996#discussion_r2180070255
=> Return addListener result in useEffects

src/components/SharedComponents/PermissionGateContainer.tsx
=> Add small timeout to modal showing

ios/Podfile.lock, package-lock.json, package.json
After updating this library, I am no longer able to replicate these two location-fetching related issues: MOB-815, MOB-758.
So I believe this closes those issues.
=> Update @react-native-community/geolocation to latest

ios/Podfile.lock, package-lock.json, package.json
Compiled and tested in Debug and Release mode on iOS.
=> Update @react-native-community/netinfo to latest

ios/Podfile.lock, package-lock.json, package.json
Compiled and tested in Debug and Release mode on iOS.
=> Update @react-native-clipboard/clipboard to latest

package-lock.json, package.json, src/components/Camera/FocusSquare.tsx
Should have no effect on the app, so I will rely on e2e tests to check for mergeability.
Closes MOB-901
=> Update lodash types

src/components/SharedComponents/DateTimePicker.tsx
=> Show only date picker first and add time picker as second step

ios/Podfile.lock, package-lock.json, package.json
Compiled and tested in debug and release mode on both platforms.
=> Update @react native community/datetimepicker

package-lock.json, package.json
Compiled and tested in debug and release mode on iOS.
=> Update react compiler
