inaturalist/iNaturalistReactNative

- package-lock.json
- package.json
- src/components/ObsEdit/EvidenceList.js
- src/components/ObsEdit/EvidenceSection.js
- src/components/ObsEdit/ObsEdit.js
- src/components/ObsEdit/OtherDataSection.js
- src/components/Observations/hooks/useObservations.js
- src/models/Comment.js
- src/models/Identification.js
- src/models/Observation.js
- src/models/ObservationPhoto.js
- src/models/ObservationSound.js
- src/models/Photo.js
- src/models/Taxon.js
- src/models/User.js
- src/models/index.js
- src/providers/ObsEditProvider.js
- src/providers/uploadHelpers/resizeImage.js
- src/providers/uploadHelpers/saveLocalObservation.js
When a saved Realm observation is opened for ObsEdit, this PR converts that observation into a plain JS object for editing. The plain JS object can be saved as a modified object with an updated `_updated_at` timestamp.
ObsList checks to see if there are any observations which have been modified since the last `_synced_at` date and shows the correct number of observations to upload in the bottom upload modal.
This also makes ObsEdit more readable by breaking out the top section into a separate `EvidenceSection` component.
> Edit existing observations

- env.example
- index.js
- ios/Podfile.lock
- src/components/LoginSignUp/AuthenticationService.js
It was bugging me that we specified API URLs in multiple places. This will make it easier to find where those values are. Note that you have to update your `.env` file to get this branch to work correctly. See `env.example`.
> Consolidate API URL config into .env

- package-lock.json
- package.json
Prior to this commit, if I were to run `npm install` twice, I would get
this error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: inaturalistreactnative@0.1.1
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!   peer react@">= 16.8.0" from react-spring@8.0.27
npm ERR!   node_modules/react-spring
npm ERR!     react-spring@"^8.0.27" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.2.0" from react-dom@18.2.0
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@">= 16.8.0" from react-spring@8.0.27
npm ERR!   node_modules/react-spring
npm ERR!     react-spring@"^8.0.27" from the root project
```
Because `react-dom` …
> Fix NPM package version conflicts.

- android/app/src/main/AndroidManifest.xml
- src/components/ObsEdit/Notes.js
- src/components/ObsEdit/ObsEdit.js
- src/models/Observation.js
- src/navigation/mainStackNavigation.js
- src/providers/ObsEditProvider.js
- src/sharedHelpers/fetchUserLocation.js
> 123 permission fetch location

- src/components/SharedComponents/ObservationViews/ObsListHeader.js
- src/components/SharedComponents/ObservationViews/Toolbar.js
This PR resolves issue #176
- passes a prop to check if there is any unuploaded obs
- If so it would turn the sync icon to green.
> Make sync icon active for unuploaded obs

- src/components/LoginSignUp/Login.js
- src/components/LoginSignUp/Logout.js
Closes #202
- separates Logout into a new component to make code easier to reason about
- updates username on Logout screen where that state is needed
- checks to make sure the component is mounted before updating state in `useEffect` with `isCurrent` boolean
- fixes bug where the signout dialog occasionally popped up a second time on the MyObservations screen
> Fix unmounted component error, login screen

- android/build.gradle
Couldn't get Android to build, and this fixes it. Seems to be a known issue [since 0.71.0-rc.0 tag added](https://github.com/facebook/react-native/issues/35204#top).
> Fix for android build in build.gradle

- src/api/error.js
- src/api/observations.js
- src/components/ObsDetails/ObsDetails.js
Closes #223
- Set initial state of `setIds` once instead of infinite times
- Add option to throw error from `handleError` when uuid doesn't exist on server / local observation hasn't been synced; otherwise `useQuery` throws an error that says data should not be undefined
> Fix infinite loop in ObsDetail for local observations

- ios/Podfile
- ios/Podfile.lock
- ios/iNaturalistReactNative.xcodeproj/project.pbxproj
I have tested on the simulator with Debug config to see if it compiles, and it did. I then tested it on a real iPhone with Release config and it compiled and opened the app. I am not aware of the current state of the app in terms of which bugs are known, so I did not test the app functions.
On the first opening of the app, directly after installation, the app crashed and closed. The second time opening was fine. This was also the behavior when compiling from main for me, so I don't see this as a regression.
> Enable hermes for iOS

- .github/workflows/test.yml
- README.md
I have enabled caching of node_modules in the GitHub Actions test workflow. This saves us about 1min of time running the workflow on every push that does not require a new install of the dependencies. Adding a dependency or using a newer version would still require the install step. A hash of the package-lock.json file is used as a check for this.
> Cache ci node modules

- src/components/SharedComponents/Footer.js
Android still has a small space at the bottom of the tab bar but if it is reduced to less the iOS tab bar buttons will be too close to the bar at the bottom swipe up.
> 216 remove excess space below the tab bar

- src/api/messages.js
- src/components/App.js
- src/components/Messages/Messages.js
- src/components/Observations/LoginPrompt.js
- src/components/Observations/hooks/useInfiniteScroll.js
- src/components/Projects/ProjectTabs.js
- src/components/Projects/Projects.js
- src/components/Settings/Settings.js
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/strings.ftl
- src/providers/ObsEditProvider.js
- src/sharedHooks/useApiToken.js
- src/sharedHooks/useCurrentUser.js
- src/sharedHooks/useUserMe.js
- tests/unit/components/Messages/Messages.test.js
- tests/unit/components/Projects/Projects.test.js
This simplifies the `useCurrentUser` hook so that this data will be available before `useAuthenticatedQuery` tries to fetch an API token. Also fixes padding around the buttons in upload/login prompts.
> Fixes for API calls, useCurrentUser hook, api token not being fetched

- .eslintrc.js
- src/api/error.js
- src/components/Observations/ObsListBottomSheet.js
- src/realmModels/Observation.js
- src/realmModels/ObservationPhoto.js
- src/sharedHooks/useLocalObservations.js
- src/sharedHooks/useUploadObservations.js
Primary bug was that requests to POST /v2/observation_photos were using the obs serial ID instead of the obs UUID.
Another major problem was that uploads always quit before the last observation when there were multiple observations to upload, which I address by changing the way we set `allObsToUpload` in `useLocalObservations`.
> Fixes bug preventing photo uploads

- fastlane/Fastfile
> Abort fastlane if release notes exceed 500 char limit

- src/components/DisplayTaxonName.js
- src/components/Observations/ObsCard.js
- tests/unit/components/ObsEdit/DeleteObservationDialog.test.js
- tests/unit/components/Projects/ProjectObservations.test.js
The problem has something to do with the unicode capitalization code that got [ported from the web.](https://github.com/inaturalist/iNaturalistReactNative/pull/334) It seems like the JS engine in Android has a problem with calling `toUpperCase()` on some unicode characters, and this gets around that particular bug, plus one problem with a null check on a Realm collection.
This isn't the best solution and probably isn't the final one. We need to keep an eye out for problems with common name capitalization.
> Fix crash on Android after login

- src/components/ObsDetails/ObsDetails.js
- src/sharedHooks/useAuthenticatedMutation.js
@jtklein, this might address the repeated requests resulting in the 429 blocks you were experiencing in your JWT work. If you've already fixed that we can just close this PR without merging.
> Only mark obs as viewed when an existing mutation is not in flight

- index.js
- src/api/error.js
- src/components/LoginSignUp/AuthenticationService.js
- src/sharedHooks/useApiToken.js
- src/sharedHooks/useAuthenticatedMutation.js
- src/sharedHooks/useAuthenticatedQuery.js
- tests/helpers/user.js
I was never able to reliably reproduce errors with an invalid or expired JWT. So I am not sure if anything is fixed with this now. However, this PR addresses two TODOs in this issue #353 :
1) Adds a retry for react-query calls when 401 or 403 is hit, after fetching the JWT token again (if expired).
2) Now the token is not kept in state in the useApiToken hook.
> 353 retry with jwt

- tailwind.config.js
Fixes overridden border radius. When setting [theme](https://tailwindcss.com/docs/theme#extending-the-default-theme) it just had to be in the `extend` property.
An issue was brought up in pr #410 regarding the border radius not being set.
Rounded images:
Button radius defaults to 7px:
> Fix overridden border radius

- src/components/DisplayTaxonName.js
- src/components/Projects/ProjectTabs.js
- src/components/SharedComponents/Map.js
- src/realmModels/Observation.js
- src/sharedHooks/useUserLocation.js
- tests/unit/components/ObsDetails/ObsDetails.test.js
Mostly fixes #404 
Turns out it was just slow on Android. Updated the `useUserLocation` hook to optionally make the place guess which was causing an unnecessary  delay (both places which use `useUserLocation` do not use the place guess currently.
> Fix nearby projects query for android

- src/components/SharedComponents/FloatingActionBar.js
- src/components/SharedComponents/StickyToolbar.js
- src/components/SharedComponents/index.js
- src/components/UiLibrary.js
#484 
Create sticky toolbar component
The toolbar also covers up the navbar in ui library page.
I don't think `15px` padding is necessary because that can be supplied via the `containerClass` prop. I'd imagine this component should become the wrapper for the `NavBar` component so styles stay consistent throughout the app.
> 484 - Create sticky toolbar

- src/components/ObsDetails/ObsDetails.js
- src/components/SharedComponents/DateDisplay.js
- src/components/SharedComponents/INatIcon/index.js
- src/components/SharedComponents/ObservationLocation.js
> 501 502 date dispaly location styling

- src/navigation/BottomTabNavigator/index.js
- src/navigation/navigationOptions.js
Lingering issue cleanup from #499 
Was getting a double back button on the photo gallery page + unexpected back buttons on other pages.
> Fix double back button android

- src/components/PhotoImporter/GroupPhotos.js
- src/components/PhotoImporter/PhotoGallery.js
- src/components/SharedComponents/FloatingActionBar.js
- src/components/UiLibrary.js
#480 
https://user-images.githubusercontent.com/13311268/224524027-362f17fd-b4e9-43f6-b2ec-3f77838c9d86.mov
1. #517 persists on any shadow on this page for android
2. I think toolbar should remain open after you complete an action like group or separate
> Utilize floating action bar and sticky toolbar in group photos ui

- src/components/MyObservations/MyObservations.js
- src/sharedHooks/useLocalObservations.js
I found if you had two unsynced observations and deleted one, it would crash.
I took out the conditional `if ( allObsToUpload.length < unsyncedObs.length ) {` because `allObsToUpload` seems as it should be a direct reflection of what is in realm, and this conditional allows cases where they aren't in sync.
If this is necessary I can look at other ways to fix this bug.
> Remove conditional around setAllObsToUpload

- src/components/Camera/PhotoPreview.js
- src/components/Camera/StandardCamera.js
- src/components/MediaViewer/HorizontalScroll.js
- src/components/SharedComponents/PhotoCarousel.js
Closes #475
At the moment, I can rotate from portrait to landscape on iPhone but not an Android phone. I see this [line of code](https://github.com/inaturalist/iNaturalistReactNative/blob/38311ea3c7e43d2c3b55563102cf39164211bcdf/src/components/Camera/StandardCamera.js#L81) which makes me think we're intending to lock to portrait orientation on all phones and only show landscape mode on tablets. Is that correct? Either way, we should be consistent in which orientations we display across Android/iOS.
> Fix orientation of thumbnails and checkmark

- src/components/MyObservations/MyObservationsContainer.js
- src/components/SharedComponents/UserText.js
- src/sharedHooks/useLocalObservations.js
#606 
https://github.com/inaturalist/iNaturalistReactNative/assets/13311268/418bb9d2-263d-418b-a43e-c5b5e4588d5c
My first pass at a fix was to make the `MyObservations` page unmount on blur, while it worked, it lost the scroll position.
Second pass around, I used a ref to prevent any downstream rerenders and would only rerender if `MyObservations` (or any consuming user of that hook) is focused. Let me know what you think of this solution as I don't think it's particularly straightforward so I left a comment about it in the code.
On another note, I think we should default to pages unmounting on blur unless there's a specific reason not to. I feel most of the pages are lightweight enough that initial render isn't that expensive and it should save on memory usage.
> 606 - Fix render blocking state change

- package-lock.json
- src/components/MediaViewer/PhotoSelector.js
The border needs to be added to the view around an Image, not the image itself. The React Native Image component does not support border styling, which oddly leads to borders showing up on iOS but not Android.
Closes #603 and closes #622
> Border on MediaViewer images Android

- src/components/MyObservations/MyObservations.js
- src/components/ObsDetails/ObsDetails.js
- src/sharedHooks/useInfiniteScroll.js
- src/sharedHooks/useLocalObservations.js
- tests/factories/LocalObservation.js
Obs deletion bug (#545) mostly has to do with Realm objects hanging around in memory when they're no longer in the database. I spent a long time trying to write a test that could see the custom header button menu we add via react-navigation but never got it to work.
I'm not sure #545 is really "done" since I didn't figure out a way to test it. If others think that needs to be tested... I'm open to advice, but if not I think it's worth merging this and closing that issue if this work doesn't have any negative side effects.
Closes #662 (edit button on obs detail when no media)
> Fixed obs deletion bug and allow edit when obs has no media

- src/components/MyObservations/MyObservations.js
> #634 - my observations header is jittery on Android when slow scrolling

- index.js
- src/api/error.js
- src/sharedHooks/useAuthenticatedQuery.js
- src/sharedHooks/useInfiniteObservationsScroll.js
- src/sharedHooks/useObservationsUpdates.js
This prevents the infinite retries I was seeing before, so maybe it's ok to merge as is, but there are definitely some open questions:
1) Why doesn't configuring the QueryClient suffice?
2) How might we consolidate this error handling?
3) How do we notify the user?
> Don't retry queries if the servers return 503 codes

- src/components/Camera/CameraView.js
- src/sharedHelpers/visionCameraPatches.js
This is a simple patch to rotate the camera view component on an iPad depending on the device orientation.
While this fixes the problem with camera view orientation this does not changes the size of the camera view as I understood this not to be a part of this issue.
Closes #840
> 840 - Add a patch to rotate camera view on iPad

- src/components/Camera/ARCamera/ARCamera.js
- src/components/Camera/CameraContainer.js
- src/components/Camera/CameraView.js
- src/components/Camera/StandardCamera/PhotoPreview.js
- src/components/Camera/StandardCamera/StandardCamera.js
- src/components/SharedComponents/VeryBadIpadRotator.js
Per our meeting this week, the camera view now covers the visible area even though the photos it capture are the full device screen size. This improves the kludge around react-native-vision-camera's inability to handle rotation on an iPad by repositioning the rotated camera view so it fills its entire area.
> Cover camera ipad rotation

- src/components/ObsEdit/EvidenceSectionContainer.js
- src/components/PhotoImporter/GroupPhotos.js
- src/components/PhotoImporter/GroupPhotosContainer.js
- src/providers/ObsEditProvider.js
- src/providers/reducers/createObsReducer.js
- src/sharedHelpers/fetchPlaceName.js
- src/sharedHelpers/parseExif.js
- tests/jest.setup.js
The problem seemed to be reverse geocoding the coordinates for each observation before moving on to ObsEdit, i.e. when that threw an exception it kind of silently cause Promise.all not to resolve... which is not supposed to happen for a few reasons, foremost among them that we were catching the error and returning null instead. So I'm still confused about why exactly this was happening.
Regardless, geocoding is potentially slow and buggy, so IMO it's better to do it on ObsEdit than in the provider, and only do it when we need it, i.e. when the user is actually looking at the obs.
Some other minor changes
* Show loading indicator on GroupPhotos button while creating obs
* fetchPlaceName performs a null check on coords before making a network request to test connectivity
* More precise …
> Bugfix: ObsEdit was blank after importing several photos

- src/components/ObsEdit/EvidenceSection.js
- src/components/ObsEdit/Header.js
- src/components/ObsEdit/ObsEdit.js
- src/components/SharedComponents/Buttons/BackButton.js
- src/navigation/StackNavigators/SharedStackScreens.js
- tests/unit/components/ObsEdit/Header.test.js
- tests/unit/components/SharedComponents/Buttons/BackButton.test.js
Closes #907
- Use custom header rather than the react navigation header with setOptions, so we can control the padding around the back button
> Increase pressable area of back button, Obs Edit

- src/components/Explore/Explore.js
- src/components/Explore/ExploreContainer.js
- src/components/Explore/ExploreFlashList.js
- src/components/Explore/Header.js
- src/components/Explore/IdentifiersView.js
- src/components/Explore/ObservationsView.js
- src/components/Explore/ObserversView.js
- src/components/Explore/SpeciesView.js
- src/components/MyObservations/InfiniteScrollLoadingWheel.js
- src/components/MyObservations/MyObservations.js
- src/components/SharedComponents/ObservationsFlashList/ObservationsFlashList.js
- tests/unit/components/Explore/IdentifiersView.test.js
- tests/unit/components/Explore/ObservationsView.test.js
Closes #888
- shows infinite loading wheel on all explore view screens and MyObservations screen
- adds tests to check for loading wheel, empty state, no internet state
- refactoring for Explore screen based on MyObservations -- uses StickyView component to animate Explore header while scrolling, uses ListHeaderComponent and ListEmptyComponent, simplifies grid item calculations in SpeciesView
> Add loading wheels to infinite scrolls in Explore

- src/sharedHelpers/fetchUserLocation.e2e-mock
Our CI e2e tests were consistently failing in late afternoon PT, even though they passed locally. Seems that was because our e2e tests were mocking the current location as San Francisco, but the Github Actions runners are set to UTC, so for that part of the day when UTC is a day in the future relative to PST, the tests were failing because they were submitting observations with dates in UTC and locations in PST. The server sets the time zone based on the coordinates, so it was interpreting that UTC date as PST, and since it was in the future, it was failing. The e2e test would then tap on the observation and expect to see ObsDetail, but since the upload failed, it landed on ObsEdit and stalled.
> Fix for failing e2e tests when UTC is tomorrow relative to PST

- package-lock.json
- package.json
- src/components/Camera/ARCamera/FrameProcessorCamera.js
- src/components/Suggestions/SuggestionsContainer.js
- src/sharedHelpers/cvModel.js
- tests/jest.setup.js
This PR adds an example usage of the function exposed from the vision-camera plugin to predict an image from disk.
package.json and -lock have a reference to the branch of the VCPlugin that exposes the function.
I have put a demo call of the function in the SuggestionsContainer. It runs on every render which is not the correct place for sure but it works every time the user changes the selected photo which is promising.
Android does not work. The error thrown is suggesting that the native side can not get the bitmap (It does work in Seek though and in the simple example app in the vision-plugin itself, so the problem might rather be the uri we have in state for the image, and can be punted to post-MVP.)
> Image recognition from local image

- e2e/signedIn.e2e.js
Needed because we added a [larger image](https://github.com/inaturalist/iNaturalistReactNative/commit/c35c2fa25eede4e8ada613b7a962e981184fda75) to the top of ObsDetails screens with no media, which sometimes pushes the comment below the fold.
> Fix e2e android comment visibility

- src/components/Camera/StandardCamera/DiscardChangesSheet.js
- src/components/LoginSignUp/ForgotPassword.js
- src/components/MediaViewer/MediaViewer.js
- src/components/MyObservations/LoginSheet.js
- src/components/ObsDetails/ActivityTab/ActivityHeader.js
- src/components/ObsDetails/DataQualityAssessment.js
- src/components/ObsDetails/ObsDetails.js
- src/components/ObsDetails/Sheets/AgreeWithIDSheet.js
- src/components/ObsDetails/Sheets/WithdrawIDSheet.js
- src/components/ObsEdit/OtherDataSection.js
- src/components/ObsEdit/Sheets/AddEvidenceSheet.js
- src/components/ObsEdit/Sheets/DeleteObservationSheet.js
- src/components/ObsEdit/Sheets/DiscardChangesSheet.js
- src/components/ObsEdit/Sheets/DiscardObservationSheet.js
- src/components/ObsEdit/Sheets/GeoprivacySheet.js
- src/components/ObsEdit/Sheets/WildStatusSheet.js
- src/components/SharedComponents/Sheets/BottomSheet.js
- src/components/SharedComponents/Sheets/RadioButtonSheet.js
- src/components/SharedComponents/Sheets/TextInputSheet.js
- src/components/SharedComponents/Sheets/TextSheet.js
- src/components/SharedComponents/Sheets/WarningSheet.js
- src/components/Suggestions/AddCommentPrompt.js
For all usages in the app of the BottomSheet component, or components derived from it, this PR removes the possibility to specify snapPoints as a prop, and replaces it with a hook to dynamically calculate them onLayout. In other words, all instances of bottom sheet will scale depending on the content to display.
This necessitated some changes in paddings at the bottom of existing bottom sheets.
> Refactor BottomSheet to always use dynamic snap points

- index.js
- package-lock.json
- package.json
Closes #976
- We can add a custom Fallback error component if we want to customize what we show to the end user. For now, this uses the built-in error boundary component and logs the stack trace.
> Replace white screen with error boundary component

- ios/Podfile.lock
- ios/iNaturalistReactNative/Info.plist
- src/components/Camera/ARCamera/ARCamera.js
- src/components/Camera/ARCamera/hooks/useModelLoaded.js
- src/components/Camera/ARCamera/hooks/usePredictions.js
- src/components/Camera/Buttons/GreenCheckmark.js
- src/components/Camera/CameraWithDevice.js
- src/components/Camera/StandardCamera/CameraNavButtons.js
- src/components/Camera/StandardCamera/CameraOptionsButtons.js
- src/components/Camera/StandardCamera/StandardCamera.js
- src/components/Camera/StandardCamera/hooks/useBackPress.js
- src/components/Camera/TabletButtons.js
- src/components/Camera/hooks/useCreateEvidence.js
- src/components/Camera/hooks/usePrepareStateForObsEdit.js
- src/components/Camera/hooks/useRotation.js
- src/components/Camera/hooks/useTakePhoto.js
- src/components/Camera/hooks/useZoom.js
- src/components/PhotoImporter/PhotoGallery.js
- src/components/SharedComponents/PermissionGateContainer.js
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/strings.ftl
- src/navigation/StackNavigators/AddObsStackNavigator.js
- tests/unit/components/Camera/ARCamera.test.js
Closes #830 
- Adds a permission gate for saving photos to library. Permission Gate appears when a user taps the checkmark on the Standard Camera or snaps a photo / taps the checkmark on the AR Camera
- Code cleanup: using shared hooks for zoom, rotation, etc. in camera library to make camera functionality easier to reason about
> Add Photo Permission Gate

- src/components/ObsDetails/ObsDetails.js
- src/components/ObsDetails/ObsDetailsHeader.js
- tests/unit/components/ObsDetails/ObsDetailsHeader.test.js
* Renamed CommunityTaxon to ObsDetailsHeader since it has more info than just the community taxon
* Made tabs stick on scroll instead of header
* Removed weird spacer element at the bottom of the activity
> Minor style fixes for ObsDetails

- ios/Podfile.lock
- src/api/messages.js
- src/components/App.js
- src/components/Explore/Header/Header.js
- src/components/Explore/IdentifiersView.js
- src/components/Explore/ObserversView.js
- src/components/ObsDetails/DetailsTab/Attribution.js
- src/components/ObsDetails/ObsDetails.js
- src/components/ObsDetails/ObsDetailsContainer.js
- src/components/ObsDetails/ObsDetailsHeader.js
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/strings.ftl
- src/realmModels/Comment.js
- src/realmModels/Identification.js
- src/realmModels/Observation.js
- src/realmModels/ObservationPhoto.js
- src/realmModels/Photo.js
- src/realmModels/Taxon.js
- src/realmModels/User.js
- src/realmModels/index.js
- src/sharedHooks/useCurrentUser.js
- src/sharedHooks/useUserMe.js
- tests/helpers/user.js
- tests/integration/ObsDetails.test.js
- tests/integration/ObsEditOffline.test.js
- tests/unit/models/Observation.test.js
* Shows notice when user or obs is opted out of Community Taxon on ObsDetails
(closes #882)
* Unifies mapApiToRealm methods around a single interface
* Ensure that the remote obs used on ObsDetail is normalized to look like a
local obs
* Ensure some tests that use signIn() have isolated Realm instances
* Update current user's obs from ObsDetails (closes #1045) 
* Fixed CC0 license display on ObsDetails (was not actually related to
updating the local copy of the obs
> Community taxon opt out notice

- src/components/SharedComponents/SearchBar.js
- src/components/Suggestions/TaxonSearch.js
Closes #914
- Search bar autofocuses when a user lands on TaxonSearch and the search input is empty
> Add autofocus prop to SearchBar

- src/components/Explore/Explore.js
- src/components/Explore/ObservationsView.js
- src/components/Explore/ObservationsViewBar.js
- src/components/MyObservations/MyObservationsContainer.js
- src/sharedHooks/index.js
- src/sharedHooks/useStoredLayout.js
Closes #1052
- creates shared useStorageLayout hook to access and write to persistent storage
> Make explore observations layout persistent

- src/components/LoginSignUp/ForgotPassword.js
- src/components/LoginSignUp/ForgotPasswordForm.js
- src/components/LoginSignUp/Header.js
- src/components/LoginSignUp/Login.js
- src/components/LoginSignUp/LoginForm.js
- src/components/LoginSignUp/LoginSignUpInputField.js
- src/components/LoginSignUp/LoginSignUpWrapper.js
- src/components/LoginSignUp/SignUp.js
- src/components/LoginSignUp/SignUpConfirmation.js
- src/components/LoginSignUp/SignUpForm.js
- src/components/LoginSignUp/hooks/useLoginState.js
- src/components/SharedComponents/ObservationsFlashList/ObsStatus.js
- src/components/Suggestions/SuggestionsContainer.js
- src/sharedHooks/useKeyboardInfo.js
Closes #940
Note: the issue seems to be coming from iOS 17 itself and how many times the keyboardWillChangeFrame event is fired. So added a few things to improve the issue here:
- let input fields maintain their own state, so the UI doesn't need to be rerendered as frequently
- textContentType='oneTimeCode' prevents the passwords bar from rendering immediately while a user is typing into the username/password fields
- hide the logo, header text, and footer text when the keyboard pops up on smaller devices, so that part of the UI doesn't jump around while a user is typing
> Prevent login screen from flickering on iOS 17

- src/components/PhotoImporter/GroupPhotoImage.js
- src/components/SharedComponents/ObservationsFlashList/ObsImagePreview.js
- src/components/SharedComponents/PhotoCount.js
- src/components/UiLibrary.js
- tests/unit/components/SharedComponents/PhotoCount/__snapshots__/PhotoCount.test.js.snap
Closes #1073
- Removes the ForeignObject component from `react-native-svg`, which didn't re-render consistently
- TextComponent is now positioned on top of the SVG below, so it renders every time FlashList re-renders
> Prevent PhotoCount from rendering with no count on scroll

- package-lock.json
- src/components/Suggestions/hooks/useOfflineSuggestions.js
This PR includes a new version of the vision-camera-plugin-inatvision after a merged PR there should fix the problem with reading images from file given a uri as input. With this PR the error of trying to `getWidth` from a null should not happen anymore. https://github.com/inaturalist/vision-camera-plugin-inatvision/pull/11
This should fix #1038 but I was not able to reproduce the wrong = error state on my devices, so I would need a review if this fixes the error seen on @kueda 's device as well.
> Image predictions uri fix

- src/components/LoginSignUp/LoginForm.js
- src/components/LoginSignUp/LoginSignUpInputField.js
- src/components/LoginSignUp/SignUpForm.js
Main required change here is `textContentType` prop in iOS.
> Allow password managers to fill in login fields

- src/components/SharedComponents/Sheets/BottomSheet.js
No matter the screen size, the bottom sheets should max out at a width of 500px and be bottom aligned and centered on the screen.
> Add max width for bottom sheet as 500 pixel

- ios/Podfile.lock
- package-lock.json
- package.json
- src/components/Camera/CameraView.js
I think this addresses #1227 for iOS.
Uses a new version of the vision-plugin that repairs the functionality of storing the predictions of the last five frames and returns only the best one. This works on iOS only currently.
Also sets the target cycle of the frame processor to be one frame per second.
So, in other words, the ARCamera UI will display the best prediction of the last five frames which on a fast device equals to the past five seconds. (On slower devices processing the frame can take longer than one second in total.)
> Multi frame smoothing repair

- ios/Podfile.lock
- package-lock.json
- package.json
- src/components/App.js
- src/components/Camera/ARCamera/FrameProcessorCamera.js
- src/components/Camera/ARCamera/hooks/usePredictions.js
- src/components/Suggestions/hooks/useOfflineSuggestions.js
- src/sharedHelpers/cvModel.ts
- tests/factories/ModelPrediction.js
- tests/integration/SuggestionsWithSyncedObs.test.js
- tests/jest.setup.js
This unifies the return types of the vision plugin callback and prediction from files on Android and iOS. So, the PR removed platform-specific handling.
Closes #1115
> Consolidate vision returns

- src/components/MyObservations/MyObservationsContainer.js
- src/components/MyObservations/hooks/useDeleteObservations.js
- src/components/ObsDetails/ObsDetails.js
- src/components/ObsDetails/ObsDetailsContainer.js
- src/components/PhotoImporter/PhotoGallery.js
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/strings.ftl
- src/sharedHelpers/logging.js
- src/sharedHelpers/util.js
The main problem here was that the API was returning deleted observations when we pulled very soon after the deletions were requested, probably due to elasticsearch syncing issues. `ttl=-1` had no effect, so I don't think it's a caching problem in the API. Since this is out of a client's hands, my imperfect solution is to make the sync operation wait at least 10 seconds after deletion finished to fetch new observations.
This also adds logic to ObsDetails so that if you land on it and the observation was deleted, it tells you and then sends you back to where you were. In theory the first change should make the second unnecessary, but there are some other situations where this could happen, e.g. if you're looking at MyObs, delete an obs on the website, and then tap that obs in the app …
> Bugfix: undead observations arose if sync happened too soon after death

- src/api/search.js
- src/sharedHooks/useTaxonSearch.js
- tests/integration/SuggestionsWithSyncedObs.test.js
- tests/integration/navigation/Suggestions.test.js
- tests/unit/components/Suggestions/TaxonSearch.test.js
Closes #1104
- Use taxa/search API instead of generic search API call, since this returns the expected results when a user has multiple common names enabled
> Show multiple common names consistently

- src/api/error.js
- src/components/Camera/ARCamera/hooks/usePredictions.js
- src/components/SharedComponents/DisplayTaxonName.js
- src/components/SharedComponents/ObservationsFlashList/ObsImage.js
- src/components/SharedComponents/TaxonResult.js
- src/realmModels/Taxon.js
- src/realmModels/index.js
- src/sharedHooks/useIconicTaxa.js
- src/sharedHooks/useTaxon.js
- tests/factories/LocalTaxon.js
- tests/helpers/render.js
- tests/integration/sharedHooks/useTaxon.test.js
- tests/unit/components/Camera/ARCamera.test.js
- tests/unit/components/SharedComponents/ObservationsFlashList/__snapshots__/ObsGridItem.test.js.snap
- tests/unit/components/SharedComponents/TaxonResult.test.js
- tests/unit/components/SharedComponents/__snapshots__/TaxonResult.test.js.snap
- tests/unit/components/Suggestions/Suggestions.test.js
- tests/unit/components/Suggestions/TaxonSearch.test.js
Several minor changes to TaxonResult, mostly focused on improving ARCamera
* Stop requesting remote taxon if local exists and was updated in the last week
* Should show a localized version of a remote taxon without needing another render to load a newly-created local taxon
* Show ActivityIndicator while attempting to load a remote taxon
* Show iconic taxon icon if loading a remote taxon fails or there is no taxon photo
* Show iconic taxon as backdrop for ObsImage whenever possible, e.g. while loading the photo or when photo can't load
Closes #1195
> Taxon result updates

- src/components/ObsDetails/DetailsTab/DetailsTab.js
- tests/unit/components/ObsDetails/DataQualityAssessment.test.js
Closes #1212
- Fixes a crash when navigating from ObsDetails to DQA with unknown taxon
- Simplifies mockObservation in DQA tests and ensures this observation is being used in tests
> Show DQA when taxon is unknown

- .github/workflows/e2e_android.yml
- .github/workflows/e2e_ios.yml
Some of our recent e2e test failures were due to services not working on staging, which took me a little bit to debug. If that happens again, this should cause e2e tests to fail in a more informative manner.
> Try to test server availability before trying e2e tests

- ios/Podfile.lock
- ios/iNaturalistReactNative.xcodeproj/project.pbxproj
- src/components/SharedComponents/DisplayTaxonName.js
- src/components/SharedComponents/ScientificName.js
- src/components/styledComponents.js
- tests/unit/components/SharedComponents/Buttons/__snapshots__/Button.dark.test.js.snap
- tests/unit/components/SharedComponents/Buttons/__snapshots__/Button.test.js.snap
- tests/unit/components/SharedComponents/Tabs/__snapshots__/Tabs.test.js.snap
- tests/unit/components/SharedComponents/Typography/__snapshots__/Heading1.test.js.snap
- tests/unit/components/SharedComponents/Typography/__snapshots__/Heading2.test.js.snap
- tests/unit/components/SharedComponents/Typography/__snapshots__/Heading3.test.js.snap
- tests/unit/components/SharedComponents/Typography/__snapshots__/Heading4.test.js.snap
- tests/unit/components/SharedComponents/Typography/__snapshots__/Heading5.test.js.snap
- tests/unit/components/SharedComponents/__snapshots__/TaxonResult.test.js.snap
Most of these are adjustments to work on #1209
* Restore Whitney Book as default font so <Text> isn't bold by default
* Refactor a function that fetches a class name to simply be a memoized string
* Simplified some italicization logic in <ScientificName>
* Fixed bug where higher rank species names were rendered as an illegible gray in ObsGridItem
Note that despite the changes to the snapshots, the actual rendered text looks identical to what's currently in main:
|Main (iPhone 14)|Branch (iPhone 15)|
|-|-|
|![main-headings](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/178fcb01-1fde-4723-9bd3-e656bc6b9413)|![branch-headings](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/ad90d25c-3def-4a72-bd82-a0a6d75ed571)| …
> Several changes to recent font updates

- .gitguardian.yml
- .gitignore
- .husky/pre-commit
- .pre-commit-config.yaml
- README.md
Adds a pre-commit hook to run GitGuardian's `ggshield` command to check new code for secrets, passwords, API keys, etc.
I tested this by
1. Hard-coding an OAuth client secret
2. Hard-coding the Android Google Maps API key
3. Hard-coding the anonymous JWT secret
It catches 1 and 2, but 3 fails because GitGuardian's [generic high entropy secret detector](https://docs.gitguardian.com/secrets-detection/secrets-detection-engine/detectors/generics/generic_high_entropy_secret) relies on assignment, and statements like `jwt.encode( claims, "bsaruceobkoraebisroaecbu89", "HS512" );` won't trigger it because there's no assignment happening (that's one of their example secrets). Since GitGuardian doesn't seem to provide a mechanism for custom detectors, the only way I can think of to prevent that …
> GitGuardian pre-commit hook

- ios/Podfile.lock
- src/components/Explore/MapView.js
- src/components/SharedComponents/Map.js
Makes the current location button on Explore zoom in to a neighborhood level instead of a backyard level.
Closes #1192
> Explore current location zoom level

- jest.config.ts
- package-lock.json
- package.json
- src/components/ObsEdit/EvidenceList.js
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/strings.ftl
- tests/unit/components/Camera/CameraContainer.test.js
- tests/unit/components/MediaViewer/MediaViewer.test.js
- tests/unit/components/Messages/Messages.test.js
- tests/unit/components/ObsEdit/ObsEdit.test.js
- tests/unit/components/ProjectDetails/ProjectDetails.test.js
- tests/unit/components/Suggestions/Suggestions.test.js
- tests/unit/components/TaxonDetails/TaxonDetails.test.js
- tests/unit/components/TaxonDetails/Taxonomy.test.js
- tests/unit/components/UserProfile/UserProfile.test.js
This PR:
- Moves Jest config out of package.json into its own file
- Adds `jest-slow-test-reporter`, which we can use to see which tests are running the slowest (and try to fix them accordingly)
- Adds `test:memory` to package.json, which lets us run a script to check for growing heap size / memory leaks in our Jest tests (we currently do seem to have a growing heap)
- Improves the test speed of a few slower tests
- Fixes accessibility issues in EvidenceList
> Jest config updates; fixes for slower tests

- ios/Podfile.lock
- src/components/Developer/Developer.js
- src/components/Developer/UiLibrary/ObsListItemDemo.js
- src/components/MyObservations/MyObservationsContainer.js
- src/components/ObsDetails/DetailsTab/DetailsTab.js
- src/components/ObsEdit/IdentificationSection.js
- src/components/ObsEdit/ObsEdit.js
- src/components/SharedComponents/ObsStatus.js
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/strings.ftl
- src/realmModels/Observation.js
- src/sharedHelpers/uploadObservation.js
- src/sharedHooks/useIconicTaxa.js
- tests/factories/LocalObservationPhoto.js
- tests/factories/LocalObservationSound.js
- tests/helpers/factoria.js
- tests/integration/MyObservations.test.js
- tests/unit/helpers/uploadObservation.test.js
This fetches a remote copy of each observation after upload to make sure the client has the freshest copy of the data immediately.
Closes #1259, but it should also address a number of related bugs, e.g. the quality grade being incorrect immediately after uploading a Casual obs.
> Show up-to-date metadata for observations immediately after upload

- ios/Podfile.lock
- src/components/AddObsModal.js
- src/components/MyObservations/MyObservationsEmpty.js
- src/components/PhotoSharing.js
- src/components/SharedComponents/Buttons/AddObsButton.js
- src/components/SharedComponents/TaxonResult.js
- src/components/Suggestions/Suggestions.js
- src/components/Suggestions/SuggestionsContainer.js
- src/components/Suggestions/TaxonSearch.js
- src/components/Suggestions/hooks/useNavigateWithTaxonSelected.js
- src/stores/createObservationFlowSlice.js
- src/stores/useStore.js
The specific crash repro'd in #1477 was due to TaxonResult getting rendered in Suggestions while that screen was in the background and lost its taxon, so a null check addressed that. Then there was a crash related to `( confidence && confidencePosition === "photo" )` resolving to a number or string literal sometimes, I think when `confidence` was 0, which evaluates as false-y. My workaround works, but we should take some care when using this pattern in React, where just adding a `0` without wrapping it in a `<Text>` component is going to cause problems.
There was still a problem with stale state, which again had to do with Suggestions being mounted in the background and a navigation-related hook it uses getting triggered when `currentObservation` changed in the Zustand state. I made it so …
> Clean up Suggestions navigation state after navigating

- src/appConstants/paths.ts
- src/components/Developer/hooks/useAppSize.ts
- src/components/MyObservations/MyObservationsContainer.js
- src/components/MyObservations/hooks/useClearGalleryPhotos.ts
- src/components/PhotoImporter/PhotoGallery.js
Create a gallery photos directory; move gallery photos out of temporary directory and into this folder; clear photos when user leaves ObsEdit flow
> Remove temporary gallery photos

- ios/Podfile.lock
- src/components/MyObservations/MyObservations.js
- src/components/SharedComponents/ScrollableWithStickyHeader.js
This also has the welcome effect of not showing jitter while the user is uploading and the hidable part of the header is partially visible (#1426).
> Stick the MyObs toolbar until user scrolls to the very top

- .eslintrc.js
- src/components/MyObservations/MyObservationsContainer.js
- src/components/MyObservations/ToolbarContainer.js
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/strings.ftl
- src/sharedHelpers/uploadObservation.js
- tests/unit/components/MyObservations/MyObservations.test.js
- tests/unit/components/MyObservations/ToolbarContainer.test.js
This is a pretty narrow solution to the problem that adds a few more things to state, including an object that stores all the errors associated with each observation, and an array that holds all the *successfully* uploaded observation UUIDs, b/c before we were only tracking how many observations were finished, i.e. observations that we tried to upload.
Closes #1544
> Track number of failed uploads

- src/components/MyObservations/MyObservationsContainer.js
- src/components/MyObservations/ToolbarContainer.js
- src/components/MyObservations/helpers/filterLocalObservationsToDelete.ts
- src/components/MyObservations/helpers/syncRemoteDeletedObservations.ts
- src/components/MyObservations/hooks/useDeleteObservations.ts
- src/components/ObsDetails/ActivityTab/ActivityHeaderContainer.js
- src/components/ObsDetails/DQAContainer.js
- src/components/ObsDetails/ObsDetailsContainer.js
- src/realmModels/LocalPreferences.js
- src/realmModels/Observation.js
- src/realmModels/index.js
- src/sharedHooks/useRemoteObservation.js
- src/stores/createDeleteObservationsSlice.ts
- src/stores/useStore.js
- tests/integration/MyObservations.test.js
- tests/unit/components/MyObservations/ToolbarContainer.test.js
- tests/unit/components/MyObservations/useDeleteObservations.test.js
Closes #1485 
- When a user lands on MyObs, their remotely deleted observations will sync automatically
- This happens before their locally deleted observations are deleted remotely
- It also happens without a user needing to press the sync button
This should eliminate errors related to a user landing on a previously deleted ObsDetails observation, since this will minimize the number of observations they can see in their observations list which have been deleted remotely.
It's still possible that a user could delete an observation remotely, have the mobile app open, and tap an observation before they navigate away from the MyObs screen, in which case they'll see the "Observation Has Been Deleted" bottom sheet on ObsDetails. However, this update means that when they close this bottom …
> Fetch remotely deleted observations automatically

- index.js
- package-lock.json
- src/api/log.ts
- src/components/App.js
- src/components/LoginSignUp/AuthenticationService.js
- src/components/SharedComponents/Buttons/AddObsButton.js
- src/sharedHelpers/userData.js
* include X-Installation-ID with most requests
* allow logged out logging
* log whether user has enabled advanced add obs btn
Note that at present, installation ID should be just that: an identifier that is unique per installation. So if two users sign in to the same installation on the same device, that's two users, one installation. If one user signs into to two separated devices, that's one user, two installations. The intent is to be able to count signed out users assuming generally only one user is using one account per installation.
> Add X-Installation-ID logging

- .eslintrc.js
- src/api/computerVision.js
- src/api/error.js
- src/components/Camera/CameraWithDevice.tsx
- src/components/Camera/hooks/useFocusTap.ts
- src/components/Camera/hooks/useTakePhoto.ts
- src/components/LoginSignUp/LoginSignUpInputField.js
- src/components/MyObservations/helpers/syncRemoteDeletedObservations.ts
- src/components/MyObservations/helpers/syncRemoteObservations.ts
- src/components/MyObservations/hooks/useUploadObservations.ts
- src/components/SharedComponents/TaxonResult.js
- src/components/Suggestions/Attribution.js
- src/components/Suggestions/Suggestions.js
- src/components/Suggestions/SuggestionsContainer.js
- src/components/Suggestions/SuggestionsEmpty.tsx
- src/components/Suggestions/SuggestionsFooter.tsx
- src/components/Suggestions/SuggestionsHeader.tsx
- src/components/Suggestions/hooks/useOnlineSuggestions.ts
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/strings.ftl
- src/sharedHelpers/resizeImage.ts
- src/sharedHooks/useUserLocation.ts
- src/stores/createExploreSlice.ts
- src/stores/createSyncObservationsSlice.ts
- src/stores/createUploadObservationsSlice.ts
- tests/integration/SuggestionsWithSyncedObs.test.js
- tests/unit/components/SharedComponents/__snapshots__/TaxonResult.test.js.snap
- tests/unit/components/Suggestions/Suggestions.test.js
This PR makes most of the changes in the #1592 suggestions enhancement PR. Specifically, it:
1. Updates the UI across all states (checkmarks, search button, help text, skip button, etc.)
2. Adds an ignore/use location button to the online state. When a user toggles this, it also toggles the scoring used (vision_score for fetches with no location parameters, and combined_score for fetches with location parameters)
3. Allows user to reload the screen when they're offline, in case they have a better internet connection available
I didn't add the button for location permission in this PR, because that's currently blocked by https://github.com/inaturalist/iNaturalistReactNative/issues/1594
> Suggestions screen UI fixes, location toggle, and offline reloading state

- src/components/Explore/Explore.js
- src/components/Explore/RootExploreContainer.js
- src/components/Explore/TaxonGridItem.tsx
- src/components/Explore/hooks/useCurrentExploreView.ts
- src/components/Explore/hooks/useCurrentMapRegion.ts
- src/components/Explore/hooks/useMapLocation.js
- src/stores/createExploreSlice.ts
- src/stores/createRootExploreSlice.ts
- src/stores/useStore.js
- tests/unit/components/Explore/TaxonGridItem.test.js
Closes #1686
As long as we have a separate RootExplore and Explore screen, we need each of these screens to maintain their own stores. Otherwise, when a user moves from RootExplore -> Explore -> any screen and then backs out to Explore -> RootExplore, they will not see a correct history of the screens with their previous states.
Before this change, when a user backed all the way out to RootExplore, they would see the RootExplore screen displaying the explore view and the relevant filters they had set on Explore, rather than on RootExplore. (So for example, if a user tapped a species, landed on TaxonDetails, then visited Explore for that species, they would back out of navigation all the way to RootExplore and see that screen filtered by the species they selected, even though their …
> Separate store for RootExplore

- ios/Podfile.lock
- src/components/Developer/UiLibrary/Misc.js
- src/components/Explore/Explore.js
- src/components/Explore/ExploreContainer.js
- src/components/Explore/Header/Header.js
- src/components/Explore/MapView.js
- src/components/Explore/Modals/ExploreFiltersModal.js
- src/components/Explore/Modals/FilterModal.tsx
- src/components/Explore/RootExploreContainer.js
- src/components/ObsEdit/IdentificationSection.js
- src/components/SharedComponents/IconicTaxonChooser.js
- src/providers/ExploreContext.tsx
- tests/unit/components/SharedComponents/IconicTaxonChooser.test.js
- tests/unit/providers/ExploreContext.test.js
The problem was the iconic_taxa param was being incorrectly set to an array... but setting it correctly involved changing the IconicTaxonChooser and the way we update Explore state when setting a taxon or setting the unknown iconic taxon filter.
* IconicTaxonChooser no longer takes a taxon or manages its own state
* Setting iconic taxon filter to Unknown is now its own action
* Unsetting a taxon can be done with the CHOOSE_TAXON action by setting taxon to null or undefined
* Omitted some extraneous params from tile requests
> Fix missing map tiles when taxon chosen on Explore

- e2e/signedIn.e2e.js
- ios/Podfile.lock
- src/components/ObsDetails/ActivityTab/ActivityItem.js
- src/components/ObsDetails/ActivityTab/ActivityTab.js
- src/components/ObsDetails/ActivityTab/FloatingButtons.js
- src/components/ObsDetails/ObsDetails.js
- src/components/ObsDetails/ObsDetailsContainer.js
- src/components/ObsDetails/Sheets/AgreeWithIDSheet.js
- src/components/ObsDetails/Sheets/SuggestIDSheet.tsx
- src/components/SharedComponents/Sheets/TextInputSheet.js
- src/components/Suggestions/hooks/useNavigateWithTaxonSelected.js
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/strings.ftl
- tests/integration/SuggestionsWithSyncedObs.test.js
- tests/unit/components/ObsDetails/ActivityItem.test.js
- tests/unit/components/ObsDetails/ActivityTab.test.js
This flow is mentioned in [#1592](https://github.com/inaturalist/iNaturalistReactNative/issues/1592). It does a couple things:
- Adds a Suggest ID bottom sheet when a user returns from ObsDetails -> Suggestions -> ObsDetails
- Allows a user to add remarks, confirm their suggestion, or cancel
- Fixes a bug where users could not confirm or close out of the "Add Optional Comment" bottom sheet when tapping agree and seeing the agreement bottom sheet
> Show bottom sheet before confirming suggested ID in ObsDetails -> Suggestions flow

- src/sharedHooks/useLocalObservations.js
Filter realm objects within listener (instead of listening to a filtered list) to show correct number of unsynced observations.
Closes #1654
Closes [#1631](https://github.com/inaturalist/iNaturalistReactNative/issues/1631)
> Show correct number of observations to upload after deletion

- src/components/ObsDetails/DQAContainer.js
- src/components/ObsDetails/DataQualityAssessment.js
- tests/integration/DataQualityAssesment/DataQualityAssessment.test.js
- tests/unit/components/ObsDetails/DataQualityAssessment.test.js
Mostly just cleanup, with the additional feature of updating the DQA header when quality grade changes. I suspect the original error reported in #1504 was happening only when downvoting the `date` or `location` metrics for observations without date or location attributes, which *should* have returned an error from the API but wasn't. That specific error will be resolved by https://github.com/inaturalist/inaturalist/pull/4150, which returns an error status when you do that.
Closes #1504
> DQA voting status

- src/components/Camera/Buttons/GreenCheckmark.js
- src/components/Camera/StandardCamera/CameraNavButtons.js
- src/components/Camera/StandardCamera/PhotoPreview.tsx
- src/components/Camera/StandardCamera/StandardCamera.js
- src/components/SharedComponents/MediaNavButtons.js
Narrow solution that disables the confirmation button while a new photo is being processed.
Closes #1690
> Photos lost from StandardCamera when confirming before processed

- src/components/SharedComponents/Buttons/Button.tsx
- src/components/SharedComponents/TaxonResult.js
- src/components/Suggestions/Suggestion.js
- src/components/TaxonDetails/TaxonDetails.js
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/strings.ftl
- tests/integration/navigation/TaxonDetails.test.js
- tests/jest.setup.js
- tests/unit/components/TaxonDetails/TaxonDetails.test.js
Closes #1742
- Adds a select a taxon button to TaxonDetails when coming from Suggestions
- Navigates user to ObsDetails with Suggest ID bottom sheet open to selected taxon when previous screen was ObsDetails
- Navigates user to ObsEdit with identification set to selected taxon when coming from any other screen
- Adds test coverage for these changes
> Add Select Taxon button on TaxonDetails

- src/components/MyObservations/hooks/useClearSyncedPhotosForUpload.ts
- src/sharedHelpers/removeSyncedFilesFromDirectory.ts
Closes #1741. That hook is a little hair-raising (deletes all photos *except* the ones you want to keep, runs pretty much every single time MyObs renders), so I might spend a bit of time trying to refactor and at least get it to run less frequently.
> Restore removal of synced photos

- .eslintrc.js
- e2e/signedIn.e2e.js
- src/appConstants/e2e.ts
- src/components/ObsEdit/ObsEdit.js
- src/components/SharedComponents/ScrollableWithStickyHeader.js
- src/sharedHelpers/geolocationWrapper.e2e-mock
- src/sharedHelpers/geolocationWrapper.ts
- src/sharedHooks/useWatchPosition.ts
Re-implements this fix we've needed to make several times to ensure our e2e tests always use a location in the UTC time zone in which they run.
> e2e mock for Geolocation.watchPosition to deflake tests

- index.js
- src/api/log.ts
- src/components/LoginSignUp/AuthenticationService.js
- src/components/MyObservations/hooks/useSyncObservations.ts
- src/components/MyObservations/hooks/useUploadObservations.ts
- src/components/hooks/useFreshInstall.js
- src/sharedHelpers/persistedInstallationId.ts
- src/sharedHelpers/userData.ts
- src/stores/useStore.js
Closes #1738 
- Clears all directories containing user generated data within the Documents Directory
- Deletes the MMKV instance wrapping the zustand store
> Clear user data on sign out

- src/sharedHooks/useInfiniteObservationsScroll.js
- Make sure query is only fetched if there's a logged in user
> Bugfix for useInfiniteObservationsScroll

- src/components/Suggestions/Suggestions.js
- src/components/Suggestions/SuggestionsContainer.tsx
Close #1806 - taxon suggestion - when the api does not provide a common ancestor and there is no species suggestion with a combined score higher than .78 - show a special message (we're not confident...)
> Notice for no top suggestion

- src/components/ObsDetails/ObsDetailsHeader.tsx
- src/components/ObsEdit/Header.js
- src/components/ObsEdit/helpers/navigateToObsEdit.ts
- src/components/SharedComponents/ObservationsFlashList/MyObservationsPressable.js
- src/navigation/StackNavigators/SharedStackScreens.js
- src/stores/createObservationFlowSlice.js
Closes #1890
We can't use the swipe gesture to go back on ObsEdit in certain situations, because ObsEdit is part of the NoBottomTab stack navigator, but there are a few scenarios where we're landing on ObsEdit from the TabStackNavigator. In these cases, swiping back in the stack will take a user back to the previous NoBottomTab screen, rather than the other stack navigator where a user came from.
So instead, we're resetting the navigator when a user is coming from MyObservations/ObsDetail, and swipe will not work on ObsEdit in these scenarios.
> Reset navigator when navigating to ObsEdit from TabStack

- ios/Podfile.lock
- src/components/MyObservations/hooks/useSyncObservations.ts
- src/components/ObsEdit/BottomButtons.js
- src/components/ObsEdit/ObsEdit.js
- src/components/ObsEdit/Sheets/DeleteObservationSheet.js
- src/sharedHelpers/shouldFetchObservationLocation.ts
- src/sharedHooks/useWatchPosition.ts
Closes #1874
- Exposes `stopWatch` callback so we can stop location fetching from any component with a subscription id
- Removes some unnecessary `useEffects` in ObsEdit
- Removes accuracy check from `shouldFetchObservationLocation` since `useWatchPosition` already handles that
> Stop location fetch when navigating to location picker

- src/components/Explore/SearchScreens/ExploreTaxonSearch.js
- src/components/ObsEdit/BottomButtons.js
- src/components/ObsEdit/IdentificationSection.js
- src/components/ObsEdit/ObsEdit.js
- src/components/Suggestions/Suggestion.js
- src/components/Suggestions/Suggestions.js
- src/components/Suggestions/SuggestionsLoading.tsx
- src/components/Suggestions/TaxonSearch.js
- src/components/Suggestions/hooks/useOnlineSuggestions.ts
- src/sharedHooks/useTaxon.js
- src/sharedHooks/useTaxonSearch.js
- tests/unit/components/ObsEdit/IdentificationSection.test.js
- tests/unit/components/Suggestions/TaxonSearch.test.js
Closes #1876 
A few changes here:
- If a taxon in `useTaxon` has already been synced to realm but is missing a common name or default photo, we should fetch remotely again
- We don't need to use individual `useTaxon` fetches in Suggestions at all, since we're already getting those taxon details from the online suggestions API call. Instead, we can store taxa in realm when online suggestions results are returned
- We can fetch less data in TaxonSearch and also store those taxa in realm. This isn't necessary for this issue, but it seemed strange to treat TaxonSearch results differently than we're treating online suggestion results
- Minor code cleanup in IdentificationSection and making sure we're not fetching a remote result from `useTaxon` there
> Load suggestion photo/common name even if previously saved to realm

- src/components/Camera/CameraContainer.tsx
- src/components/TaxonDetails/TaxonDetails.js
- src/components/TaxonDetails/Wikipedia.js
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/strings.ftl
- tests/unit/components/TaxonDetails/TaxonDetails.test.js
It was being hidden for signed out users. Also refactors tests and sends the user back when they try to access a camera screen on a device with no camera.
Closes #1917
> Select taxon button always visible from Suggestions

- src/components/MyObservations/MyObservationsContainer.js
- src/components/MyObservations/hooks/useSyncObservations.ts
- src/components/MyObservations/hooks/useUploadObservations.ts
- src/stores/createSyncObservationsSlice.ts
- src/stores/createUploadObservationsSlice.ts
- tests/integration/MyObservations.test.js
- tests/unit/components/MyObservations/useSyncObservations.test.js
* Fix previous state in which it was never really allowed to sleep again after upload finished
* Rename `uploadObservations` to `startUploadObservations` to accurately describe what it does
* Minor improvements in ts typing
> Ensure device stays awake during uploading and can sleep after

- src/components/ObsEdit/DatePicker.js
- src/sharedHelpers/dateAndTime.js
- tests/unit/components/ObsEdit/DatePicker.test.js
Closes #1920
- Removes seconds from date display, since a user can't set seconds in the native DatePicker
- Updates date displayed formatting to be closer to the Figma designs
> Formatting in DatePicker, ObsEdit

- ios/Podfile.lock
- package-lock.json
- package.json
Fixes a crash when saving an observation with a photo but without location permission.
Close #1866
> Update react-native-exif-reader version

- src/realmModels/ObservationSound.js
- src/realmModels/Sound.js
This just submits the ObservationSound UUID on creation to prevent duplicate sound creation.
Closes #1068
> Submit local ObservationSound UUID when creating observation

- src/components/Explore/Explore.js
- src/components/Explore/ExploreContainer.js
- src/components/Explore/ExploreFlashList.js
- src/components/Explore/Header/ExploreHeader.js
- src/components/Explore/Header/ExploreHeaderCount.js
- src/components/Explore/IdentifiersView.js
- src/components/Explore/ObservationsView.js
- src/components/Explore/ObserversView.js
- src/components/Explore/RootExploreContainer.js
- src/components/Explore/SpeciesView.js
- src/components/Explore/hooks/useExploreHeaderCount.js
- src/components/Explore/hooks/useInfiniteExploreScroll.js
- src/components/MyObservations/MyObservations.js
- src/components/SharedComponents/ObservationsFlashList/ObservationsFlashList.js
- src/providers/ExploreContext.tsx
- src/realmModels/Taxon.js
- src/realmModels/User.ts
- src/sharedHooks/useInfiniteScroll.js
- tests/integration/navigation/Explore.test.js
- tests/unit/components/Explore/IdentifiersView.test.js
- tests/unit/components/Explore/ObservationsView.test.js
Closes #1918
- Hides loading wheel in dark gray header unless data is actually fetching
- Shows loading wheel within explore view if data is loading
- Speeds up query response times by removing `return_bounds` as a default parameter in each explore view
- Adds `enabled` key to make sure we're not fetching data preemptively (say, fetching worldwide data before a user has given location permissions for nearby data)
> Fixes for explore loading state after permissions granted

- src/components/MyObservations/MyObservations.js
- src/components/MyObservations/MyObservationsContainer.js
- src/components/ObsDetails/ObsDetailsHeader.tsx
- src/components/ObsEdit/BottomButtons.js
- src/components/ObsEdit/helpers/navigateToObsEdit.ts
- src/components/SharedComponents/ObservationsFlashList/MyObservationsPressable.js
- src/components/SharedComponents/ObservationsFlashList/ObservationsFlashList.js
- src/components/SharedComponents/ScrollableWithStickyHeader.js
- src/stores/createMyObsSlice.ts
- src/stores/useStore.js
Symptom: when you scroll MyObs, tap an unsynced obs to enter ObsEdit, then go back, MyObs is always scrolled back to the top.
Diagnosis: entering ObsEdit requires opening a parallel stack navigator to the one that contains MyObs, which means the MyObs screen gets destroyed and it loses its scroll position.
Treatment: the ideal treatment would be to not use parallel stack navigators, but since we don't have a way to do that *and* ditch the bottom tabs for certain screens, my approach here was to store the scroll offset in Zustand when we navigate to ObsEdit, and when we return to MyObs we scroll the list to that position. We do *not* want this behavior after creating an observation, b/c we want the newly-created obs to be visible at the top of the list.
Questions for review:
* Feels real …
> Preserve MyObs scroll position

- src/components/ObsDetails/ActivityTab/ActivityItem.js
- src/components/ObsDetails/ObsDetails.js
- src/components/ObsDetails/ObsDetailsContainer.js
- src/components/ObsDetails/Sheets/AgreeWithIDSheet.js
- src/components/ObsDetails/Sheets/PotentialDisagreementSheet.js
- src/components/ObsDetails/Sheets/SuggestIDSheet.tsx
- src/components/SharedComponents/DisplayTaxon.js
- src/components/SharedComponents/Sheets/BottomSheet.js
- src/components/SharedComponents/Sheets/RadioButtonSheet.tsx
- src/components/Suggestions/hooks/useNavigateWithTaxonSelected.ts
- src/components/TaxonDetails/TaxonDetails.js
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/strings.ftl
- src/sharedHelpers/taxon.js
- src/sharedHooks/useTaxon.js
- tests/unit/components/ObsDetails/ObsDetails.test.js
* separates ident body editing into its own state and UI
* stop adding an entire Realm object to nav params, where it gets out of date and causes access bugs
* fixes bug where accessing ObsDetails from MyObs can cause you to return there when returning from TaxonDetails via Explore
* separates BottomSheet handleClose callback so it can respond differently to the sheet closing and the user intentionally closing the sheet
* Suggest ID and Agree bottom sheets both have buttons of equal width with a single primary action
* Disagree sheet prompt refers to the taxon being disagreed with, not the ident taxon
* save taxon to local db when viewed on TaxonDetails
* minor refactors for readability
Closes #2003
> fix: ident bodies should not get set by obs descriptions

- src/components/LocationPicker/CrosshairCircle.js
- src/components/LocationPicker/Footer.js
- src/components/LocationPicker/LocationPicker.js
- src/components/LocationPicker/LocationPickerContainer.js
- src/components/ObsEdit/BottomButtons.js
- src/components/ObsEdit/EvidenceSectionContainer.js
- src/components/ObsEdit/ObsEdit.js
- src/components/ObsEdit/Sheets/ImpreciseLocationSheet.js
- src/components/SharedComponents/Map/Map.tsx
closes #1877
- the main thing stopping the stutter here is that we switched from passing in `region` to the map and instead started passing in an `initialRegion`, which means the map is responsible for its own region state instead of trying to keep up with panning/zooming.
- that means we also need to use the `animateToRegion` method when a user types in a place name and selects a place search result -- this is a way to set the map without using `region`
- otherwise, tried to make LocationPicker a little easier to read and removed some unnecessary `useEffects`
> Remove stutter when scrolling LocationPicker

- src/components/App.js
- src/components/Explore/hooks/useInfiniteExploreScroll.js
- src/components/MyObservations/Announcements.js
- src/components/UserProfile/UserProfile.js
- src/navigation/BottomTabNavigator/NotificationsIconContainer.js
- src/sharedHelpers/logging.js
- src/sharedHooks/index.js
- src/sharedHooks/useAuthenticatedInfiniteQuery.ts
- src/sharedHooks/useIconicTaxa.ts
- src/sharedHooks/useInfiniteNotificationsScroll.js
- src/sharedHooks/useInfiniteObservationsScroll.js
- src/sharedHooks/useInfiniteScroll.js
- src/sharedHooks/useObservationsUpdates.js
- src/sharedHooks/useUserMe.js
Addresses part of #1847
This doesn't solve the original problem where uploads fail, but it addresses the issue with React Query attempting endless retries without being online.
- Uses the `onlineManager` event listener in React Query to listen for whether the app is online or offline
- Refactors `useInfiniteQuery` into `useAuthenticatedInfiniteQuery` to make sure we're attempting retries uniformly across the app
- Removes checks for network connectivity from the `enabled` option in various individual queries, since we're instead handling that globally
> Set online/offline status via event listener in React Query

- package-lock.json
- package.json
- src/sharedHelpers/parseExif.js
Since timezone conversion is already happening on the native side of things, we don't need to also convert date to a user's local timezone in iNaturalistReactNative. Instead, we can use the GMT date returned from the (fixed) `react-native-exif-reader`.
Closes #1516
> Update exif-reader library

- src/components/Camera/AICamera/AICamera.js
- src/components/Camera/AICamera/AICameraButtons.tsx
- src/components/Camera/Buttons/Zoom.tsx
- src/components/Camera/CameraView.tsx
- src/components/Camera/StandardCamera/CameraOptionsButtons.js
- src/components/Camera/StandardCamera/StandardCamera.js
- src/components/Camera/TabletButtons.tsx
- src/components/Camera/hooks/useZoom.ts
Closes #1984
Closes #2053
- Show zoom button text when using pinch-to-zoom
- Set 3x zoom to a similar magnification level as the native camera app, rather than the maximum zoom level we use for pinch-to-zoom
> Fixes for camera zoom

- src/components/Camera/hooks/usePrepareStoreAndNavigate.js
> Fix: don't show EvidenceList loading wheel if save photo permission denied

- src/components/MediaViewer/CustomImageZoom.js
- src/components/MediaViewer/MainMediaDisplay.js
I think this helps with #1882, but I don't think it fixes it. I think I'm out of ideas about a final fix b/c I'm not convinced the problem is really re-rendering.
FWIW, I replaced an object prop that changed on every render to a string whose value will not change when you are zooming or panning the image, which should cut down on some re-rendering.
> Try to minimize re-renders for CustomImageZoom

- src/components/Camera/AICamera/AICamera.js
- src/components/Camera/AICamera/FrameProcessorCamera.js
- src/components/Camera/CameraView.tsx
- src/components/Camera/hooks/useTakePhoto.ts
This freezes the preview immediately after taking a photo. There is a delay between button press and freeze now, don't know if this is good enough.
Edit: The delay is only on Android because on iOS we set the camera to inactive just before taking the photo. On Android this errors out with the message that the camera is inactive and can't be used to take a photo. This is an inconsistency in the camera library and we would need to keep an eye on whether this function breaks on camera updates.
> Set AI camera inactive immediately after taking photo

- src/components/App.js
- src/components/hooks/useTaxonCommonNames.ts
Closes #1958
When user opens the app, check for location permissions. If they granted permission, fetch the 500 taxon closest to their location. If not, fetch the 500 most observed taxon across the globe.
Store taxon names and common names in Realm if they're not already there or if they're out of date.
> Fetch taxon common names

- src/components/Developer/Developer.js
- src/components/SharedComponents/Buttons/BackButton.js
This makes it possible to see what we'll need to work on to support RTL. When a user toggles this button in debug mode, the app will change into either RTL or LTR and restart.
Until we have translations, we should ignore the text alignment since it's likely this will be detected automatically if there are Hebrew or Arabic characters.
Also reverses the back arrow direction for RTL.
> Add toggle button for RTL/LTR on debug screen

- src/components/Developer/UiLibrary/Misc.js
- src/components/Explore/ExploreFlashList.js
- src/components/Explore/SearchScreens/ExploreLocationSearch.js
- src/components/Explore/SearchScreens/ExploreProjectSearch.js
- src/components/Explore/SearchScreens/ExploreSearchHeader.tsx
- src/components/Explore/SearchScreens/ExploreTaxonSearch.js
- src/components/Explore/SearchScreens/ExploreUserSearch.js
- src/components/Explore/SpeciesView.js
- src/components/Explore/TaxonGridItem.tsx
- src/components/Notifications/NotificationsList.js
- src/components/PhotoImporter/GroupPhotos.js
- src/components/SharedComponents/CustomFlashList.tsx
- src/components/SharedComponents/ObservationsFlashList/ObsItem.js
- src/components/SharedComponents/ObservationsFlashList/ObservationsFlashList.js
- src/components/SharedComponents/PhotoCount.js
- src/components/SharedComponents/index.js
- src/sharedHooks/index.js
- src/sharedHooks/useGridLayout.ts
- tests/unit/components/SharedComponents/PhotoCount/PhotoCount.test.js
- tests/unit/components/SharedComponents/PhotoCount/__snapshots__/PhotoCount.test.js.snap
Closes #2144
- Uses `CustomFlashList` component to disable auto layout and remove the unexpected blank space in grid view while user is viewing a RTL language
- Standardizes the way we calculate grid item sizes across the app (GroupPhotos, Explore Observations GridView, Explore SpeciesView, MyObservations GridView, etc.) via a `useGridLayout` hook
- Standardizes the Explore search screen header and uses `BackButton` within that header to automatically flip back arrow into RTL mode
- Fixes PhotoCount rendering in RTL mode & removes unused props
> Support FlashList in RTL mode

- src/components/TaxonDetails/Wikipedia.js
> fix: hide Wikipedia button if server provides no Wikipedia URL

- src/components/Explore/SearchScreens/ExploreLocationSearch.js
- src/components/Explore/SearchScreens/ExploreProjectSearch.js
- src/components/SharedComponents/TaxaList/TaxaList.tsx
Closes #2086
- When we're using a FlatList and a SearchBar, make sure items in the FlatList all appear above the keyboard
> Show list items above keyboard

- src/components/MyObservations/MyObservationsEmpty.js
- src/components/Projects/Projects.tsx
- src/components/SharedComponents/FlashList/FlashListEmptyWrapper.tsx
Closes #2107
The main issue wasn't happening anymore and was probably fixed by https://github.com/inaturalist/iNaturalistReactNative/pull/2185. This fixes the second issue of making the empty project results screen match what's in Figma.
> Match projects empty button width to Figma

- .github/workflows/crowdin-pull.yml
- .github/workflows/crowdin-push.yml
- .github/workflows/crowdin.yml
- crowdin.yml
- src/components/TaxonDetails/Wikipedia.js
- src/i18n/i18ncli.js
- src/i18n/initI18next.js
- src/i18n/l10n/af.ftl
- src/i18n/l10n/af.ftl.json
- src/i18n/l10n/ar.ftl
- src/i18n/l10n/ar.ftl.json
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/loadTranslations.js
- src/i18n/strings.ftl
More complicated than maybe it needed to be, but this accomplishes a few things
* strings.ftl gets pushed to Crowdin when it changes
* translations get pulled from Crowdin every day and a PR should get made if there are changes
* FTL validation and normalization happens in the action and will *prevent* a PR from being created; we may want to change that if we find ourselves ignoring the failed action
* Right now only Arabic and Afrikaans are enabled for this file. I'll enable the rest when I'm ready to deal with all the questions from translators
Some details for future reference:
* Crowdin locale names don't match iNat locale names, or at least I was not able to find a way to get their Github Action and CLI to perform this mapping, so I ended up doing it in our out i18ncli script (will …
> Sync with Crowdin

- .github/workflows/crowdin-pull.yml
- src/i18n/i18ncli.js
- src/i18n/l10n/af.ftl.json
- src/i18n/l10n/ar.ftl.json
- src/i18n/l10n/en.ftl.json
- src/i18n/l10n/es-MX.ftl.json
- src/i18n/l10n/es.ftl.json
- src/i18n/l10n/ru.ftl.json
By default, the Crowdin action was pushing changes to the git branch even if it wasn't making a PR, which was messing up the state of the repo before we ran our normalization script, resulting in some files / changes getting omitted. This skips that push and allows our scripts to run on the dirty repo as intended.
Also modified the FTL-to-JSON processing to omit comments, which will slim down those files a bit.
> fix: prevent git push after Crowdin pull

- src/components/LoginSignUp/LoginForm.js
- src/components/ProjectDetails/ProjectDetailsContainer.js
- tests/helpers/render.js
- tests/unit/components/ProjectDetails/ProjectDetails.test.js
Closes #2115
- If a user is logged out and tries to join a project, they'll navigate to the login flow
- If they log in successfully, they'll be returned to project details to try to join again
- For logged in users, instead of using a `useEffect` and a React Query refetch, we're invalidating the query key to automatically refetch the current user's latest project join/leave status
> Navigate logged out users from join project > login screen

- src/components/MyObservations/MyObservations.js
- src/components/MyObservations/MyObservationsContainer.js
- src/components/MyObservations/hooks/useSyncObservations.ts
- src/realmModels/Observation.js
- src/sharedHooks/useInfiniteObservationsScroll.js
- src/sharedHooks/useLocalObservations.js
Closes #2033 
Kinda finicky. Hopefully fixed a couple things here:
- Local deletions should now be working correctly after an observation was successfully deleted remotely
- Activity indicator should show at correct time: 1) when a user first logs in and remote observations are fetching and 2) not after the final observation has been deleted from an account
- Empty screen should show immediately after the final observation has been deleted from an account
> Show empty MyObs screen after deleting last observation in account

- src/components/Explore/Modals/FilterModal.tsx
- src/components/Explore/SearchScreens/ExploreSearchHeader.tsx
Closes #2130
- When text sizes are large and screen is small, explore filters header and explore search headers wrap text into two lines
- Reset button is given a smaller maxFontSizeMultiplier value so text stays one one line (at least in English)
This prevents header text from either running off the screen and hiding the reset button (FilterModal) or overlapping the reset button so it can't be tapped (ExploreSearchHeader)
> Prevent explore filters headers from overlapping reset button

- src/components/ProjectDetails/ProjectDetails.js
- src/components/ProjectDetails/ProjectDetailsContainer.js
- src/components/ProjectDetails/ProjectRequirements.tsx
- src/components/ProjectList/ProjectListItem.tsx
- src/components/Projects/helpers/displayDates.ts
- src/components/Projects/hooks/useInfiniteProjectsScroll.ts
- tests/unit/components/ProjectDetails/ProjectDetails.test.js
- tests/unit/components/Projects/Projects.test.js
Closes #2117 
- On Projects and Project Details, show date ranges instead of project type when project is an umbrella or collection project and has date ranges in the project rules
> Show date ranges as subtitle for collection/umbrella projects

- src/components/Explore/ObservationsView.js
- src/components/Identify/Identify.js
- src/components/MyObservations/MyObservations.js
- src/components/ObservationsFlashList/ObsItem.js
- src/components/ObservationsFlashList/ObsPressable.tsx
- src/components/ObservationsFlashList/ObservationsFlashList.js
- tests/integration/navigation/Explore.test.js
Rapid taps on an observation could open ObsDetails multiple times for the same observation. This uses a key that is unique to the observation *and* the obs list that contains it to prevent this from happening.
Closes #2204
Closes #2216
> fix: prevent multiple obs details from opening

- package-lock.json
- package.json
- src/components/Camera/AICamera/AICamera.js
- src/components/Camera/AICamera/AICameraButtons.tsx
- src/components/Camera/AICamera/AIDebugButton.js
- src/components/Camera/AICamera/FrameProcessorCamera.js
- src/components/Camera/AICamera/SliderControl.tsx
- src/components/Camera/AICamera/hooks/usePredictions.ts
This adds an update to the computer vision plugin allowing to exclude lower scores during the taxonomy rollup phase. The threshold number is customizable as an option to the frame processor. A number of 0.01 means all nodes with a cv score lower than that are excluded from calculating the top predictions. Thereby saving resources on computing those.
Currently, the threshold defaults to 0.0, i.e. no nodes are filtered out, and so, this PR should introduce no visible changes outside debug mode. In debug mode you can change the taxonomy cutoff threshold value around a bit for exploration of this feature.
> Optional computer vision speedup using a taxonomy cutoff threshold

- e2e/aiCamera.e2e.js
- e2e/helpers.js
Operating under the theory that one potential reason for flakiness is that finding *a* suggestion finds the temporary one from the camera, then it disappears, then the test fails when it tries to tap on that disappeared element.
> test: wait for OTHER SUGGESTIONS in aicamera test

- src/components/Notifications/NotificationsListItem.js
- src/components/ObsDetails/ActivityTab/ActivityTab.js
- src/components/ObsDetails/ObsDetails.js
- src/components/ObsDetails/ObsDetailsContainer.js
* prevent ObsDetail from re-scrolling to an activity item after returning from
TaxonDetails (closes #2232)
* scroll far enough down ObsDetail to show the whole activity item the user
wants to see, even on small screens (closes #2233)
* scroll all the way to the bottom after creating a new comment or ID
(closes #2231)
> fix: scroll to activity item once

- src/components/Explore/MapView.tsx
- src/components/LocationPicker/LocationPicker.js
- src/components/SharedComponents/Map/Map.tsx
This was causing location to be fetched even in situations where there was no need, like ObsDetails and TaxonDetails, which was a bit creepy. This requires us to explicitly turn it on, which I've done for Explore and the LocationPicker.
Closes #2260
> fix: prevent maps from showing user location by default

- index.js
- src/api/log.ts
- src/components/LoginSignUp/AuthenticationService.ts
- src/components/MyObservations/MyObservations.js
- src/sharedHelpers/installData.ts
- src/sharedHelpers/persistedInstallationId.ts
* Rename the separate MMKV store we were using to store the installation ID to
indicate that it stores data related to the installation, not the user
* Use that MMKV to store whether or not this installation has shown the
onboarding. We don't want to re-show the onboarding to people after they
sign out
> fix: only show onboarding once per install

- src/components/Explore/SearchScreens/ExploreLocationSearch.js
- src/components/LocationPicker/LocationPickerContainer.js
- src/components/ObsEdit/ObsEdit.js
- src/components/SharedComponents/Map/CurrentLocationButton.tsx
- src/components/SharedComponents/Map/Map.tsx
- src/components/SharedComponents/PermissionGateContainer.tsx
- src/realmModels/types.d.ts
- src/sharedHelpers/shouldFetchObservationLocation.ts
- src/sharedHooks/useLocationPermission.tsx
- tests/integration/ObsEditOffline.test.js
* allow user to edit obs location even if location permission denied
* zoom location picker out to a global level if editing location for an obs with no coordinates
* stop showing sound recorder or any children of a permission gate if permission denied
* show permission gate if permission denied
Closes #2319
> fix: edit location without location permission

- src/components/Explore/Explore.js
- src/components/Explore/ExploreContainer.js
- src/components/Explore/Header/ExploreHeader.js
- src/components/Explore/Modals/ExploreLocationSearchModal.tsx
- src/components/Explore/RootExploreContainer.js
- src/components/Explore/SearchScreens/ExploreLocationSearch.js
- src/components/SharedComponents/PermissionGateContainer.tsx
- src/sharedHooks/useLocationPermission.tsx
Much of the problem described in #2318 was handled in #2418 (mostly the part about nothing happening), but there remained a problem after the user went to Settings and granted permission: when they returned, the permission gate was still visible, and closing it did nothing. This PR makes it so the permission gate closes if the app is foregrounded and the permission gate detects that permission was granted. In iOS, this also results in Explore filtering by nearby as the user intended. In Android that might happen sometimes, but usually the user needs to tap NEARBY again.
Closes #2318
> fix: explore nearby after permission granted in Settings

- src/components/Suggestions/Suggestions.js
Closes #2272
Another `useMemo` vs. `useCallback` error, like the one originally tracked down while debugging test errors in https://github.com/inaturalist/iNaturalistReactNative/pull/2280. 
`useMemo` prevents the SuggestionsHeader from rerendering when a photo is selected, while `useCallback` likely creates a lot of extra rerenders when a photo is selected.
> Prevent Suggestions photo scroll from resetting scroll placement on selection

- src/components/ObsDetails/FaveButton.js
- src/components/ObsDetails/ObsDetailsHeader.tsx
- src/components/SharedComponents/OverlayHeader.tsx
* Allow taps to pass through the obs details header to the fave button
* Stop rendering a full-height fave button on tablets
Closes #2177
> fix: allow faving on tablets

- src/components/Explore/MapView.tsx
- src/components/SharedComponents/Map/Map.tsx
This is a fix for issue #2432 Explore rapidly alternates between different maps.
The underlying problem is that on Android, the Explore map view is infinitely re-rendered. The `onRegionChangeComplete` callback should only be called at the end of a pan or zoom user interaction. On Android, it is also called when the map is first displayed, before any user interaction.
This seems to be a known issue, as there is a comment and a function in the codebase to handle it:
```
const handleRegionChangeComplete = async ( newRegion, boundaries ) => {
// Seems to be a bug in react-native-maps where
// onRegionChangeComplete fires once on initial load before the
// region actually changes, so we're just ignoring that update
// here
if ( Platform.OS === "android" && Math.round( newRegion.latitude ) === …
```
> fix for infinite re-rendering in Explore map view on Android

- .bundle/config
- .github/workflows/crowdin-pull.yml
- .gitignore
The setup-ruby action was choking on the explicit Docker container image we were using in crowdin-pull. The only reason we were doing that was to run everything as root, b/c the crowdin action adds files owned by root, leading to permissions errors when we later move things around. This PR just uses `sudo chown` (which apparently works?!) to get the same effect.
> fix: skip container to allow Ruby setup in crowdin-pull action

- ios/Podfile.lock
- package-lock.json
- package.json
Technically this means we could now support geomodel on iOS. We need additional work though to add the model to the app and connect to the frame processor.
> Update cv plugin

- src/components/MyObservations/MyObservations.js
- src/components/MyObservations/MyObservationsContainer.js
- src/components/MyObservations/hooks/useSyncObservations.ts
- src/components/ObservationsFlashList/CustomRefreshControl.tsx
- src/components/ObservationsFlashList/ObservationsFlashList.js
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/strings.ftl
- tests/integration/MyObservations.test.js
Closes #2332
- Uses built-in React Native `RefreshControl` component to add pull-to-refresh functionality on MyObservations
- Pull-to-refresh triggers a manual sync, but skips the upload step that a manual tap of the sync button would trigger
> Add pull-to-refresh on MyObservations list and grid

- src/components/MyObservations/MyObservations.js
- src/components/MyObservations/MyObservationsContainer.js
- src/components/MyObservations/hooks/useSyncObservations.ts
- src/components/ObservationsFlashList/ObservationsFlashList.js
Original code was also showing pull-to-refresh when a user tapped the sync button to upload. This fix shows the refreshing UI when a user pulls down, and it hides the refreshing UI when the manual sync has completed.
> Fix: show pull-to-refresh UI only during a pull-to-refresh

- src/components/ObsDetails/ObsDetails.js
- src/components/ObsDetails/ObsDetailsHeader.tsx
- src/components/SharedComponents/OverlayHeader.tsx
- src/components/TaxonDetails/TaxonDetails.js
- src/components/TaxonDetails/TaxonDetailsHeader.tsx
Addresses part of #2331
- This uses fixed headers on ObsDetails and TaxonDetails, and it inverts the colors of the header when a user scrolls down to a certain y value on the screen
I spent about a day looking into ways that we can make both the fixed header and the tab bar stick to the top of the screen in ObsDetails, but the furthest I got was a hacky solution that worked on iPhone 15 Pro but not an iPhone SE. React Native components are designed to only allow for one sticky header at a time, so we'll need some custom code here. I'm going to unassign myself in case someone else wants to pick up the rest of this issue.
> Use fixed headers on ObsDetails/TaxonDetails which invert colors on scroll

- src/components/Suggestions/hooks/useOnlineSuggestions.ts
- src/components/hooks/useTaxonCommonNames.ts
- src/realmModels/Taxon.js
- src/realmModels/index.ts
- src/sharedHelpers/taxon.js
- src/sharedHooks/useIconicTaxa.ts
- src/sharedHooks/useTaxon.js
- src/sharedHooks/useTaxonSearch.ts
Trying again with a migration and a totally separate field. Locally it worked for me, but I also wasn't able to replicate the prior release-only bug, so I'm curious if you can still see that here, @jtklein. If so, I think we just have to abandon the full-text index.
> feat: use full-text index on new _searchableName field

- src/components/Explore/Explore.js
- src/components/Explore/hooks/useInfiniteExploreScroll.js
- src/components/SharedComponents/Sheets/BottomSheet.tsx
- src/components/SharedComponents/Sheets/RadioButtonSheet.tsx
- src/sharedHooks/useFontScale.ts
- tests/integration/Explore.test.js
URL params got removed from the query key as a part of pull-to-refresh, but that's how changes to filters were triggering a new request. This restores that behavior, adds a test to ensure changes to filters call the API again, and fixes the prior test of pull to refresh which was not testing the equivalent behavior when pulling to refresh (API on first load, so the mock needed to be cleared).
> fix: load new Explore results when filters change

- src/components/ObsEdit/BottomButtonsContainer.tsx
Closes #2446
- Reset MyObs scroll position when creating new observation in ObsEdit
> Fix: don't jump back to a previous scroll position in MyObs when creating, then editing new observations

- src/components/MyObservations/MyObservationsContainer.js
- src/stores/createUploadObservationsSlice.ts
Closes #2445 
The main issue here was that spreading `...DEFAULT_STATE` to reset the upload state or update the canceled upload state wasn't doing what we thought it was... instead of updating with the actual original, empty state (i.e. `uploadQueue: []`), the existing state was being set again (i.e. `uploadQueue: [upload1, upload2, upload3]`).
So canceling an upload would still have an uploadQueue with all the previous uploads, which would make the animations on individual uploads continue to rotate.
TLDR: be careful to make sure the original state is actually being reset in zustand, particularly when spreading objects.
> Fix: display canceled upload UI correctly

- src/components/ObsDetails/ObsDetails.js
- src/components/ObsDetails/ObsDetailsContainer.js
- src/components/ObsDetails/ObsDetailsOverview.js
Closes #2410 
Removes the spinner that should never ever appear on ObsDetails
> Remove refetching loading wheel on ObsDetails

- src/components/SharedComponents/Map/Map.tsx
+ The map from ObsDetails does not reset after each zoom anymore. A state for the region needed to be introduced and updated after each gesture.
+ The current location button now centers the map on the current location. A callback needed to be called explicitly after `animateToRegion()`.
+ A search in LocationPicker now centers the map on the selected location.  A state for the region needed to be introduced and a callback needed to be called explicitly after `animateToRegion()`.
Closes #2529
Closes #2555
Closes #2593
> Fixes for Map in Android

- src/components/Camera/CameraContainer.tsx
Memoize the boolean passed into trigger this `useEffect`, which should prevent phone from overheating and potential issues with location fetching (since iOS will give up on fetching if you try to fetch too many times in quick succession)
> Fix: log location fetch start without infinite renders

- src/components/Camera/hooks/usePrepareStoreAndNavigate.ts
- src/components/Match/EmptyMapSection.js
- src/components/Match/Match.js
- src/components/Match/MatchContainer.js
- src/components/ObsDetailsDefaultMode/LocationSection/LocationSection.tsx
- src/components/SharedComponents/SimpleObservationLocation.js
Closes MOB-354
- When a user taps the empty map, the empty location text, or the add location button, they will see the location permission gate. If they have already given permissions, they will see the location picker.
> Add location picker / gate to Match screen

- src/components/ObsEdit/DatePicker.tsx
- src/components/SharedComponents/DateTimePicker.js
- tests/integration/ObsDetails.test.js
Closes MOB-347
If observation has a date, show that instead of the current date in the date picker on ObsEdit.
> Fix: Show observation date in ObsEdit date picker

- src/components/SharedComponents/UserText.tsx
> Fix: Keep list items within screen width on ObsDetails

- README.md
- src/api/types.d.ts
- src/components/Explore/helpers/exploreParams.ts
- src/components/Explore/hooks/useInfiniteExploreScroll.js
- src/sharedHooks/useAuthenticatedInfiniteQuery.ts
- tests/factories/RemoteObservation.js
- tests/unit/components/Explore/helpers/exploreParams.test.js
* remove assumed and undocumented meaning of page being zero from our use of useInfiniteScroll in Explore; uses explicit type checks instead
* document byzantine pagination logic in useInfiniteExploreScroll
* fix broken infinite scroll when sorting by faves (was only showing first page)
The underlying problem from 96c316a was setting initialPageParam to 1 in useAuthenticatedInfiniteQuery, which seems rational, except useInfiniteExploreScroll was using a false-ish value of page to detect when it was requesting its first page. This does the same by being more explicit about page's type without injecting undocumented meaning into the params we hand to useInfiniteScroll.
Closes MOB-400
> fix: allow Explore searches in places again

- src/components/Explore/SpeciesView.js
- src/components/MyObservations/MyObservationsSimple.tsx
- src/components/MyObservations/SimpleTaxonGridItem.tsx
- src/components/ObservationsFlashList/ObsImage.js
- src/components/ObservationsFlashList/ObservationsFlashList.js
- tests/unit/components/SharedComponents/ObservationsFlashList/__snapshots__/ObsGridItem.test.js.snap
Closes MOB-116
Anywhere we're using a grid view image (species view, observations grid view on Explore and MyObservations), the images were being recycled and displayed alongside the wrong observation/species.
For future reference, I believe we need three things in place to prevent recycling behavior:
1. An `Image` nested anywhere within the `renderItem` function should have `fadeDuration=0`
2. Items in the `renderItem` function should be given a unique `key` prop
3. The key extractor on the FlashList also needs to have a unique key
This PR also creates a `SimpleTaxonGridItem` for the `ObservationsSimple` species view. I started there because it was a lot easier than trying to figure out what was happening to cause recycling in our very, very nested `ObsImage` component, and because we …
> Prevent cell recycling in FlashList

- src/components/Match/calculateConfidence.js
Fixes an undiscovered bug that the confidence values shown are off by 100 for offline results.
Offline meaning results coming from the vision-plugin, i.e. prediction from file and frame processor.
> fix: confidence off by factor 100 for offline results

- src/api/computerVision.ts
- src/components/Match/AdditionalSuggestions/SuggestionsResult.js
- src/components/Match/Match.js
- src/components/Match/PhotosSection.js
- src/realmModels/Taxon.js
Closes MOB-454
The representative photos are directly pulled from the online suggestions objects and not stored in realm as they only pertain to a certain image being scored.
> Include taxon photo similarity parameter when making online vision api requests for the match screen

- .gitignore
- .husky/pre-commit
- .rubocop.yml
- package.json
We're running a lot of checks on each commit and each commit was starting to feel pretty slow. Trying to make it feel snappier by only linting JavaScript, TypeScript, and Ruby files we actually staged in the latest commit, instead of linting everything. 
Also added caches for eslint and rubocop.
Our Flow check is theoretically also only running on staged files, but it's still slow and apparently why the industry is slowly moving towards TypeScript. If nothing else, this makes it a little easier to visually see that Flow is the slowest part of our precommit.
> Speed up precommits

- package.json
Flow bumps into errors in lint-staging because it's expecting to run on the whole project directory, turns out.
> Fix precommit hook

- ios/Podfile.lock
- src/components/Match/calculateConfidence.js
~~I'm not sure this is the right fix long term, but rather than tracing all the sources of suggestions this simple change handles current and former score properties.~~ In my testing, the old factor computation is no longer needed, as both score and combined_score are using the same 0-100 range.
Update after extensive debugging and testing: For the common ancestor property of iNatVisionAPI results, the node API layer is [renaming](https://github.com/inaturalist/iNaturalistAPI/blob/cf4503c5df13ef757e419dc5de9fcec0e029ad67/lib/controllers/v1/computervision_controller.js#L395) `combined_score` to `score`
They're scaled correctly by the vision api layer, and iNat Next doesn't need to scale anymore, as previously commented.
Fixes MOB-513
> Fix confidence calculation crash when accessing match screen online

- src/components/ObsDetailsDefaultMode/CommunityTaxon.js
- src/components/ObsDetailsDefaultMode/MapSection/MapSection.js
- src/components/ObsDetailsDefaultMode/ObsDetailsDefaultMode.js
- src/components/ObsDetailsDefaultMode/ObsDetailsDefaultModeContainer.js
- src/components/SharedComponents/DisplayTaxon.js
Closes MOB-512
Simple ObsDetail mode is activated only for logged-out users who are not using advanced settings (aka default mode), on observations which have not been uploaded.
- Removes the header, community discussion, details, and more sections.
- Swaps out the match-screen-style taxon display and replaces it with one showing the taxon photo, but with larger fonts per Figma.
- Updates map height to match Figma.
- Fixes a crash when pressing on the taxon display when "Unknown" was shown.
- ~~[ ] Add new tests~~ We might delete this in the morning. I'm not going to spend any more time attempting to write tests for it until we do some user testing.
> Implement simple un-uploaded logged-out mode for ObsDetail

- src/components/Match/MatchContainer.js
- src/sharedHooks/useLocationPermission.tsx
This was introduced because of a misunderstanding of requirements in a previous ticket. Now the permission gate behaves again the same on all screens.
> Remove initial block function from location permission gate

- src/components/Camera/AICamera/FrameProcessorCamera.js
- src/components/Camera/CameraView.tsx
- src/components/Camera/helpers/index.ts
Closes MOB-230: The error logged in this issue for the classifier is potentially outdated. If not this PR here changes the logs to serialize the error object as outlined in the issue. So if the error appears again we shall have more info.
Closes MOB-228: If this error appears again there should be more info what kind of error this is. "unknown/unknown" is a real error though that is thrown from the camera library we are using.
Closes MOB-478 by no longer accessing the message property.
> Adding some more info to errors thrown from camera

- ios/Podfile.lock
- package-lock.json
- package.json
The update is required to run vision model version 2.20.
Should be fully backwards compatible though, so no actual need to update to v2.20.
Have tested with 2.13 and still works as expected.
Have also tested with 2.20 and works as expected.
> Update vision-plugin to prepare for cv model v2.20

- src/components/ObsDetailsDefaultMode/LocationSection/LocationSection.tsx
Possible fix for sharing into app crashing based on the crash report's stack trace.
> Optional access of optional property

- src/components/MyObservations/MyObservationsContainer.js
- src/components/MyObservations/MyObservationsSimple.tsx
- src/components/MyObservations/MyObservationsSimpleHeader.tsx
- src/components/MyObservations/SimpleUploadBannerContainer.js
- src/components/MyObservations/hooks/useSyncObservations.ts
- src/components/MyObservations/hooks/useUploadObservations.ts
- tests/unit/components/MyObservations/useSyncObservations.test.js
Closes MOB-550
This is the quickest solution I could come up with.
Two components to this solution:
- The UI state is calculated based on number of unuploaded observations minus number of observations that have some missing information.
- When the sync button is pressed the uuids of the observations with missing basics are sent along and skipped for the upload process.
> Do not upload observations that have missing location or date when in default mode

- src/components/ObservationsFlashList/ObsPressable.tsx
- src/components/SharedComponents/FlashList/CustomFlashList.tsx
- src/components/SharedComponents/Sheets/BottomSheet.tsx
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/strings.ftl
Closes MOB-553
Closes MOB-548
Also removed the accessible prop from all bottom sheets, which meant that elements inside bottom sheets were not read out.
> Make any CustomFlashList scrollable with Voice Over

- src/sharedHelpers/logging.js
- src/sharedHooks/index.js
- src/sharedHooks/useAuthenticatedInfiniteQuery.ts
- src/sharedHooks/useAuthenticatedMutation.js
- src/sharedHooks/useAuthenticatedQuery.js
- src/sharedHooks/useQuery.ts
- src/sharedHooks/useSafeRoute.js
Related to Mob-207
We have very little information about what's happening when a 429 error gets logged currently, so this should add some context and add a progressive retry for any 429 errors being handled by React Query
> Add error handling for 429 to React Query, including mutations

- src/components/MyObservations/helpers/syncRemoteDeletedObservations.ts
- src/components/MyObservations/helpers/syncRemoteObservations.ts
- src/components/Settings/LanguageSetting.tsx
- src/components/hooks/useLinking.js
- src/sharedHelpers/logging.js
- src/sharedHelpers/uploadObservation.js
- src/sharedHooks/useAuthenticatedMutation.js
Error handling for Mob-445
A few things here:
- More detailed error handling overall for 401 errors at the react-query level
- Add error handling for mutations
- Audit places in the app where we're not using react-query for whatever reason -- a few of them were missing JWT tokens including `fetchAvailableLocales` and `searchObservations` (this is why it's great to standardize the way we're doing things whenever we can)
- Add error handling for `uploadEvidence`, because it's possible that our JWT tokens are expiring before a set of bulk uploads complete (say if a user leaves the MyObservations screen and comes back to ongoing bulk uploads minutes, hours, or days later). For this one, when we refactor uploadObservations we could do more decoupling and intentionally force JWTs to update at …
> Better error handling for missing or invalid jwt errors

- src/components/Match/Match.js
So, in a case of having no top suggestion but low confidence additional suggestions we show all UI available for the match screen, so that a user can potentially also improve them by giving location permission.
Tested with the first photo here: 
https://linear.app/inaturalist/issue/MOB-600/match-screen-special-handling-of-potential-dual-species-situations
> Only show no  suggestions match screen UI without additional suggestions

- src/components/ObsDetailsDefaultMode/CommunitySection/ActivityItem.js
- src/components/ObsDetailsDefaultMode/CommunitySection/CommunitySection.js
- src/i18n/l10n/en.ftl
- src/i18n/strings.ftl
Only show explainer text if we are on the user's obs, if it is an ID of this user and the user has in total less than 10 obs (handled in HOC).
Closes MOB-630
> Fix: id text on every item

- src/components/Camera/AICamera/AICamera.js
- src/components/Camera/AICamera/hooks/usePredictions.ts
- src/components/SharedComponents/TaxonResult.tsx
- src/sharedHelpers/fetchPlaceName.js
- src/sharedHooks/useAuthenticatedQuery.js
- src/sharedHooks/useTaxon.js
- src/sharedHooks/useTaxonSearch.ts
Closes Mob-635
I wasn't able to reproduce this, so taking a multi-pronged approach to avoid lengthy network requests here:
- Make sure we're not accidentally calling the API for iconic taxon whenever there's a new prediction. We fetch that data to store in Realm on app startup, so we can get it directly from Realm instead of the API.
- Set no retries for each TaxonResult (prediction) in the AICamera, since this API is being fetched every second anyway, and it seems wise to make sure these API calls are not stacking up (3 retries each) in low connectivity conditions
- Set a 2.5 second timeout for the geocoded observation place name
> Fix: limit API calls in AICamera to avoid delay in advancing navigation

- src/components/StartupService.js
- src/sharedHelpers/installData.ts
According to the docs, we really shouldn't be creating more than one MMKV instance. It turns out this is exactly the kind of thing that can cause a Signal 11 error, because of excessive memory usage or improper initialization.
I discovered this because I wanted to work on screen transitions and moving the onboarding screens into a react-navigation modal, but when I tried to access the `onboardingShown` data from MMKV in our `rootDrawerNavigator` I could no longer build a release build due to MMKV errors... maybe that instance of MMKV hadn't been initialized yet or was competing for resources?
Anyway, this is a partial fix since we're still creating three MMKV instances, but maybe creating only one new instance for fresh install instead of two instances is helpful.
> Use existing MMKV instance to check for fresh install

- src/realmModels/ObservationPhoto.js
- src/realmModels/ObservationSound.js
- src/sharedHelpers/uploadObservation.js
Another attempt to close MOB-639.
After a lot of looking at our upload code, I realized I didn't take my own advice a few weeks ago to not touch the upload code. I'm now suspicious that [this PR](https://github.com/inaturalist/iNaturalistReactNative/pull/2783) to try to handle jwt errors is actually what recently made bulk uploads spotty. Before that, we hadn't touched that code since November, so I put this upload code back to the state it was in before.
With this reversion, I made a local release build. Unlike the current build from `main` (or in TestFlight) I can now background the app, come back, and see my uploads continue as expected with no photos dropped.
Would be great to review & merge this if it's working for others before the next public release.
> Fix: revert upload code

- src/components/PhotoImporter/GroupPhotos.js
Minor fix to add a white background to the button bar on the GroupPhotos screen.
> MOB-665 - group photos - add white background to import observations button (#2834)

- app.json
- fastlane/metadata/ios/default/name.txt
- ios/InfoPlist.xcstrings
- ios/iNaturalistReactNative/Info.plist
Closes MOB-622
Fixes MOB-672
Forces the rename throughout the untranslatable elements of xcstrings rather than waiting for crowdin to do the same thing.
> Rename iNat Next to iNaturalist

- src/components/MyObservations/MyObservationsEmptySimple.js
- src/components/SharedComponents/Buttons/Button.tsx
- src/components/SharedComponents/Buttons/INatIconButton.tsx
- src/components/SharedComponents/Buttons/PressableWithTracking.tsx
- src/components/SharedComponents/IconicTaxonChooser.tsx
- src/components/styledComponents.js
REVISED: see comments below.
ORIGINAL:
Trying out a simple approach to analytics by logging `Button` taps. If we like this approach, the next step would be to extend this to the rest of our tappable components such as `INatIconButton`.
This currently shows up in the logs as something like what's shown below, which also alerts me to one problem with this approach -- we're translating strings before passing them to the Button, which means we'll be logging text in all languages and making it hard to aggregate any data:
`{"level":"info","message":"Button tap: {\"accessibilityHint\":null,\"accessibilityLabel\":\"APP-SPRACHE ÄNDERN\",\"testID\":null,\"text\":\"APP-SPRACHE ÄNDERN\",\"routeName\":\"Settings\"}","context":"Button","timestamp":"2025-04-14T21:36:42.246Z"}`
I'm blanking on the right …
> Add tracking for Pressable and INatIconButton taps

- src/components/Match/AdditionalSuggestions/SuggestionsResult.js
MOB-692 related. Unsure if this is a fix for this issue.
This is the best I could come up with for now. I could not replicate this error locally.
It would be good to get detailed replication steps.
From experience not accessing any properties of the RealmObject is a good way to avoid this error message. `taxon` is the only RealmObject used in this component so maybe this change addresses it.
It's a bit weird because in the CustomFlashList higher in the stack we already access taxon.id which when I am testing with removing taxon directly from the suggestion error out. So, I am unsure how we can access something lower in the tree when not having it higher already should give a different error.
Anyways, I also checked Kibana to gauge what user actions happen before this error appears but …
> Do not access taxon in SuggestionsResult if none

- src/components/Explore/Modals/FilterModal.tsx
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/strings.ftl
- src/providers/ExploreContext.tsx
Closes MOB-479
Removing the hrank or lrank filter, by selecting "NONE" in the UI did not set it back to a state of `null` but instead set it to a state of `"null"` (= string) which was rejected by the API.
So, now when "NONE" is selected we revert back to null (which means the explore param is not added to the query params). Reverting the UI back to "ALL" when "NONE" is selected in the dropdown menu is wanted behaviour (https://inaturalist.slack.com/archives/C02G5AATVGA/p1743290324244789?thread_ts=1743174700.224619&cid=C02G5AATVGA).
There was also one taxonomic rank that is actually not supported by the API.
> Fix: hrank/lrank 422 api error

- src/components/Onboarding/OnboardingCarousel.js
On Android release builds, imagesLoaded never switched from false to true, and this screen was stuck in a loading state. On iOS it worked as expected. Disabling it now on Android to make a new release possible.
> Do not show loading state on Android

- src/components/Explore/SearchScreens/ExploreTaxonSearch.js
- src/components/SharedComponents/SearchBar.tsx
- src/sharedHooks/useTaxonSearch.ts
Closes Mob-688
- Limits unnecessary re-renders in `useTaxonSearch` (via `useMemo`, cleaning up `useEffect`, and reducing the number of `useEffects`)
- Prevents a *second* API fetch which is the default behavior when using `TaxonResult`
- Adds a debounce to the global `SearchBar`, which still shows the user everything they type in real-time while limiting the number of API calls by only firing when they have stopped typing
> Limit 429 errors in Explore taxa search

- babel.config.js
- src/sharedHelpers/uploadObservation.js
- src/uploaders/index.ts
- src/uploaders/utils/realmSync.ts
- tests/unit/uploaders/utils/realmSync.test.js
Sorry, I messed up the original PR this is a copy of the two commits.
[albullington](https://github.com/albullington) commented [last week](https://github.com/inaturalist/iNaturalistReactNative/pull/2872#issue-3015479987)
Closes [Mob-734](https://linear.app/inaturalist/issue/MOB-734)
This is a sub-issue of a larger issue to start making our upload code easier to maintain. Realm syncing functionality was the most modular and easiest part of the code to break out.
Unit tests were added to make sure functionality didn't change while refactoring. The one exception to this is the very last test, which highlighted that we were swallowing any non-invalidation errors instead of throwing them. I believe throwing these errors is the desired behavior, so made this change & changed the unit test to …
> Copy of: Maintenance: break upload code into smaller modules -- realm syncing functions

- src/components/MyObservations/SimpleUploadBanner.js
- src/components/MyObservations/SimpleUploadBannerContainer.js
- src/stores/createUploadObservationsSlice.ts
- tests/unit/components/MyObservations/SimpleUploadBannerContainer.test.js
Closes MOB-694
Instead of using `numUploadsAttempted` only to show the number of uploaded observations, I have changed to use `numUploadsAttempted - totalUploadErrors` instead. Which in first approximation should be the number of successful uploads, unless I am missing something here. Maybe better in the future would be to have an actual "successful uploads" counter using the actual create/upload response as signal.
I have tested with all obs failing and randomly half of the obs failing (by changing params.observation to {} in observations.js, createObservation which result in a 500 error from server). Both times I think it displays the wanted information now. With all obs failing it only shows the x-failed text. With some failing it shows the x-uploaded and the x-failed test
> Change calculation of successful upload status stats

- fastlane/Fastfile
Only to remove a log that happens for each review while the script is running.
> Remove log from script

- src/components/Camera/AICamera/AICameraButtons.tsx
- src/components/Camera/CameraContainer.tsx
- src/components/Camera/TabletButtons.tsx
I think we should reuse the already existing `takingPhoto` state to disable the camera UI until the user navigates away.
This way we can at a later point also add some error handling, and re-enable the camera if say the first photo taken errors out.
> Move blur effect to CameraContainer

- src/components/Notifications/NotificationsList.tsx
- src/sharedHooks/useInfiniteNotificationsScroll.ts
This came out of a recent user problem where notifications would not load. While the actual error reason was a 500 on the server we are also requesting many more fields here than we actually need for the notifications screen to work.
So, a small cleanup, safeguard, possible speed improvement.
Closes MOB-780
> Request fewer update fields from API

- ios/Podfile.lock
- package-lock.json
- package.json
- tests/unit/components/BottomTabNavigator/CustomTabBar.test.js
Closes MOB-789
Version 4.10.1 adds support for react native 0.74. Upgrading RN to 0.74 without updating this library is breaking compilation on Android for me. I have tested with the latest available version 4.x and everything seems to be in order for it as well. The changes in v4 seem backwards compatible so we can already merge it in as a standalone PR because it is also working on RN 0.73.
> Update react-native-safe-area-context-to >4.10.1

- ios/Podfile.lock
- package-lock.json
- package.json
react-native-screens version 4.5.0 increases the react native version that it supports to 0.74.0+ (https://github.com/software-mansion/react-native-screens/pull/2613/files). So, by using 4.4.0 we are still able to build the app on Android as we are still on 0.73 for now (have tested and it works).
Have not seen any effect on the changes related to the latest react-navigation versions.
> Downgrade react-native-screens to v4.4.0

- src/api/error.js
- src/sharedHooks/useAuthenticatedMutation.js
I don't know what happened to the previous PR. This is a copy of a previous one with only the commits we want to have added. Summary of previous [PR](https://github.com/inaturalist/iNaturalistReactNative/pull/2864):
No description provided.
----------
@[albullington](https://github.com/albullington) albullington [last month](https://github.com/inaturalist/iNaturalistReactNative/pull/2864#discussion_r2054860256)
one problem we're bumping into in 429 errors is that the context is still showing up as null every time. i'm not sure what the core issue is there -- maybe we're not awaiting the  handleError function throughout the app and we need to? I don't think this will fix the core issue or help us add context, unfortunately.
----------
Have updated this PR with the results of the previous …
> MOB-690 - Add error context to 401 errors

- src/components/LoginSignUp/AuthenticationService.ts
- src/uploaders/mediaUploader.ts
- src/uploaders/observationUploader.ts
- tests/integration/ObsEditOnline.test.js
- tests/integration/navigation/ObsEdit.test.js
- tests/unit/uploaders/observationUploader.test.js
Closes Mob-777
- Adds logging to the upload process to help debug what's happening when a batch upload fails. Aiming for the right amount of data to be useful without making logs noisy
- Validates jwt token at each stage of the upload process, to address our hypothesis that a token could expire between the time the user starts the upload process and the time media gets attached to an observation (this would make sense if the user backgrounded the app and came back midway through an upload, or if they had a large batch of uploads and were close to the expiry time when they started uploads)
- Throws errors at each stage of the upload process so we can see where an upload is failing and any errors that bubble up
> Add logging to uploads & validate jwts at each upload step

- tests/helpers/setStoreStateLayout.js
- tests/helpers/uniqueRealm.js
- tests/integration/MyObservations.test.js
- tests/integration/MyObservationsLocalization.test.js
- tests/integration/MyObservationsSimple.test.js
- tests/integration/PhotoDeletion.test.js
- tests/integration/PhotoImport.test.js
- tests/integration/SuggestionsWithSyncedObs.test.js
- tests/integration/SuggestionsWithUnsyncedObs.test.js
- tests/integration/navigation/AICamera.test.js
- tests/integration/navigation/AddObsButton.test.js
- tests/integration/navigation/Explore.test.js
- tests/integration/navigation/MediaViewer.test.js
- tests/integration/navigation/MyObservations.test.js
- tests/integration/navigation/ObsEdit.test.js
- tests/integration/navigation/PhotoLibrary.test.js
- tests/integration/navigation/SoundRecorder.test.js
- tests/integration/navigation/StandardCamera.test.js
- tests/integration/navigation/Suggestions.test.js
- tests/unit/components/BottomTabNavigator/CustomTabBar.test.js
- tests/unit/components/MyObservations/SimpleUploadBannerContainer.test.js
I think this is in line with how we want to setup our integration tests, first let the entire store load it's defaults and then only set the specific flags we want to have for the single test suite. Even though we did not specify the store to be replaced with the object we are passing in in those instances, the `layout` key of the store does get replaced with only the object passed in, i.e. the new object used in the `setState` call is not merged with the existing defaults.
I ran across some issues when I accessed the `shownOnce` key of the `layout` slice from the store in the AddObsButton which is shown prominently in the app, which would have required to setState in all those test files (like it was done [here](https://github.com/inaturalist/iNaturalistReactNative/pull/2932/commits/484e2 …
> Fix: integration tests store setup when changing layout slice

- ios/Podfile.lock
- package-lock.json
- package.json
Version 3.15.x of react-native-reanimated is the minimum version that supports react-native 0.75.x.
This PR is blocking the update to RN 0.75 because in the branch of the RN update the app did not compile on Android with an error message that react-native-reanimated is the culprit. (Have tested to update locally and this PR here actually resolves this issue).
> Update react native reanimated

- ios/Podfile.lock
- package-lock.json
- package.json
- tests/integration/navigation/PhotoLibrary.test.js
- tests/integration/navigation/StandardCamera.test.js
- tests/jest.setup.js
This is another library that currently does not compile with RN 0.75.
According to their GitHub release notes react-native-gesture-handler version 2.18.x introduces support for RN 0.75.
I have no idea what these "time travel" functions are in the updated tests, but I did get them to pass by removing these calls. I think less calls required make for better tests, so I would argue this is correct.
> Update react native gesture handler

- __mocks__/react-native-share-menu.ts
- src/components/App.js
- tests/integration/PhotoSharing.test.js
- tests/unit/components/PhotoSharing.test.js
This is core observation flow functionality that we didn't have any tests for, and unsurprisingly, we often run into unexpected bugs with sharing into the app. Here are some unit and integration tests which should help stabilize this part of the app and allow us to fix bugs/make upgrades/refactor as needed without breaking this functionality.
> Testing: unit & integration tests for sharing photos

- ios/Podfile.lock
- package-lock.json
- package.json
Update of a package in preparation for RN 0.76, react-native-worklets-core v1.5.0 introduces support for RN 0.76.x.
Have compiled for Debug and Release and tested the camera with frame processor which is the only component that uses this.
> Update react native worklets core 1.5.0

- ios/Podfile.lock
- package-lock.json
- package.json
Update of a package in preparation for RN 0.76, react-native-keep-awake v1.3.1 fixes build issues with RN 0.76.x.
Have compiled for Debug and Release and tested that uploading of multiple observations does not let the phone get into sleep mode (auto-Lock on iOS) until upload is finished (+ Auto-Lock time).
> Update react-native-keep-awake to version ^1.3.1

- src/components/Notifications/NotificationsContainer.tsx
- src/sharedHooks/useInfiniteNotificationsScroll.ts
Closes MOB-853
- Fixes a memory leak where `useEffect` would run an infinite amount of times when returning from ObsDetails by running an unsubscribe cleanup on the add focus listener
- Fetch only the fields needed from API (photos, sounds, user_id) instead of fetching and passing around very large observation objects
> Performance: speed up Notifications

- src/components/Projects/hooks/useInfiniteProjectsScroll.ts
didn't make an issue for this, but falls under the general app is slow bucket
> Performance: use only API fields needed for project lists

- src/sharedHooks/useInfiniteNotificationsScroll.ts
Closes MOB-866
Observations that were fetched from server on the notifications screen were inserted into the local database with limited data, because we started requesting less data from the API. The major problem with that was that they were interpreted as having a "Missing date" which on the Me tab sorts them to the top of the list. While not being a data corruption issue per se it looks like something is wrong with the data.
I switched back to request more fields again for observations loaded from notifications. Instead of all fields, we now request the "Advanced fields" which is the max of data we show anywhere in the app.
> Fix: Observations shown without data

- ios/Podfile.lock
- package-lock.json
- package.json
Update of a package in preparation for RN 0.77, react-native-svg v15.11.0 introduces support for RN 0.77.x. But the latest version also compiles.
The only place we use this library is in the PhotoCount component, so wherever we show the number of photos that one observation has inside the icon for multiple photos.
Have compiled for Debug and Release on both platforms and tested that this component still looks okay.
> Update react-native-svg to latest

- ios/Podfile.lock
- package-lock.json
- package.json
Update of a package in preparation for RN 0.77, react-native-safe-area-context v5.1.0 introduces support for RN 0.77.x. on Android. But the latest version also compiles.
Have compiled for Debug and Release on iOS and for Debug on Android (having some build issues on Android but that should not matter for this PR) and tested the app in places where a notched phone should show correct UI.
> Update react-native-safe-area-context to latest

- src/components/LoginSignUp/AuthenticationService.ts
- src/components/LoginSignUp/LoginForm.tsx
- src/components/MyObservations/hooks/useUploadObservations.ts
- src/components/StartupService.js
- src/i18n/l10n/en.ftl
- src/i18n/l10n/en.ftl.json
- src/i18n/strings.ftl
- src/sharedHooks/useTranslation.ts
- src/uploaders/observationUploader.ts
- src/uploaders/utils/errorHandling.ts
- tests/unit/uploaders/utils/errorHandling.test.js
We added a debug button to the app, to log in again. This has been tested by some user, and it does resolve the error of not being able to upload their observations. So, in this PR I am adding a recovery option whenever we hit the error of trying to upload an observation without api token (which will surely fail server side).
As recovery:
Navigate to login screen to login again (which replenishes the api token).
In addition, stop all ongoing uploads if multiple have been queued because they for sure also would error out.
I would not say this PR solves the ticket MOB-851, because it is still possible for the app to arrive at the error state of user not being able to upload. However, I think this workaround is enough to remove the "urgent" label for now.
> Recovery from observations not uploading

- package-lock.json
- package.json
- src/components/AddObsModal/AddObsButton.js
- src/components/AddObsModal/AddObsModal.tsx
- tests/unit/components/AddObsModal/__snapshots__/AddObsButton.test.js.snap
- tests/unit/components/BottomTabNavigator/__snapshots__/CustomTabBar.test.js.snap
Almost closes MOB-785 (see below).
Basically, I think one of the reasons this tooltip was buggy before was that we have a lot of modals opening and closing at the same time. In the case of a user logging in with >50 obs, they would see AccountCreation onboarding modal, tooltip modal, AddObs modal, all in tight sequence.
So, since the only option to leave the tooltip should be to make a long press on the GradientButton that then directly opens the ObsWheel modal, I decided to move the tooltip into the ObsWheel modal itself, and a long-press just switches to the other content. This way we can remove the need for one npm package, and get rid of one modal to modal transition.
Overall, this fixes all bugs I have previously encountered with the tooltip.
One side note though: While I was testing …
> Repair ObsWheel tooltip

- src/components/AddObsModal/AddObsButton.js
This is a small part that was missing in the re-implementation of the obswheel tooltip. It was not implemented because of a bug with the account creation tooltip that is now fixed here: https://github.com/inaturalist/iNaturalistReactNative/pull/3030
Finally, closes MOB-785
> Enable tooltip for new account creation

- ios/Podfile.lock
- package-lock.json
- package.json
Compiled and tested in Debug and Release mode on both platforms.
According to the changelog, this is the last version that supports RN with the old architecture.
Half of [MOB-904](https://linear.app/inaturalist/issue/MOB-904)
> Update react-native-maps to 1.20.1

- src/components/Camera/AICamera/AICamera.js
- src/components/Camera/AICamera/AICameraButtons.tsx
- src/components/Camera/Buttons/PhotoLibraryIcon.tsx
- src/components/Camera/TabletButtons.tsx
- src/components/StartupService.js
- src/sharedHelpers/sentinelFiles.ts
There were two issues here as far as I can see:
1. Sentinel files are created every time the camera starts, and supposedly deleted every time the flow exits without any error. So, when the user closes the camera without error, or takes a photo without error. We were not deleting the files though when the user pressed the gallery button and exited the camera this way, thereby leaving one sentinel file with empty stages on every such time.
2. When it was time to log sentinel files to the server (every app start) we were also sending them to the server when there were no actual stages logged.
So, I have changed to: delete sentinel files when exiting through gallery button, do not log sentinel file that has no stages data, i.e. was created and never interacted with (which means we also don't …
> Do not log empty sentinel files to the server

- ios/Podfile.lock
- package-lock.json
- patches/react-native-share-menu+6.0.0.patch
- src/components/PhotoSharing.tsx
- tests/unit/components/PhotoSharing.test.js
Compiled and tested in Debug and Release mode on iOS and Android.
The actual change in the library to make it run on iOS inside the Podfile code had to be reverted using a patch because the library now only works with static.
> Update react-native-share-menu to build with use_frameworks static
